### ISSUE TITLE
Cannot read 'destroy' of undefined (ripple)

### ISSUE THREAD

**Issue by Egnus** [hperrin/svelte-material-ui#1]
This is an error happening when running the server in a liveReload environment.
When changes are done in the code the page gets broken due to this `destroy` of the ripple and an update of the page is required manually.

Particularly in this line:
https://github.com/hperrin/svelte-material-ui/blob/master/components/ripple/index.js#L26

My proposal is to add a condition before executing the destroy of the instance like:

```javascript
if(instance) instance.destroy();
```

**Comment by Egnus** [comment]
Tested in my local and it worked, currently happening when using storybook (which has its own hot reload system without refreshing the page).
If you need I can do a PR for you.

**Comment by hperrin** [comment]
I believe Svelte has a hot reload system. I'm not sure if it's ready for version 3 though. But, that should solve the problem, without having to change any code.

**Comment by hperrin** [comment]
It looks like this is actually a problem with more than just hot reloading. I'll fix it soon.
