### ISSUE TITLE
Ripple effect does not complete

### ISSUE THREAD

**Issue by aksappy** [hperrin/svelte-material-ui#100]
Hi
The ripple effect on the components do not complete and reset the style of the component. 

Browsers - Microsoft Edge (Chromium) Version 80.0.361.54, FF 72.0.2

Steps to reproduce
1. Go to https://sveltematerialui.com/demo/fab
2. Click on any of the button
3. The ripple effect shade does not go away after the effect is completed or assumed to be completed.
4. Click outside of the component to reset the component.

![Ripple-effect-defect](https://user-images.githubusercontent.com/4348461/74775474-ce9f2e80-5263-11ea-95d3-46f4b89ab36b.gif)

**Comment by cdock1029** [comment]
As intended?

https://material-components.github.io/material-components-web-catalog/#/component/menu

**Comment by krisgun** [comment]
Close issue perhaps?

**Comment by aksappy** [comment]
Closing this as the actual material design guidelines follow the same approach. Many other libraries have chosen to do this differently, and had me confused. 

take care everyone
