### ISSUE TITLE
Unnecessary console.log in updated ripple code

### ISSUE THREAD

**Issue by Egnus** [hperrin/svelte-material-ui#101]
I left a comment directly on the code. Can we disable this by default?

Check any page with ripples, it fills the console with irrelevant info not needed for the majority of the cases. Example: https://sveltematerialui.com/demo/button/

Commented line to delete:
https://github.com/hperrin/svelte-material-ui/commit/550ac93cc6d4dfa18eee70f6c1db55f1971cd8fc#r37438325

**Comment by MintyMods** [comment]
Hi @Egnus,
I have submitted a pull request #103 for this - I find random console logs annoying when you are trying to get a console clear from your own issues  :)

**Comment by Egnus** [comment]
Hi @MintyMods, there is another console.log just a bit below, regarding "removeClass" can you also delete that one as well? I have done this already in my dependency but we know this is not final, only a workaround for now

**Comment by MintyMods** [comment]
Damn, Totally missed that 2nd one and I even searched for instances of log! I have added it to the PR

**Comment by hperrin** [comment]
Oops! Sorry, guys. That’s my bad for leaving that in there.
(-_(\

**Comment by MintyMods** [comment]
> Oops! Sorry, guys. That’s my bad for leaving that in there.
> (-_(\

No worries, my mistakes are much worse than yours ;o)

**Comment by xrd** [comment]
Until this one is fixed, I just used this in `"scripts": { "postinstall" : "bin/fix-smui" }`

`bin/fix-smui`

```
#!/bin/bash
sed -i 's/console.log/\/\/ console.log/' node_modules/@smui/ripple/Ripple.js
```

**Comment by hperrin** [comment]
Fixed.
