### ISSUE TITLE
Crash in transition_out referencing empty outros with Button

### ISSUE THREAD

**Issue by xrd** [hperrin/svelte-material-ui#104]
(package.json: `"svelte-material-ui": "^1.0.0-beta.20"`)

I'm not entirely sure how to reproduce this yet because it happens deep inside my code. But, I see a crash like this:

![Screenshot from 2020-02-28 07-57-51](https://user-images.githubusercontent.com/17064/75563978-24ac6880-5a00-11ea-87c6-da047af69b3f.png)

The simple fix for me was to modify line 708 of the function transition_out in  `@smui/common/node\
_modules/svelte/internal/index.mjs` from this:

```
function transition_out(block, local, detach, callback) {                                                   
    if (block && block.o) {                                                                                 
        if (outroing.has(block))                                                                            
            return;                                                                                         
        outroing.add(block);                                                                                                                                                                    
        outros.c.push(() => {                                                                               
            outroing.delete(block);                                                                         
            if (callback) {                                                                                 
                if (detach)                                                                                 
                    block.d(1);                                                                             
                callback();                                                                                 
            }                                                                                               
        });                                                                                                 
        block.o(local);                                                                                     
    }                                                                                                       
}  
```

```
outrous && outros.c.push(() => {                
```

That fixes it, and I am happy to create a PR, but I'm not sure if this is really the correct fix, or whether there is a problem upstream.

My button code is pretty simple so I don't think it is erroneous usage.

```
<Button variant="raised" on:click={() => choose(option)}>Select</Button>
```

**Comment by hperrin** [comment]
I’m not sure what’s going on here. I haven’t used Svelte outros before. It sounds like it might be a bug in Svelte though. Let’s ask Rich Harris.

**Comment by xrd** [comment]
OK. I wasn't exactly sure how to look at it since it was in the svelte node_modules with your project. Is Rich involved in this project? Should I file a bug in the general svelte project do you think?

**Comment by hperrin** [comment]
Rich runs Svelte, which this project doesn’t have any official affiliation with. You can ask about it in the Svelte discord room. Someone in there can help determine if this is a bug in Svelte. I think there’s a link on svelte.dev.

**Comment by xrd** [comment]
Will do.

**Comment by xrd** [comment]
FYI, I fixed this with a postinstall script:

```
"scripts": {
    ...
    "postinstall" : "bin/fix-smui-svelte"
}
```

`bin/fix-smui-svelte`: 

```
#!/bin/bash

sed -i 's/outros.c.push(() => {/outros \&\& outros.c.push(() => {/' node_modules/@smui/common/node_modules/svelte/internal/index.mjs
```
