### ISSUE TITLE
Tab Scroller - Tab head swipe action in desktop

### ISSUE THREAD

**Issue by knoxjoseph** [hperrin/svelte-material-ui#106]
Hi, 
First of all, this is an impressive project. Secondly, this is a suggestion, not an Issue.
Been trying out the Tab Scroller component. Its good. For my project I need to have the tab heads swipable/scrollable in desktop as well. Is it possible? Like if I drag the Tab heading with a mouse?
I am aware that this works in Mobile.

Thank You once again.

**Comment by hperrin** [comment]
You can hold shift and scroll. I don't have plans to add mouse support, but you could with something like Tinygesture.js.
