### ISSUE TITLE
Feature request: Paper component

### ISSUE THREAD

**Issue by LaughingBubba** [hperrin/svelte-material-ui#11]
Hi would love a Paper component / surface 😃 

PS: If you need a hand with documenting the API or writing tests or other general schlepp work let me know.

**Comment by hperrin** [comment]
@LaughingBubba Hey. Yeah, if you're interested in helping out, I'd greatly appreciate it. 😄 I've started some work on documentation, with the Button component. Check out the readme in there.

**Comment by LaughingBubba** [comment]
Thanks for doing the Paper so quickly. Here's my go at documenting Paper: https://github.com/LaughingBubba/svelte-material-ui/blob/master/components/button/README.md

It's been a couple of years since I've done any PR's. I can't remember if I need to merge my `lb-doco` branch back into my `master` before doing the PR. 

I just wanted to a small bit to see if you're OK with how I write and also go through PR cycle before doing more.

Anyways you can IM me on discord: https://discord.gg/aUfEgUw

Just be mindful that I'm +10 GMT and it's time to snuggle up to the Mrs and some Netflix :smiley:
