### ISSUE TITLE
Snackbar won't reopen when navigating before timeout

### ISSUE THREAD

**Issue by rothnic** [hperrin/svelte-material-ui#111]
I'm using the snackbar with sapper and discovered I was having the same issue as mentioned in Issue #53, but found a workaround. However, I quickly noticed another issue. 

* Trigger the snackbar, then wait till the snackbar dismisses naturally via the timeout, then navigate to another page
* Trigger the snackbar again, and you'll see it show up, as expected
* Trigger the snackbar, then navigate to another page before the snackbar timeout runs out
* Go back to the original page, and trigger the snackbar again. This time, **it won't show up** 

I found a way to fix it, but not sure if it is the right way of going about it. I modified the library locally and added `export` to `function handleClosed()` in [snackbar.svelte](https://github.com/hperrin/svelte-material-ui/blob/master/packages/snackbar/Snackbar.svelte#L82). I then added the following function to my page's script tag where the snackbar is being triggered: `onDestroy(() => {mySnackbar.handleClosed()});`. After making this change, it will be retriggered each time I return to the page.

**Comment by rothnic** [comment]
After a little more digging, I tried using `.forceOpen()` instead of `.open()` and that also appears to resolve the issue. Should this be required?

**Comment by lkalinowski** [comment]
First I did similar workaround as you - using handleClosed function.
For now the best solution for me is having only one Snackbar in my whole app, which I manage through store. No more problems with reopening.
I did the same with progress indicator.

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.

**Comment by JavRedstone** [comment]
This issue still seems to persists in snackbar v7.0.0. The simplest solution so far is to use `.forceOpen()` as @rothnic mentioned. Normal `.open()` does not open the snackbar unfortunately.
