### ISSUE TITLE
Text in select component has unwanted displacement in Mozilla browser.

### ISSUE THREAD

**Issue by klavobit** [hperrin/svelte-material-ui#113]
Screenshot from https://sveltematerialui.com/demo/select/ :
![image](https://user-images.githubusercontent.com/23148482/76866387-20dc6b00-6875-11ea-85b9-546a930cbf0b.png)
How it looks in my project:
![image](https://user-images.githubusercontent.com/23148482/76867162-343c0600-6876-11ea-8369-7a01638903ba.png)
Property in observe of element :
![image](https://user-images.githubusercontent.com/23148482/76866050-a01d6f00-6874-11ea-88b6-578b2952941a.png)
Css code:
![image](https://user-images.githubusercontent.com/23148482/76866088-ad3a5e00-6874-11ea-9a94-3ca7cc18e833.png)

**Comment by hperrin** [comment]
This seems to be fixed now, as I've tested in Firefox.
