### ISSUE TITLE
Textfield does not pass prop for step, when used as number

### ISSUE THREAD

**Issue by Escalion** [hperrin/svelte-material-ui#115]
The Textfield component supports passing the input type as number, however does not support the step prop.
```
<Textfield on:change={validateRange} bind:value={value} type="number" step="0.1" label={label} />
```
Expected result: The up down buttons operate in steps of 0.1
Actual result: The up down buttons operate in steps of 1

This also applies to min and max props. Possibly more, if anyone find any add to this issue.

**Comment by hperrin** [comment]
I added a demo to show how to achieve the same effect as the PR with the `input$step` prop. This keeps the code a bit cleaner, since the Textfield component wasn't using those props anyway.

**Comment by hperrin** [comment]
So for step, min, and max, you can use
```js
<Textfield on:change={validateRange} bind:value={value} type="number" input$step="0.1" input$min="0" input$max="1" label={label} />
```
