### ISSUE TITLE
Would be great to translate Box, Container, Grid, Grid List, and Hidden (from Material UI) into Svelte components

### ISSUE THREAD

**Issue by x80486** [hperrin/svelte-material-ui#118]
- https://material-ui.com/components/box/
- https://material-ui.com/components/container/
- https://material-ui.com/components/grid/
- https://material-ui.com/components/grid-list/
- https://material-ui.com/components/hidden/

**Comment by nateshmbhat** [comment]
is there any plan for this ? @hperrin  
these would be really helpful

**Comment by hperrin** [comment]
I believe this is essentially done, with the (relatively) new layout grid component.

**Comment by mather** [comment]
> I believe this is essentially done, with the (relatively) new layout grid component.
Some examples help users, I think.
