### ISSUE TITLE
Show the code with the UI component

### ISSUE THREAD

**Issue by locohost** [hperrin/svelte-material-ui#119]
Please, please, please include and show the code above each UI control visual example. The visual examples all look fantastic, but we neeeeed the code that generates each right there.

Thank you very much for this awesome Svelte/MaterialUI project!

**Comment by confraria** [comment]
I've been looking at a way to this by adding a rollup plugin to the site config and adding a html comment around the example blocks
```js
{
        name: 'svelte-example',
        transform(code, id) {
          const matchId = /routes.demo..+\.svelte$/;
          if (matchId.test(id)) {
            const matcher = /<!-- example -->([\s\S]+)<!-- \/example -->/g;
            return code.replace(matcher, (match, code) => {
              const highlighted = PrismJS.highlight(
                code,
                PrismJS.languages.markup,
                'markup',
              );
              return `${code}<pre class='language-markup'><code>${highlighted}</code></pre>`;
            });
          }
          return null;
        }
      },
```
it kind of works but was wondering if anyone had another approach in mind
<img width="1488" alt="screenshot of code in the docs" src="https://user-images.githubusercontent.com/84892/79080750-81918300-7d0f-11ea-85c7-5382ff9d014a.png">

**Comment by MintyMods** [comment]
Similar to issue #95

**Comment by confraria** [comment]
Yeah. it's exactly the same. let's talk there.

**Comment by hperrin** [comment]
Do you think the solution in #95 would be good enough, or do I need inline code? Some of the demo pages are pretty long.

**Comment by confraria** [comment]
having copy paste examples directly from the docs is always a plus imho. i was thinking to do some experiments to move the examples into each packages/*  and finally have the website aggregate everything, including the markdown docs.
do you think it's worth the effort?

**Comment by Egnus** [comment]
sorry I couldn't help @hperrin as I said to do this.
Yes, +1 for inline code, but not pasted, since the code can be updated, my suggestion is to iframe the source raw code and use the language markup over it.
Any update on the demo code will automatically update the rest.

Also, for those long pages or you divide the content in 2 columns or you can set a limit height and scroll on it.
Lastly, having a link to the code will be also good to increase readability. (not to raw source but the githup prettier source version)

**Comment by hperrin** [comment]
Maybe this might help: https://github.com/finom/github-embed

**Comment by hperrin** [comment]
I forgot to close this, but this is done now. :D

The new demos are a lot more informative, sectioned out better, and documented much better.
