### ISSUE TITLE
Select enhanced: on:change / on:input not triggering

### ISSUE THREAD

**Issue by Krisa** [hperrin/svelte-material-ui#121]
`on:change` and `on:input` handlers are not triggering when using `enhanced`

**Comment by DougAnderson444** [comment]
Also, on:blur must be used instead of on:change, unless absolutely necessary and it causes no negative consequences for keyboard only or screen reader users.

here

https://github.com/hperrin/svelte-material-ui/blob/b2c366bdb001a6c49d976ea91add93343557a56f/packages/select/Select.svelte#L28

and here:

https://github.com/hperrin/svelte-material-ui/blob/b2c366bdb001a6c49d976ea91add93343557a56f/packages/select/Select.svelte#L57

**Comment by smoglica** [comment]
This is the warning message that I get from webpack (`svelte-loader`) when I use the `Select.svelte` component.

```bash
WARNING in ./node_modules/@smui/select/Select.svelte
Module Warning (from ./node_modules/svelte-loader/index.js):
A11y: on:blur must be used instead of on:change, unless absolutely necessary and it causes no negative consequences for keyboard only or screen reader users. (50:4)
48:     </Menu>
49:   {:else}
50:     <select
        ^
51:       bind:this={inputElement}
52:       use:useActions={input$use}
 @ ./node_modules/@smui/select/bare.js 1:0-37 5:15-21
 @ ./node_modules/@smui/select/index.js
 @ ./src/components/molecules/Block/Block.svelte
 @ ./src/components/molecules/Block/index.js
 @ ./src/components/molecules/Block/Block.stories.js
 @ ./src sync ^\.\/(?:(?:|\/|(?:(?:(?!(?:|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:\[tj\]|[tj])s)$
 @ ./docs/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./docs/preview.js ./docs/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```

**Comment by DougAnderson444** [comment]
Pull request to fix this: https://github.com/hperrin/svelte-material-ui/pull/139

**Comment by hperrin** [comment]
Is this only happening when using enhanced, or always?

**Comment by hperrin** [comment]
It looks like this only applies to <select> elements:
https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-onchange.md
