### ISSUE TITLE
Demo website shows radio buttons on form fields tab.

### ISSUE THREAD

**Issue by jrbrodie77** [hperrin/svelte-material-ui#124]
This project is amazing!

Clicked through all the examples on the website.  I notice that under "Inputs and Controls" there is a section called "Form Fields".  Clicking on Form Fields navigates to Radio Buttons.

**Comment by hperrin** [comment]
Thanks for the kind words! :D And thank you for pointing this out. Now that the demos link to their components, this was definitely a big issue.
