### ISSUE TITLE
"[Violation] Added non-passive event listener ..." issue?

### ISSUE THREAD

**Issue by countnazgul** [hperrin/svelte-material-ui#128]
I'm getting some REST data and displaying the result on a web page (using mostly the Card component). And noticed a delay between when the data is received and when the card components are displayed. The delay is in order of 1-2-3 seconds (depends how many card are being displayed) 

I've started to investigate and saw the below in Chrome console (when enable the `Verbose` logging)

![image](https://user-images.githubusercontent.com/22850/81545692-2768f980-9371-11ea-8afa-5c8a097c5455.png)

When I expand one of the event I can see that SMUI is being mentioned few times ( the first mention is for `forwardEvents.js`)

Any idea if this is something to do with `SMUI` itself or its svelte/browser issue?

Thanks!

**Comment by userquin** [comment]
See this https://github.com/hperrin/svelte-material-ui/issues/83

**Comment by countnazgul** [comment]
Thanks! Not sure how ive missed this issue!

**Comment by hperrin** [comment]
Fixed!

See here: https://github.com/hperrin/svelte-material-ui/issues/83#issuecomment-820699306
