### ISSUE TITLE
cant get standard input

### ISSUE THREAD

**Issue by greaka** [hperrin/svelte-material-ui#13]
when i try the code from the demo or from the readme, i always get the filled input, how can i make the standard work?

![image](https://user-images.githubusercontent.com/2805834/63097444-bbd43600-bf70-11e9-9cd7-59b9546e086d.png)

**Comment by hperrin** [comment]
If you're using the NPM package, I haven't published one that includes that styling yet.

**Comment by greaka** [comment]
i see

how can i reproduce the demo styles then?

**Comment by hperrin** [comment]
I released a new NPM version that has this feature.
