### ISSUE TITLE
Unable to use grid

### ISSUE THREAD

**Issue by twkrol** [hperrin/svelte-material-ui#130]
Hi.
I'm quite new to svelte and started to use svelte-material-ui.
I would like to use MDC layout grid, but I'm unable to.

I've put the follwing in _smui-theme.scss

`@import "@material/layout-grid/mdc-layout-grid";`

but got error during compilation:

> [!] (plugin postcss) Error: Invalid CSS after "...ch $size in map": expected expression (e.g. 1px, bold), was ".keys(variables.$co"
node_modules/@smui/button/_index.scss
Error: Invalid CSS after "...ch $size in map": expected expression (e.g. 1px, bold), was ".keys(variables.$co"

What should I do to use MDC grid system?

**Comment by bignol** [comment]
Hey twkrol, I ran into the same issue. I was able to get this working by uninstalling node-sass and installing sass. I am not sure what the implications of this might be (haven't fully tested) but I hope it helps.

Thanks,
Nolan

**Comment by hperrin** [comment]
There's now a component for layout grid within SMUI. :)
