### ISSUE TITLE
@smui/common shouldn't have svelte as a dependency

### ISSUE THREAD

**Issue by RedHatter** [hperrin/svelte-material-ui#138]
`@smui/common` currently has svelte as a dependency. This causes svelte to be bundled multiple times which causes various errors. One solution would be to set svelte as a peer dependency.

**Comment by hperrin** [comment]
Hmm. I can look into this.

**Comment by hperrin** [comment]
Fixed with 2c1b1370e10503110421bd66bcb31a81e57cf182.
