### ISSUE TITLE
Storybook integration

### ISSUE THREAD

**Issue by KamranKhan-Dev** [hperrin/svelte-material-ui#142]
Has anyone been able to get this library to integrate with Storybook?

I'm using Sapper and I haven't been able to get this to integrate.

**Comment by dbrrt** [comment]
@KamranKhan-Dev I'm currently working on it and still facing some issues with `scss` file import, despite having configured loaders in webpack and config.

Have you been able to integrate some stories with some components from this library in storybook?

**Comment by xrd** [comment]
@KamranKhan-Dev @dbrrt I have it working with multiple projects, but I am using webpack (sounds like you are as well). Can you post the errors you are having? I can probably help.

**Comment by dbrrt** [comment]
@xrd 

Here's the error stack
```
ERROR in ./node_modules/@smui/button/_index.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import "smui-theme";
| @import "./style";
```

and my webpack configuration for Storybook looks like that:
```JavaScript
const path = require('path');

module.exports = async ({ config }) => {

  config.module.rules.push({
    test: /\.s[ac]ss$/i,
    use: ['style-loader', 'css-loader', 'sass-loader'],
    include: path.resolve(__dirname, '../src'),
    exclude: path.resolve(__dirname, '../node_modules')
  });

  config.module.rules.push({
    test: [/\.stories\.[tj]s$/],
    loaders: [require.resolve('@storybook/source-loader')],
    include: [path.resolve(__dirname, '../src')],
    enforce: 'pre'
  });
  return config;
};
```

**Comment by xrd** [comment]
@dbrrt, first things first: you do have a file (mine is empty) called ` src/_theme/_smui-theme.scss`, right? That's part of the setup for smui.

As a reference, if I clone this repository:

https://github.com/hperrin/smui-example-webpack

And, then run:

`npx -p @storybook/cli sb init --type svelte && yarn storybook` 

Storybook then works for me.

But, if that's not a way to troubleshoot for you, another project I have uses this `.stories/main.js`

```
const sassOptions = {
        sassOptions: {
                includePaths: [
                        './node_modules',
                        './src/_theme/'
                ],
        }
};

module.exports = {

  stories: ['../stories/**/*.stories.js'],
  addons: ['@storybook/addon-actions', '@storybook/addon-links'],

  webpackFinal: async (config, { configType }) => {
   // Make whatever fine-grained changes you need
   config.module.rules.push(
    {
      test: /\.(sa|sc|c)ss$/,
      use: [
        'style-loader',
        'css-loader',
        {
          loader: 'sass-loader',
          options: {
            ...sassOptions
          },
        },
      ]
    },
   )
   return config;
  }
};
```
I don't recall if this matters here, but I also have this in my webpack.config.js file:

```
...
      {
        test: /\.(sa|sc)ss$/,
        use: [
          /**
           * MiniCssExtractPlugin doesn't support HMR.
           * For developing, use 'style-loader' instead.
           * */
          prod ? MiniCssExtractPlugin.loader : 'style-loader',
          'css-loader',
          {
            loader: 'sass-loader',
            options: {
              ...sassOptions,
            },
          },
        ],
      },
...
```

**Comment by dbrrt** [comment]
@xrd Thanks, I just tweaked my webpack file used by storybook and the problem went away.
The theme file wasn't imported correctly.

**Comment by janat08** [comment]
@hperrin I think like the other material svelte package we should use storybook for docs. The storybook in those docs don't seem to be able to use slots though, so you can't really tell what they do (for list components).
