### ISSUE TITLE
Should we import svgs instead of using fonts?

### ISSUE THREAD

**Issue by mitkonikov** [hperrin/svelte-material-ui#147]
I love the Material UI Icons, they have so many variations of them. We should just extract the svgs from the Material UI Icons package and put them in svelte components. I am only wondering if we should use svelte components or js files?

I would love to hear your opinion on it.

**Comment by mitkonikov** [comment]
I already extracted all the Icons and generated svelte components for each one. This will speed up the performance and also give much more customizability to the Icons.

[Here](https://github.com/mitkonikov/Miscellaneous-Projects/tree/master/SvelteMaterial-Icons) is the link.

Because of the number of icons in the 'icons' folder, you may not be able to see the `util` folder, but there is one. The util folder contains scss and SvgIcon svelte component which includes component customization. You can just import the 'icons' folder as another package in SMUI or tell me to make a Pull Request.

[Here](https://github.com/mitkonikov/Miscellaneous-Projects/tree/master/SvelteStartup) is a project which is a demo and uses the extracted icons.

```svelte
<script>
    import AccessAlarm from './icons/AccessAlarm.svelte';
</script>

<AccessAlarm color="#fff"/>
```

* The default color is primary from the material theme.

**Comment by hperrin** [comment]
I believe there is an icon button demo that shows how to do this.
