### ISSUE TITLE
How do we use custom fonts?

### ISSUE THREAD

**Issue by elbertwang3** [hperrin/svelte-material-ui#148]
I can't figure out how to use a custom font with SMUI. Do I do this in the _smui-theme.scss file?

**Comment by Zahara-Nour** [comment]
I put this in _smui-theme.scss  to use Roboto 

```
@import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500');
$mdc-typography-font-family: unquote("Roboto, sans-serif");
```

**Comment by orenwang** [comment]
> I put this in _smui-theme.scss to use Roboto
> 
> ```
> @import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500');
> $mdc-typography-font-family: unquote("Roboto, sans-serif");
> ```

Note that you could simply put this in your **theme/_smui-theme.scss** or **theme/dark/_smui-theme.scss**:
```css
@use '@material/typography/mdc-typography.import' with (
  $mdc-typography-font-family: unquote("'Your Custom Font', 'Roboto', sans-serif")
);
```

And when you run `npm run prepare`, smui elements will try to use 'Your custom Font' first.
