### ISSUE TITLE
Checkbox Questions

### ISSUE THREAD

**Issue by LaughingBubba** [hperrin/svelte-material-ui#15]
1) Props: `value` vs `checked` ? Looks like `value` is used with group checkboxes but potentially you could pass in contradictory values 
```html
<Checkbox checked={true} value={false} />
```

2) Does the `Checkbox` *have* to be wrapped in `<FormField/>` ?

**Comment by caschbre** [comment]
> 1. Props: `value` vs `checked` ? Looks like `value` is used with group checkboxes but potentially you could pass in contradictory values
> 
> ```
> <Checkbox checked={true} value={false} />
> ```

The checked and value props align with the [HTML spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#Additional_attributes).


> 1. Does the `Checkbox` _have_ to be wrapped in `<FormField/>` ?

It doesn't haven't to be according to [material.io spec](https://material.io/develop/web/components/input-controls/checkboxes/) but it is recommended.

> "We recommend using MDC Checkbox with MDC Form Field for enhancements such as label alignment, label activation of the ripple interaction effect, and RTL-awareness."

**Comment by hperrin** [comment]
I added an explanation about the checked and value props in the readme that @LaughingBubba wrote.

**Comment by LaughingBubba** [comment]
@hperrin cheers
