### ISSUE TITLE
Issues with pnpm (can't resolve module)

### ISSUE THREAD

**Issue by unlocomqx** [hperrin/svelte-material-ui#150]
I encountered issues when using pnpm
I found a solution and wanted to post it in case someone finds it useful or if you'd like to add to the docs

The issue when using the `svelte-material-ui`, normally the sub packages get installed under `node_modules` directly, but in the case of pnpm, they go under `node_modules/.pnpm` and `node_modules/.pnpm/node_modules`. So we need to add these two dirs to the webpack and sass resolve configuration

Webpack
```
modules: [
  'node_modules',
  path.resolve('./node_modules/.pnpm'),
  path.resolve('./node_modules/.pnpm/node_modules'),
  // ...
],
```

Sass rule
```
{
  loader: "sass-loader",
  options: {
    sassOptions: {
      includePaths: [
        path.join(__dir, "/node_modules/"),
        path.join(__dir, "/node_modules/.pnpm/"),
        path.join(__dir, "/node_modules/.pnpm/node_modules/"),
      ]
    }
  }
},
```

I'll try to ping the pnpm dev, he probably got a better solution

**Comment by hperrin** [comment]
Thanks for posting the solution! 😀
