### ISSUE TITLE
I don't understand how to install this

### ISSUE THREAD

**Issue by wktdev** [hperrin/svelte-material-ui#157]
Hi. I downloaded the "webpack" template and did "npm install" and I got a big load of errors:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/es-abstract/-/es-abstract-1.14.0.tgz
npm ERR! 404 
npm ERR! 404  'es-abstract@1.14.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'svelte-webpack-template-master'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-06T21_10_54_965Z-debug.log
wktdev@pop-os:~/Desktop/app/svelte-webpack-template-master$

```

My goal is to use Routify (https://routify.dev/) with Material UI and their is no step by step instructions on how to incorporate Material Ui into the Routify template. In my Routify template project I originally did "npm install --save-dev svelte-material-ui" and it installed correctly without errors. However, when I tried to reference a Material UI component I got this error:

```
Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
node_modules/@smui/button/_index.scss (1:0)

```

Can anyone help me?

Thank you!

BTW - I have installed sass, svelte-preprocessor and it still doesn't work.

**Comment by previ** [comment]
In my case, I followed [this](https://github.com/hperrin/svelte-material-ui#integration-for-sapper), it works but now I have problems with CSS.

**Comment by Frioo** [comment]
This is what I use to get SMUI working with Sapper and Sass, but I use rollup, as I experienced some issues with webpack.

### Clone sapper-template-rollup
`git clone https://github.com/sveltejs/sapper-template-rollup.git my-project`

### Install dependencies
`npm install`

### Add packages: node-sass and svelte-preprocess-sass
`npm install --save-dev svelte-material-ui node-sass svelte-preprocess-sass postcss rollup-plugin-sass`
* svelte-preprocess-sass for `<style lang="sass">` tags
* postcss and rollup-plugin-sass for resolving`.scss` imports

### Add packages: @smui/button, ...
`npm i -D @smui/button ...`

### Add fonts and icons (template.html)
```
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,600,700">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono">
```

### Edit rollup.config.js
```
import postcss from 'rollup-plugin-postcss';
import { sass } from "svelte-preprocess-scss";
const postcssOptions = () => ({
  extensions: ['.scss', '.sass'],
  extract: false,
  minimize: true,
  use: [
    ['sass', {
      includePaths: [
        './src/theme',
        './node_modules',
        //'./static/sass'
      ]
    }]
  ]
});

plugins: [
  ...
  svelte({
    ...
    preprocess: {
      style: sass({
        // Options for compiling Svelte tag: <style lang="scss">
        includePaths: ["./node_modules"],
      }),
    }
  }),
  ...
  postcss(postcssOptions()),
]
```

SAME FOR SERVER MODULE

**Comment by avisangray** [comment]
+1 documentation is very unclear. also templates are outdated and don't work either with latest versions of svelte

**Comment by LucianVoju** [comment]
Not working with latest sapper template

**Comment by SumitBando** [comment]
Instructions were not helpful for me to be able to integrate into a project using routify.

Documentation saying 'use a Sass processor (not a Sass Svelte preprocessor, but a Sass processor)' is not very helpful.
Documenting dependencies may be a little more helpful, e.g.: 'npm install --save-dev node-sass svelte-preprocess-sass postcss rollup-plugin-sass' or whatever

**Comment by cliveportman** [comment]
> Not working with latest sapper template
Did you get anywhere?

**Comment by FunMiles** [comment]
I am having a similar issue. I cannot get this working with webpack and can't move to rollup for most of my projects because there's no solid rollup web-worker tools.
This is very frustrating. Does anyone have a working webpack example on github?

**Comment by marekdedic** [comment]
https://github.com/skaut/shared-drive-mover#svelte

**Comment by FunMiles** [comment]
> https://github.com/skaut/shared-drive-mover/tree/svelte

Are you sure this is the right URL? I am not seeing any svelte code or material-ui in it.

**Comment by marekdedic** [comment]
> Are you sure this is the right URL? I am not seeing any svelte code or material-ui in it.

Look at `frontend.webpack.config.js` and `src/frontend`...

**Comment by FunMiles** [comment]
Based on your webpack config file to modify mine, I get:
```
 modules by path ./node_modules/ 8.39 KiB
    modules with errors 156 bytes [errors]
      ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./node_modules/@smui/top-app-bar/_index.scss 39 bytes [built] [code generated] [1 error]
      ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./node_modules/@smui/icon-button/_index.scss 39 bytes [built] [code generated] [1 error]
      ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./node_modules/@smui/checkbox/_index.scss 39 bytes [built] [code generated] [1 error]
      ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./node_modules/@smui/form-field/_index.scss 39 bytes [built] [code generated] [1 error]
    ./node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js 6.67 KiB [built] [code generated]
    ./node_modules/css-loader/dist/runtime/api.js 1.57 KiB [built] [code generated]
  modules by path ./src/ 137 KiB
    ./src/main.ts + 36 modules 136 KiB [built] [code generated]
    ./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./src/global.css 1.01 KiB [built] [code generated]

ERROR in ./node_modules/@smui/checkbox/_index.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./node_modules/@smui/checkbox/_index.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: File to import not found or unreadable: smui-theme.
        on line 1 of node_modules/@smui/checkbox/_index.scss
>> @import "smui-theme";

```

**Comment by marekdedic** [comment]
Do you have a `_smui-theme.scss`?

> PS: I don't know how to clone your project. When cloning https://github.com/skaut/shared-drive-mover.git I get some vue code instead, which explains my last post before this one.

Switch to the `svelte` branch.

**Comment by FunMiles** [comment]
@marekdedic Thanks for the hint about the branch. Didn't think of that.

For the `_smui-theme.sccs` I do have it. I had it in the wrong directory however. `theme/_smui-theme.scss`. Moving it directly to my source directory fixed the issue. Thanks.

**Comment by hperrin** [comment]
As of v4, there are now much easier steps to install, and a `smui-theme` package for building SMUI's CSS. Check out the new installation instructions:

https://sveltematerialui.com/INSTALL.md/
