### ISSUE TITLE
[Site Enhancement] Add Install Instruction on Demo Pages

### ISSUE THREAD

**Issue by akhil-vineti** [hperrin/svelte-material-ui#159]
- Adding installation instruction for every component on respective demo page would a lot helpful.

Please see the attached screenshot with the installation instruction:
![image](https://user-images.githubusercontent.com/52163474/90334477-80d56a00-dfeb-11ea-8ec2-bd78d1fae18a.png)

@hperrin Please let me know if it looks good. In case we find it helpful, I would love adding that on each and every demo page.

**Comment by hperrin** [comment]
Done!
