### ISSUE TITLE
Installation instructions with Sapper need improving

### ISSUE THREAD

**Issue by cliveportman** [hperrin/svelte-material-ui#161]
I really like the look of this package but am unable to get it working. I'm using a fresh Sapper install and have followed the instructions in the Readme without any errors. But there is absolutely zero styling being applied to my app. Event the CSS in my Svelte files is being ignored.

I appreciate the work that's been done on this and would love to contribute in future but it's all for nothing if no-one can install it.

**Comment by csaltos** [comment]
Here you may find a source reference to use svelte-material-ui with Sapper -> https://dev.to/csaltos/sapper-with-material-ui-35id

Please also vote for the PR https://github.com/hperrin/svelte-material-ui/pull/174 to have the README updated for nowadays Sapper and Svelte versions.

**Comment by hperrin** [comment]
That PR has been merged, so the latest instructions should work now. :)
