### ISSUE TITLE
rollup-plugin-postcss breaks css generation.

### ISSUE THREAD

**Issue by c19** [hperrin/svelte-material-ui#162]
I did what the doc says to include rollup-plugin-postcss. but failed catastrophically. (all css files generated has "export default undefined" instread of css.

**Comment by csaltos** [comment]
Yes, it's a known error, please set postcss configuration with extract to false and it will work. If you are using Sapper you may also change emitCss to false and css to true at the client section.

More info about a Sapper reference at https://dev.to/csaltos/sapper-with-material-ui-35id

**Comment by hperrin** [comment]
The latest instructions should work now.
