### ISSUE TITLE
Textfield focus

### ISSUE THREAD

**Issue by Zahara-Nour** [hperrin/svelte-material-ui#165]
Is there a way to programmatically get focus on TextField component ? I don't think the bind:this directive can be forwarded to the inner input element, so how to do that ?

**Comment by Zahara-Nour** [comment]
Ok I managed to do it. As I wanted the focus when the TextField is mount, I used an action.

``` 
<script>
function focus(node) {
  node.focus()
}
</script>

<TextField use={[focus]} />
```

**Comment by hperrin** [comment]
The TextField component now supports `on:blue` and `on:focus`. :)
