### ISSUE TITLE
TextField on focus styles input wrongly

### ISSUE THREAD

**Issue by rotimi-best** [hperrin/svelte-material-ui#169]
When I focus on an input it moves the border-bottom-color beneath the bottom of the input rather than on the bottom line. I copied the same code from the text-field docs

## Code
```js
<div>

  <div>
    <Textfield bind:value={name} label="Name" />

    <pre class="status">Value: {name}</pre>
  </div>
</div>

<script>
  import Textfield from '@smui/textfield';

  let name = '';
</script>
```

## Result
![image](https://user-images.githubusercontent.com/31730715/92685337-2dcbaa00-f340-11ea-97bb-f09ad184366b.png)

## package.json
```json
{
  "name": "svelte-app",
  "version": "1.0.0",
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w",
    "start": "sirv public"
  },
  "devDependencies": {
    "@rollup/plugin-alias": "^3.1.1",
    "@rollup/plugin-commonjs": "^14.0.0",
    "@rollup/plugin-node-resolve": "^8.4.0",
    "@rollup/plugin-replace": "^2.3.3",
    "@smui/textfield": "^1.0.0",
    "node-sass": "^4.14.1",
    "rollup": "^2.3.4",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-postcss": "^3.1.8",
    "rollup-plugin-scss": "^2.6.0",
    "rollup-plugin-svelte": "^6.0.0",
    "rollup-plugin-terser": "^7.0.0",
    "svelte": "^3.24.1"
  },
  "dependencies": {
    "sirv-cli": "^1.0.0"
  }
}
```

## rollup.config.js
```js
import svelte from 'rollup-plugin-svelte';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import postcss from 'rollup-plugin-postcss';

const production = !process.env.ROLLUP_WATCH;

function serve() {
  let server;

  function toExit() {
    if (server) server.kill(0);
  }

  return {
    writeBundle() {
      if (server) return;
      server = require('child_process').spawn('npm', ['run', 'start', '--', '--dev'], {
        stdio: ['ignore', 'inherit', 'inherit'],
        shell: true
      });

      process.on('SIGTERM', toExit);
      process.on('exit', toExit);
    }
  };
}

export default {
  input: 'src/main.js',
  output: {
    sourcemap: true,
    format: 'iife',
    name: 'app',
    file: 'public/build/bundle.js'
  },
  plugins: [
    svelte({
      // enable run-time checks when not in production
      dev: !production,
      // we'll extract any component CSS out into
      // a separate file - better for performance
      css: css => {
        css.write('bundle.css');
      }
    }),
    postcss({
      extract: true,
      minimize: true,
      use: [
        ['sass', {
          includePaths: [
            './src/theme',
            './node_modules'
          ]
        }]
      ]
    }),

    // If you have external dependencies installed from
    // npm, you'll most likely need these plugins. In
    // some cases you'll need additional configuration -
    // consult the documentation for details:
    // https://github.com/rollup/plugins/tree/master/packages/commonjs
    resolve({
      browser: true,
      dedupe: ['svelte']
    }),
    commonjs(),

    // In dev mode, call `npm run start` once
    // the bundle has been generated
    !production && serve(),

    // Watch the `public` directory and refresh the
    // browser on changes when not in production
    !production && livereload('public'),

    // If we're building for production (npm run build
    // instead of npm run dev), minify
    production && terser()
  ],
  watch: {
    clearScreen: false
  }
};
```

**Comment by kota-yata** [comment]
I got the literally same issue...

**Comment by csaltos** [comment]
I found the bug -> PostCSS breaks the CSS generation ... for fixing it please set `extract` to `false` at the postcss configuration of your rollup.config.js file.

Please find here a repo with a working solution -> https://github.com/csaltos/smui-issue-169-textfield-error

**NOTE**: if you are using Sapper please also change `emitCss` to false and `css` to true at the client section. (here you may found a complete Sapper template about it: https://dev.to/csaltos/sapper-with-material-ui-35id)

**Comment by rotimi-best** [comment]
I cloned the repo you pointed to and ran it locally. I still have the same issue. All I did was, `git clone`, `npm i` and `npm run dev`
![image](https://user-images.githubusercontent.com/31730715/93602868-e9897b00-f9cb-11ea-97e7-25499bf14c13.png)

**Comment by rotimi-best** [comment]
What I suggest as a solution is to remove the margin that is added to the input of the text field. I don't really know if this will break other things but this solves this issue

![svelte-text-input-bug-fix](https://user-images.githubusercontent.com/31730715/95442404-02020b00-0964-11eb-932b-0cd433f6a241.gif)

**Comment by ThomasDeruel** [comment]
For people who use `degit`, it generates a global css file named `global.css` (public/global.css).

You have to remove the `input` element assigned to these properties:
```css
/* remove the input element */
input, button, select, textarea { 
	font-family: inherit;
	font-size: inherit;
	-webkit-padding: 0.4em 0;
	padding: 0.4em;
	margin: 0 0 0.5em 0;
	box-sizing: border-box;
	border: 1px solid #ccc;
	border-radius: 2px;
}
```
Or else, if you don't need a global css, just delete it, and remove the meta link in `index.html `: 
```html
<!-- Should be removed -->
<link rel='stylesheet' href='/global.css'>
```

**Comment by mbacon-edocs** [comment]
> 
> 
> For people who use `degit`, it generates a global css file named `global.css` (public/global.css).
> 
>

This fixed the issue for me - just dropped most of the global.css

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
