### ISSUE TITLE
Autocomplete component

### ISSUE THREAD

**Issue by tomzij** [hperrin/svelte-material-ui#170]
Svelte doesn't have a lot of options when it comes to autocomplete (something used in a lot of UIs :) ). The closest I found was: https://github.com/rob-balfre/svelte-select but it has some issues.

Would it be possible to add: https://material-ui.com/components/autocomplete/

It looks really good!

**Comment by hperrin** [comment]
This might be a good candidate as the first package in `@smui-extra`. :D

**Comment by hperrin** [comment]
Done! It also works as a combobox!
