### ISSUE TITLE
How do i create a fixed width button?

### ISSUE THREAD

**Issue by vinkobedek** [hperrin/svelte-material-ui#175]
I'm new to svelte, and material UI also. I would like to know how do I create a fixed width button. I have a button that changes text and it would be better when the button would be of a fixed sized.
I tried to add a class to the button:
```
<Button color="primary" variant="unelevated" on:click={handler} class="button-test-class">{buttonText}</Button>    
``` 

This does not seem to work. Thoughts?

Edit: forgot to mention. the class specifies min-width and max-width for the button.

**Comment by hperrin** [comment]
Classes only work on elements defined within the component in Svelte. To add a class to a component underneath the current one, you can use Svelte's ":global()" syntax. If your button is under an element inside your component, try this:

```svelte
<style>
  * :global(.button-test-class) {
    /* your styles */
  }
</style>
```

**Comment by hperrin** [comment]
(Changing the title for future users searching for similar issues.)
