### ISSUE TITLE
How to integrate SMUI in a Sapper application with TypeScript support?

### ISSUE THREAD

**Issue by silvioprog** [hperrin/svelte-material-ui#184]
Hi.

Consider the following [official steps](https://sapper.svelte.dev/docs#Getting_started) to create a Sapper application with TypeScript support:

```bash
npx degit "sveltejs/sapper-template#rollup" my-app
# or: npx degit "sveltejs/sapper-template#webpack" my-app
cd my-app
npm install
npm run dev
^C
node scripts/setupTypeScript.js
npm install
npm run dev
```

now, those [official steps](https://github.com/hperrin/svelte-material-ui#usage) to enable SMUI in the above application:

```bash
npm install --save-dev @smui/button
npm i -D rollup-plugin-postcss node-sass
```

and applied all other [required changes](https://github.com/hperrin/svelte-material-ui#integration-for-sapper) suggested by the documentation. However, when I run the application, it emits the following warning:

```bash
• client
The emitted file "index-044d48e1.css" overwrites a previously emitted file of the same name.
```

and the button doesn't get stylized, like showed in the picture below:

![image](https://user-images.githubusercontent.com/1456829/98149634-39ed6700-1eac-11eb-8d28-5813f1aaf1d8.png)

So, what I'm doing wrong?

TIA for any help!

P.S.: the full application in attachment.

[my-app.zip](https://github.com/hperrin/svelte-material-ui/files/5489604/my-app.zip)

**Comment by daison12006013** [comment]
Maybe you missed the rollup config, have you read that you should put it both inside the `client:` and `server:`?

**Comment by nikitaignatov** [comment]
I experienced the same issue, where css from smui was not bundled correctly.

The code for the postcss plugin in the rollup.config section that is mentioned in the [README](https://github.com/hperrin/svelte-material-ui/blob/master/README.md#integration-for-sapper) has the extract option set to true.
  
There is some explanation of what this options does on the  [rollup README](https://github.com/egoist/rollup-plugin-postcss#extract-css)

Changing it to false for the client  at least loads the style. Changing the server config does not seem to have any effect.

```js
postcss({
    extract: false, // <--- setting this to false applies the style from smui and from the _smui-theme.scss
    minimize: true,
    use: [
        ['sass', {
            includePaths: [
                './src/theme',
                './node_modules'
            ]
        }]
    ]
}),
```

**Comment by DustinEwan** [comment]
That loads in the styles for the SMUI components, but it doesn't apply any of the styles in a components <style> section.

Is the idea here that we need to make corresponding .scss files for each component and forego <style>?

**Comment by skpn** [comment]
I am very new to web development but I also have the same issue after following the README from SMUI.
I tried commenting out the ts lines in my rollup config but this doesn't change anything, so it might not be related ?

**Comment by hanysek** [comment]
I had a similar issue. I used @nikitaignatov solution and it helps. Just change `extract: true` to  `extract: false` in rollup.config.js.

**Comment by bostondevin** [comment]
I don't have a rollup config - I have a snowpack.config using the @next version - any clue how to get it working?

**Comment by skpn** [comment]
I don't know how many people this will help because it requires changing templates but this repo works for me :
https://gitlab.com/eloyra/material-sapper-template

**Comment by etozhealkhipce** [comment]
@skpn solution helped me.

My `rollup.config.js`

`import path from 'path'
import resolve from '@rollup/plugin-node-resolve'
import replace from '@rollup/plugin-replace'
import commonjs from '@rollup/plugin-commonjs'
import url from '@rollup/plugin-url'
import svelte from 'rollup-plugin-svelte'
import autoPreprocess from 'svelte-preprocess'
import babel from '@rollup/plugin-babel'
import { terser } from 'rollup-plugin-terser'
import config from 'sapper/config/rollup.js'
import pkg from './package.json'
import postcss from 'rollup-plugin-postcss'

const mode = process.env.NODE_ENV
const dev = mode === 'development'
const legacy = !!process.env.SAPPER_LEGACY_BUILD

const onwarn = (warning, onwarn) =>
  (warning.code === 'MISSING_EXPORT' && /'preload'/.test(warning.message)) ||
  (warning.code === 'CIRCULAR_DEPENDENCY' &&
    /[/\\]@sapper[/\\]/.test(warning.message)) ||
  onwarn(warning)

const postcssOptions = () => ({
  extensions: ['.scss', '.sass'],
  extract: false,
  minimize: true,
  use: [
    [
      'sass',
      {
        includePaths: [
          './src/theme',
          './node_modules',
          path.resolve(__dirname, '..', 'node_modules')
        ]
      }
    ]
  ]
})

const preprocess = autoPreprocess({
  stylus: false,
  less: false,
  coffeescript: false,
  pug: false,
  typescript: {
    compilerOptions: {
      module: 'es2015'
    }
  },
  postcss: false,
  scss: {
    includePaths: ['src']
  }
})

export default {
  client: {
    input: config.client.input(),
    output: config.client.output(),
    plugins: [
      replace({
        'process.browser': true,
        'process.env.NODE_ENV': JSON.stringify(mode)
      }),
      svelte({
        compilerOptions: {
          dev,
          hydratable: true
        },
        emitCss: true,
        preprocess
      }),
      url({
        sourceDir: path.resolve(__dirname, 'src/node_modules/images'),
        publicPath: '/client/'
      }),
      resolve({
        browser: true,
        dedupe: ['svelte']
      }),
      commonjs(),
      postcss(postcssOptions()),
      legacy &&
        babel({
          extensions: ['.js', '.mjs', '.html', '.svelte'],
          babelHelpers: 'runtime',
          exclude: ['node_modules/@babel/**'],
          presets: [
            [
              '@babel/preset-env',
              {
                targets: '> 0.25%, not dead'
              }
            ]
          ],
          plugins: [
            '@babel/plugin-syntax-dynamic-import',
            [
              '@babel/plugin-transform-runtime',
              {
                useESModules: true
              }
            ]
          ]
        }),

      !dev &&
        terser({
          module: true
        })
    ],

    preserveEntrySignatures: false,
    onwarn
  },

  server: {
    input: config.server.input(),
    output: config.server.output(),
    plugins: [
      replace({
        'process.browser': false,
        'process.env.NODE_ENV': JSON.stringify(mode)
      }),
      svelte({
        compilerOptions: {
          dev,
          generate: 'ssr'
        },
        preprocess
      }),
      url({
        sourceDir: path.resolve(__dirname, 'src/node_modules/images'),
        publicPath: '/client/',
        emitFiles: false
      }),
      resolve({
        dedupe: ['svelte']
      }),
      commonjs(),
      postcss(postcssOptions())
    ],
    external: Object.keys(pkg.dependencies).concat(
      require('module').builtinModules
    ),

    preserveEntrySignatures: 'strict',
    onwarn
  },

  serviceworker: {
    input: config.serviceworker.input(),
    output: config.serviceworker.output(),
    plugins: [
      resolve(),
      replace({
        'process.browser': true,
        'process.env.NODE_ENV': JSON.stringify(mode)
      }),
      commonjs(),
      !dev && terser()
    ],

    preserveEntrySignatures: false,
    onwarn
  }
}
`

**Comment by hperrin** [comment]
Hey guys. There are new instructions for integrating with Sapper that produce better results:
https://github.com/hperrin/svelte-material-ui#integration-for-sapper

Basically all of the SMUI styles will be bundled into a file called "smui.css", then you include that in your template. This eliminates the flash of unstyled content on load.

I'm going to close this issue since these new instructions should resolve any issue with Sapper apps.
