### ISSUE TITLE
Textfield Icon and Select Icon have same default export

### ISSUE THREAD

**Issue by anito** [hperrin/svelte-material-ui#187]
Using both Textfield and Select component with ```withLeadingIcon``` (didn't try ```withTrailingIcon```) attribute and within a single component isn't currently possible, since both the [Select Icon components bare.js](https://github.com/hperrin/svelte-material-ui/blob/31fefee24c4aa50c3d396b5fe9198194a80531e5/packages/select/icon/bare.js#L3) and [Textfield Icons bare.js](https://github.com/hperrin/svelte-material-ui/blob/31fefee24c4aa50c3d396b5fe9198194a80531e5/packages/textfield/icon/bare.js#L3) currently only ```export default Icon```.
An additional **named export** ```export {Icon}``` would allow us to do an e.g.
```
import { Icon as SelectIcon } from "@smui/select/icon";
import { Icon as TextfieldIcon } from "@smui/textfield/icon";
```
and therefore using Textfield and Select side by side. Thx

**Comment by hperrin** [comment]
You can name the default export from the icon, like this:

```js
import SelectIcon from "@smui/select/icon";
import TextfieldIcon from "@smui/textfield/icon";
```
