### ISSUE TITLE
Please support SMUI as custom HTML element!

### ISSUE THREAD

**Issue by blackjyn** [hperrin/svelte-material-ui#189]
Hi, thanks for this great UI library.
Would you please support SMUI as custom HTML el?

It is very hard if not impossible to use SMUI  (and Svelte comps in general) , inline with the PHP code or Spring Java code.
The only way its working is via compile Svelte app with custom element support.

I can tweaks the source for that goal as I needed, but would you please make it official? 

Thanks! :smile:

**Comment by hperrin** [comment]
I'm sorry, but that's out of the scope of what I'd be willing to support.

**Comment by blackjyn** [comment]
I don't know why it is "out of the scope"?
Svelte custom HTML element can be achieved by just adding `<svelte:options tag="tag-name"/>` into each SMUI elements.

For instance for SMUI button, we can add `<svelte:options tag="smui-button"/>` then we can use that in HTML file like `<smui-button/>` .

This will be very useful to that SMUI can be use inside *.php file or any other server technologies. There are several case that we need to deal with  server data directly onto the component. Again thats because we can NOT, for instance writing directly inline PHP code inside the *.svelte document, 

So if SMUI is also supported  as custom HTML element , **it helps backend developers alot mainly the developers outside the NodeJS ecosystem like PHP , Java and ASP**.

So please consider to officially support it as custom HTML elements. Thank you
