### ISSUE TITLE
Cannot use import statement outside a module for @smui/Dialog

### ISSUE THREAD

**Issue by edqx** [hperrin/svelte-material-ui#190]
When I try to import @smui/Dialog it just tells me that I can't use an import statement outside a module. It works for @smui/Button perfectly, just not @smui/Dialog.

```
\node_modules\@smui\dialog\index.js:1
import './_index.scss';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (\__sapper__\dev\server\server.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

I'm using Typescript with Sapper on Rollup.
Node version 15.3.0

**Comment by andreyan-andreev** [comment]
I do have same issue, using svelte@next no rollup file.

**Comment by el-davo** [comment]
Same issue here @smui/top-app-bar component

**Comment by el-davo** [comment]
Figured out my issue if it helps. I was getting the same error as you when using jest. The reason being I had a .babelrc file on the root of my app, aparently jest does not read this file so I moved it to a file called babel.config.js with the following contents

```
module.exports = {
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": {
                    "node": "current"
                }
            }
        ]
    ]
};
```

now it works

**Comment by jsessink** [comment]
I ran into this issue as well, but with @smui/button.  I noticed that I had accidentally installed that one in the normal dependencies (didn't add -D), so after uninstalling and re-installing with `npm i -D @smui/button`, it ended up working.

Leaving that here in case it helps someone else.

**Comment by arshabh-inspectlogs** [comment]
I am facing the same issue using svelte@next. Any idea how this can be fixed ?

**Comment by Exomnius** [comment]
I got the samen issue using svelte@next (sveltekit)

**Comment by rafalou38** [comment]
Same issue with sveltekit

**Comment by hperrin** [comment]
@rafalou38, have any of the methods above worked to solve the issue?

**Comment by hperrin** [comment]
There are new instructions for SvelteKit, which should resolve all your issues. Just be sure to install SMUI packages as dependencies instead of dev dependencies.

https://sveltematerialui.com/SVELTEKIT.md/

**Comment by ranjanified** [comment]
> There are new instructions for SvelteKit, which should resolve all your issues. Just be sure to install SMUI packages as dependencies instead of dev dependencies.
> 
> https://sveltematerialui.com/SVELTEKIT.md/

That link is a 404... Also, this suggestion didn't help me... I too am using `SvelteKit`.
