### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by j209** [hperrin/svelte-material-ui#193]
Hi
any plan for rtl support?(Arabic,hebr,persian cultures)

**Comment by hperrin** [comment]
Hi @j209, SMUI does support RTL through MDC-Web's RTL support. If there is a specific issue with SMUI's implementation of RTL support, you can raise an issue for it.

[Here's an example REPL showing RTL support.](https://svelte.dev/repl/c2ff2d5dd5404eccb901ba04ef0161be?version=3.37.0)
