### ISSUE TITLE
Component request: Steppers

### ISSUE THREAD

**Issue by marekdedic** [hperrin/svelte-material-ui#194]
Hi,
Is there any way to implement steppers with smui now? I am migrating a project from vue (learning svelte along the way) and am missing https://vuematerial.io/components/steppers

Thanks.

**Comment by chrisrrowland** [comment]
Also curious about this.

**Comment by hperrin** [comment]
This looks similar to tabs, so if you can coerce tabs into doing what you want, I think that should work. I don't have plans to implement these myself, but if MDC-Web implements them, I will support them.

**Comment by danieleades** [comment]
this is a blocker for adoption for me, unfortunately
