### ISSUE TITLE
Help with svelte@next

### ISSUE THREAD

**Issue by andreyan-andreev** [hperrin/svelte-material-ui#195]
I know its not official release yet, but most of it seems to work. I am having struggles adding this component library.

Here is how i setup the new project.

```bash
cd svelte-app
npm init svelte@next # Selected Yes for typescript and SCSS for styling
npm install
npm install --save-dev svelte-material-ui
npm run dev
```
I have tried to apply the steps from the `Usage` section, trying to adjust them for svelte@next, 
for example: 
`snowpack.config.js`
```javascript
installOptions: {
  rollup: {
	  plugins: [
		  require("rollup-plugin-postcss")({
			  use: [
				  [
					  "sass",
					  {
						  includePaths: ["./src/theme", "./node_modules"],
					  },
				  ],
			  ]
		  })
	  ]
  }
}
```

Tried many different things to no avail, dont want to list all here to avoid confusion. Anyway the bottom line is that I always end up here:

```
500
<Button> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

Error: <Button> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at Object.validate_component (/web_modules/svelte/internal.js:1344:15)
    at eval (/_components/Counter.js:23:22)
    at Object.$$render (/web_modules/svelte/internal.js:1367:22)
    at eval (/_app/routes/index.js:19:61)
    at Object.$$render (/web_modules/svelte/internal.js:1367:22)
    at Object.default (/_app/assets/generated/root.js:38:103)
    at eval (/_app/assets/components/layout.js:7:41)
    at Object.$$render (/web_modules/svelte/internal.js:1367:22)
    at eval (/_app/assets/generated/root.js:35:50)
    at $$render (/web_modules/svelte/internal.js:1367:22)
```

This is how I am trying to import the button component
```typescript
<script lang="ts">
	import Button, { Label } from '@smui/button';
</script>

<Button>
	<Label>A Button</Label>
</Button>
```

I will be very thankful if somebody has the key to this and it is willing to share it.

**Comment by unlocomqx** [comment]
This could help
https://stackoverflow.com/questions/61970250/getting-svelte-material-ui-working-with-snowpack-and-sass

**Comment by hperrin** [comment]
SvelteKit migrated to Vite, and I haven't gotten the Sass compilation working well on Vite, so there is a workaround for now, where you compile all the Sass outside of Vite, then import from the "/bare" endpoints:

https://github.com/hperrin/svelte-material-ui/blob/master/SVELTEKIT.md
