### ISSUE TITLE
Slider: Missing on:input and on:change events.

### ISSUE THREAD

**Issue by piranha771** [hperrin/svelte-material-ui#197]
**Example:**

`<Slider on:input={() => console.log('Hello World')} />`

or 

`<Slider on:change={() => console.log('Hello World')} />`

**Expected behavior:**

The event methods are called. Message "Hello World" is logged to console.

The events on:input, on:change forward their handler to on:MDCSlider:input, on:MDCSlider:change

**Observed behavior:**

The event methods are not called. Message "Hello World" is not logged to console.

**Comment by hperrin** [comment]
This is fixed in the latest version.

**Comment by demoran23** [comment]
@hperrin I'm encountering this issue in both 6.0.0-beta.13 and 6.0.0-beta.14.  Is this possibly a regression?  It's not the only control that acts like this.  I'm using svelte 3.39.0 (I downgraded to fix a wierd `$$ on undefined` issue).

**Comment by hperrin** [comment]
The Slider doesn't use a native input, so it doesn't fire native input events that can be forwarded. Use the SMUIInput event.

**Comment by hperrin** [comment]
Can you use the `SMUISlider:input` or `SMUISlider:change` event?

**Comment by demoran23** [comment]
@hperrin Ah yes, that did the trick!  I can use those events.  Maybe I won't have to debounce after all.
