### ISSUE TITLE
postcss plugin error when using data-table

### ISSUE THREAD

**Issue by malgor** [hperrin/svelte-material-ui#199]
When I attempt to compile the basic table from Readme.md I get this error:

[!] (plugin postcss) Error: Mixin mdc-typography has no parameter named $exclude-props
node_modules\@smui\textfield\_index.scss
Error: Mixin mdc-typography has no parameter named $exclude-props
    at options.error (C:\Users\Mal\Documents\software\

node_modules\node-sass\lib\index.js:290:33)

I feel this must be some simple oversight but I can't see what it is.  I have attached my package.json in case there is an obvious dependency missing.

Thanks for any help

[package.json.txt](https://github.com/hperrin/svelte-material-ui/files/5841859/package.json.txt)

**Comment by malgor** [comment]
After reducing the problem to minimum levels of code I found package-lock.json had become corrupt.

**Comment by sswam** [comment]
I had the same error when using TextField.

I partly solved this by running npm install @material/typography@4.0.0. svelte-material-ui only depended on ^3.1.0.

Now I am getting a new error:

```
node_modules/@smui/textfield/Textfield.svelte
A11y: A form label must be associated with a control.
1: {#if valued}
2:   <label
     ^
3:     bind:this={element}
4:     use:useActions={use}
```

See also here: https://github.com/sveltejs/svelte/issues/5300

It seems that the <label> component must refer to the main Input or Textarea component by ID. But we don't necessarily have an ID. Also, I have only included the file, have not added a Textfield to my page yet. So I'm not sure how to resolve this. Can you please advise?  I'd be happy to make a donation to the project if that can help.  Thanks.
