### ISSUE TITLE
can't seem to get the demo working

### ISSUE THREAD

**Issue by robertsozolins** [hperrin/svelte-material-ui#2]
```
<Button>Just a Button</Button>
<Button raised><ButtonLabel>Raised Button, Using a Label</ButtonLabel></Button>
<Button some-arbitrary-prop="placed on the actual button">Button</Button>

<Fab on:click="{() => alert('Clicked!')}" extended>
  <FabIcon style="margin-right: 12px;">favorite</FabIcon>
  <FabLabel>Extended FAB</FabLabel>
</Fab>

<script>
  import Button, {Label as ButtonLabel} from 'svelte-material-ui/components/button';
  import Fab, {Label as FabLabel, Icon as FabIcon} from 'svelte-material-ui/components/fab';
</script>
```

![image](https://user-images.githubusercontent.com/47858537/61724717-2e3d6600-ad77-11e9-8765-7857accf9d76.png)

**Comment by hperrin** [comment]
I'm not sure how your bundler is set up, but it looks like a problem with that.

**Comment by robertsozolins** [comment]
i'm using the default configuration from sapper.

**Comment by hperrin** [comment]
Hmm. Is it set up to look for certain file extensions? Right now, I'm not using file extensions in my imports.

**Comment by hperrin** [comment]
(So, with my current webpack config, it will look inside the "fab" folder for index.svelte.)

**Comment by hperrin** [comment]
This should be resolved in the latest version.
