### ISSUE TITLE
Circular progress indicators aren't supported

### ISSUE THREAD

**Issue by SlickNicky10** [hperrin/svelte-material-ui#205]
Hey, loving this module and it seems to support most components from Material UI perfectly. However, I did notice a strange omission (likely a silly mistake). While this module does support material's linear progress indicators, it does not support the circular ones ("loading spinners"). Vuetify and the React implementations of Material UI seem to support them just fine though. For the meantime I have been using [svelte-loading-spinners](https://github.com/Schum123/svelte-loading-spinners) as a supplement, but it would be nice to support the official material ones too :)

**Comment by hperrin** [comment]
Hey @SlickNicky10. These are supported now! Check it out: https://sveltematerialui.com/demo/circular-progress/
