### ISSUE TITLE
Svelte Select like Component

### ISSUE THREAD

**Issue by bwbroersma** [hperrin/svelte-material-ui#21]
Would be great to have a (Multi) Select that has filtering, virtual-list, etc. like (the great) [svelte-select](https://github.com/rob-balfre/svelte-select).

**Comment by hperrin** [comment]
I'm not sure actually, whether this component would fit into Material Design. What features do you want from this component that aren't present in the select component?

**Comment by caschbre** [comment]
I use svelte-select mixed in with svelte-material-ui... mainly for the auto-complete and ability to pull the options from an API.

**Comment by oculardexterity** [comment]
> I use svelte-select mixed in with svelte-material-ui... mainly for the auto-complete and ability to pull the options from an API.

Can you give me an example of this?

**Comment by bwbroersma** [comment]
Mainly I would want the 'combo' feature of typing in the Select to filter the options (kind of auto-complete?), and virtual-list support to handle a lot of options.

**Comment by caschbre** [comment]
> > I use svelte-select mixed in with svelte-material-ui... mainly for the auto-complete and ability to pull the options from an API.
> 
> Can you give me an example of this?

I just mean that I use svelte-select in my project alongside svelte-material-ui. There isn't a specific integration between the two.  So if I want auto-complete or data pulled from an API then I use svelte-select, otherwise I use the Select component from smui.

**Comment by caschbre** [comment]
@hperrin I see you have this tagged help wanted.... are you thinking the existing Select component would be modified to accommodate the additional functionality or would a completely new component be ideal?  I may have some time to take a crack at it.

**Comment by atilkan** [comment]
I think virtual list would not be essential for this.

**Comment by mwamp** [comment]
I am not sure what you guys want exactly but it looks to me that we might actually want to tweak svelte-select so it accepts smui/Select&Option as slots no?
This would make sense as the features you mention are about logic when smui is more about view?
This way we could define a Select interface which could be shared between svelte ui libraries?

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
