### ISSUE TITLE
Slider touch highlight should be disabled

### ISSUE THREAD

**Issue by Immortalin** [hperrin/svelte-material-ui#219]
On touch devices, there is a default momentary input highlight around the component when the slider is used.

**Comment by hperrin** [comment]
Can you tell me which device and browser you're using?

**Comment by Immortalin** [comment]
Chrome android

**Comment by Immortalin** [comment]
Unrelated but the card page overflows on mobile:

![Screenshot_20210415-170956](https://user-images.githubusercontent.com/7126128/114938740-7afb8700-9e0d-11eb-835a-bf74b3e3d631.jpg)

**Comment by hperrin** [comment]
Ah, ok. Gotta go grab my Android phone! I'll fix the cards demo too.

**Comment by hperrin** [comment]
I've figured out that this happens to any element in Chrome that has the "cursor: pointer;" style.

**Comment by hperrin** [comment]
And there is a solution! https://stackoverflow.com/a/25704651
