### ISSUE TITLE
How to use beta with MDC 10 components

### ISSUE THREAD

**Issue by amit777** [hperrin/svelte-material-ui#221]
** Is this for an existing documentation file? **
https://github.com/hperrin/svelte-material-ui/blob/master/INSTALL.md

** What needs improvement? **
Steps on how to use the MDC10 components that you mentioned is in beta.  Thank you!

**Comment by hperrin** [comment]
Hi @amit777. As of this morning, 3.0 is no longer in beta. :D You should be able to install them with the "@latest" tag, or just no tag at all.

If you are upgrading existing imports from SMUI 1 or 2, check out [NPM Check Updates](https://preview.npmjs.com/package/npm-check-updates).

```
npx npm-check-updates -c
```

(Keep in mind, this may update other libraries.)

Then you can follow the [migration docs](https://sveltematerialui.com/MIGRATING.md/) to update your code.
