### ISSUE TITLE
Unable to change LayoutGrid grid-gap

### ISSUE THREAD

**Issue by masyukun** [hperrin/svelte-material-ui#224]
**Describe the bug**
Unable to change the LayoutGrid's grid-gap. No parameter appears to exist to support a different value. Passing style prop in with "grid-gap: 5px;" does nothing. 

**Additional context**
Also, Vertical and horizontal gaps are tied together under .mdc-layout-grid__inner, and similar classes. It would be great to separate these for finer-grained style control.

**Comment by hperrin** [comment]
You would need to use MDC-Web's layout grid Sass mixin to do this:
https://github.com/material-components/material-components-web/tree/v11.0.0/packages/mdc-layout-grid#sass-mixins
