### ISSUE TITLE
The single toggle button does not clear its background

### ISSUE THREAD

**Issue by kvetoslavnovak** [hperrin/svelte-material-ui#225]
**Describe the bug**
The single toggle button does not seem to work correctly because it does not clear its background if switched/clicked off. 

**To Reproduce**
See an example in the Documentation -Segmented Button - Group Selection OR Icons and Keyed Segments
https://sveltematerialui.com/demo/segmented-button/
The buttons in Group selection example or in the formatting example do not clear their background if switched off. The single toggle button does not seem to work correctly.  Only group toggle buttons clear their background automatically. 

**Expected behavior**
The single toggle button clears its background when switched/clicked off. 

**Screenshots**
  ![Screenshot from 2021-04-21 21-32-50](https://user-images.githubusercontent.com/5719547/115610927-c8826300-a2e9-11eb-9605-4334a28e9ccc.jpg)
The Bold button should be switched off (having  white background) as the Underline button is.

**Desktop (please complete the following information):**
 - OS: iOS, Pop!_OS, Windows
 - Browser Chrome, Chromium

**Comment by hperrin** [comment]
I think what you're seeing is just confusing styles from MDC. The button is off (so no background), but it's also focused (so added background). The only difference in that case is that the icon is not colored.

**Comment by kvetoslavnovak** [comment]
Actually that is the point.  The button is out of focus but styled as being in focus when switched off.

**Comment by hperrin** [comment]
Can you try it now? I've updated to the latest upstream MDC version.

**Comment by kvetoslavnovak** [comment]
Seems the update has broken overall functionality unfortunately. 
Now only one button on the whole page https://sveltematerialui.com/demo/segmented-button/ can be switched on. 
Also the text/icon is not highlighted any more when the button is switched on.
![Screenshot from 2021-04-23 10-50-11](https://user-images.githubusercontent.com/5719547/115846255-fff42b00-a421-11eb-9697-e30e25b80256.jpg)

**Comment by hperrin** [comment]
I think you might need to do a hard refresh, cause they are working for me.

**Comment by hperrin** [comment]
If you'd like, you can file a bug for this here:
https://github.com/material-components/material-components-web/issues
