### ISSUE TITLE
Vertical alignment in Text Field is off on iOS

### ISSUE THREAD

**Issue by jesperhoy** [hperrin/svelte-material-ui#226]
**Describe the bug**
Vertical alignment in Text Field is off on iOS

**To Reproduce**
Open https://sveltematerialui.com/demo/textfield/ on iPad and enter text...

**Expected behavior**
Input text to be below label - not overlapping

**Screenshots**
![909C0CFD-A736-4735-BBC2-D6BB96C75CA8](https://user-images.githubusercontent.com/12099212/115723139-f4502800-a37f-11eb-9034-dde294337dc3.jpeg)

**Desktop (please complete the following information):**
 - OS: iOS 14.4.2
 - Browser: Safari + Chrome
 - Version: latest

**Smartphone (please complete the following information):**
 Nope

**Additional context**
None

**Comment by hperrin** [comment]
Thank you for the screenshot. I've verified this on the iPhone too.

**Comment by hperrin** [comment]
Looks like this is also an issue on desktop Safari.

**Comment by jesperhoy** [comment]
Thank you for fixing. Looks good now:-)
