### ISSUE TITLE
TextField type "date" shows buggy behaviour when input$max is given

### ISSUE THREAD

**Issue by heyDante** [hperrin/svelte-material-ui#228]
**Describe the bug**
`<TextField type="date" />` shows buggy behaviour with `input$max` attribute, when taking input via keyboard.
`input$max="9999-12-31"` is provided to restrict the year to 4 digits only.

**To Reproduce**

***Behaviour 1***
1. Open the [repl](https://svelte.dev/repl/89911f5ca4d144c0aa8dcd538b6ece51?version=3.37.0)
2. Enter date on the input with keyboard
3. See the year field, it takes max only 2 digits.

***Behaviour 2***
1. Open the [repl](https://svelte.dev/repl/89911f5ca4d144c0aa8dcd538b6ece51?version=3.37.0)
1. Provide date with the datepicker.
2. Change the provided date with keyboard. It doesn't proceed further after day.

**Expected behavior**
1. Expected to take MM-DD-YYYY input with `input$max="9999-12-31"`  attribute.
2. Here's a [JSFiddle](https://jsfiddle.net/e6xc5ujd/1/) showing normal behaviour with native input type date and max attribute.
`<input type="date" max="9999-12-31">`

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: Chrome
 - Version: 90.0.4430.85

**Comment by hperrin** [comment]
I believe type="date" is deprecated. Try type="datetime-local" and see if the max value works then.
