### ISSUE TITLE
Remove height: 56px from all .mdc-select__anchor classes so height can be set with style props of <Select> 

### ISSUE THREAD

**Issue by masyukun** [hperrin/svelte-material-ui#229]
Your <Select> component uses height: 56px for all .mdc-select__anchor classes in bare.css, as a result setting height in <Select> style prop gets overwritten. This behavior is not consistent with other components, such as Textfield for example. If you remove this we can set the height with <Select> style prop.

**Comment by hperrin** [comment]
This is something that the upstream Sass sets, so it should be either handled by them, or you can use the `!important` flag for a quick fix.
