### ISSUE TITLE
Switch appears as a tickbox

### ISSUE THREAD

**Issue by josesan9** [hperrin/svelte-material-ui#232]
Hi,
I have the following code, essentially the same as the one shown in the demo:
```
<script lang="ts">
  import Switch from "@smui/switch";
  import FormField from "@smui/form-field";
</script>

<div>
  <FormField>
    <Switch />
    <span slot="label">myLabel</span>
  </FormField>
</div>
```

but when I look at it in the UI, I see the following:
![image](https://user-images.githubusercontent.com/25055859/116256588-3bb52a80-a76b-11eb-935d-1fa093d0abc6.png)

am I doing something wrong which is causing the switch to look like a tickbox? this is effectively the same as what you have in the Demo code, which causes further confusion.
Thanks

**Comment by wesleyegbertsen** [comment]
Are you using Sapper and if so are you using the Advanced Styling Method? If so make sure you add the '/styled' directive then to the imports, so like this:

```
import Switch from "@smui/switch/styled";
import FormField from "@smui/form-field/styled";
```

**Comment by josesan9** [comment]
yes, we are using all as stated. I tried adding the "/styled" postfix, but the import fails:
![image](https://user-images.githubusercontent.com/25055859/116268570-5a202380-a775-11eb-9187-93d59b66949a.png)
I tried running it anyways, and svelte errored saying that `Switch is not defined`.
could I be missing an npm import? I'm importing all of the `@smui/*` components that I need, but as far as I'm aware, no additional imports are necessary. Is this correct?

**Comment by wesleyegbertsen** [comment]
Hmm that's weird, when I upgraded from SMUI V3 to V4 in my project that worked for me, as stated here at Breaking Changes for V3 -> V4: https://github.com/hperrin/svelte-material-ui/blob/master/MIGRATING.md#smui-3---smui-4

**Comment by hperrin** [comment]
Can you try `/styled.js`?

**Comment by hperrin** [comment]
I'm gonna close this now, assuming that worked. Feel free to reopen if you're still having trouble. Or you can join the Discord.
