### ISSUE TITLE
when first created switch's ripple takes 100% width

### ISSUE THREAD

**Issue by rafalou38** [hperrin/svelte-material-ui#235]
# when first created switch's ripple takes 100% width

## Describe the bug
When you create a switch before doing any action its ripple will be 100% width

it will become normal if you:
- click it
- resize the window
- scroll

## To Reproduce

1. create a switch
2.  load the page/refresh

## example code:
```svelte
<Switch/>

<script>
	import Switch from '@smui/switch';
</script>
```

## Screenshots
![switch](https://user-images.githubusercontent.com/58974586/116377798-d7997180-a811-11eb-8ab7-e229e70f6bde.gif)

## Desktop:
 - OS: Windows
 - Browser: Firefox
 - Version: 90.0a1

[**repl**](https://svelte.dev/repl/7b852bc775154aafa9fb2ac7fcda20e4?version=3.37.0)

**Comment by hperrin** [comment]
I haven't been able to reproduce this outside of the REPL. Are you able to reproduce this locally?

**Comment by rafalou38** [comment]
I just noticed it while testing in the repl but if it only happens in the repl and not in a true install it is not really important 🤷🏻‍♂️
