### ISSUE TITLE
Properly override SASS class ?

### ISSUE THREAD

**Issue by Grandnainconnu** [hperrin/svelte-material-ui#238]
Hello,

I am struggling a little with theming on SASS, I would like for example to override `.mdc-form-field`, so I have this :
```
@use 'sass:color';

@use '@material/theme/color-palette';

@use '@material/theme/index' as theme with (
  $primary: rgb(86, 100, 210),
  $secondary: #676778,
  $surface: #fff,
  $background: #fff,
  $error: color-palette.$red-900,
);

.mdc-form-field {
    display: inline-flex;
    flex-direction: column;
    align-items: start;
    position: relative;

    min-width: 0;
    width: 100%;

    padding: 0;
    margin: 16px 0 8px;

    border: 0;

    vertical-align: top;

    .field--error {
        color: rgb(244, 67, 54);
        font-size: 1rem;
        text-align: left;

        margin: 3px 14px 0;
    }
}
```

Problem, when the SASS is compiled, the original class is appended after my override, and so my changes are canceled.

I would like to know if there is anything to avoid this except adding a class like `.my-website` at the root of my project and make my SASS class like `.my-website .mdc-form-field` ?

Thanks in advance !

**Comment by pkid169** [comment]
Did you figure this out? I'm trying this out and have been struggling with overriding even simple attributes for button.

**Comment by Grandnainconnu** [comment]
> Did you figure this out? I've been struggling with overriding even simple attributes for button. Couldn't get anything to work without resorting to workaround as you mentioned :(

I decided to use another theme finally, too much struggle with this one, sorry :|

**Comment by hperrin** [comment]
If you make your CSS selector more specific, it will override the default. This could be done with adding the element as well, like `div.mdc-form-field`.
