### ISSUE TITLE
Workeround @use error WebStorm ?

### ISSUE THREAD

**Issue by Grandnainconnu** [hperrin/svelte-material-ui#239]
Hello,

Is there a way to prevent this from happening in WebStorm while importing SASS files ?
![image](https://user-images.githubusercontent.com/4025637/116854448-591d4500-ac00-11eb-9175-4e0654935cbc.png)

If I put `~` before `@material` it works but then the CSS compilation fails

I tried creating a symlink of `@material` directly in the theme folder without success.

Thanks in advance

**Comment by robsch** [comment]
Same here. Is it possible that `@material/theme/index` does not exist? I would expect in node_modules, but I don't have that file. Wondering if it needs to be installed somehow.

**Comment by robsch** [comment]
Now I have installed it with `npm i @material/theme`.

**Comment by robsch** [comment]
With the prefix of `~` (and the installation of `@material/theme`) it works for me now.

**Comment by robsch** [comment]
One thing that seems to work is to specify the node_modules directory directly:

`@use 'node_modules/@material/theme/color-palette'`

**Comment by hperrin** [comment]
This is absolutely a problem with the IDE and not the library.

**Comment by hperrin** [comment]
You should file a bug with the WebStorm project.
