### ISSUE TITLE
TopAppBar does not work in Svelte-Kit

### ISSUE THREAD

**Issue by FunMiles** [hperrin/svelte-material-ui#251]
I took the simple standard SvelteKit demo app and added a SMUI Button without trouble.
However, once I inserted a TopAppBar, I got the following error:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/michel/Clone/node_modules/@smui/top-app-bar/index.js
require() of ES modules is not supported.
require() of /Users/michel/Clone/node_modules/@smui/top-app-bar/index.js from /Users/michel/Clone/node_modules/vite/dist/node/chunks/dep-e9a16784.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/michel/Clone/node_modules/@smui/top-app-bar/package.json.
```
I am not sure if just following the instruction is all it takes to solve the issue. I will try it when I have more time, but it would be nice to have all the widgets working.

**Comment by ArleyRistar** [comment]
I had this same problem, found the solution here: #237 
Moving the SMUI packages from devDependencies to dependencies worked for me.

**Comment by FunMiles** [comment]
Thanks @ArleyRistar, it does the trick for me as well.
