### ISSUE TITLE
FloatingLabel overlaps Select value

### ISSUE THREAD

**Issue by tsndr** [hperrin/svelte-material-ui#252]
**Describe the bug**
FloatingLabel overlaps the value of a select on blur when values are numbers instead of strings.

**To Reproduce**
Here is a little example component to reproduce the bug.
```svelte
<script>
import Select, { Option } from '@smui/select'

let options = [
    { id: 1, name: 'Option 1'},
    { id: 2, name: 'Option 2'}
]
</script>

<Select label="Options">
    {#each options as option}
        <Option value={option.id}>{option.name}</Option>
    {/each}
</Select>
```

**Expected behavior**
That the label stays up and doesn't slide down since an option has been selected.

**Screenshots**
<img width="218" alt="Screen Shot 2021-05-23 at 02 01 26" src="https://user-images.githubusercontent.com/2940127/119243846-cb7fa600-bb6a-11eb-92de-423a378ef342.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 90

**Comment by tsndr** [comment]
I did some further testing and it looks like the async part isn't the issue. It seems to have something to do with the values being numbers instead of strings.

**Comment by loganwyas** [comment]
I have also noticed this issue. It would be nice if this bug gets fixed, rather than having to do the workaround of using strings as values.

**Comment by rururux** [comment]
use `key` attribute like [this demo](https://github.com/hperrin/svelte-material-ui/blob/3a84a0245fa96284ebe08272dbb59fc51175d778/packages/site/src/routes/demo/select/_Objects.svelte#L43).

```svelte
<Select key={(num) => String(num)} label="Options">
    {#each options as option}
        <Option value={option.id}>{option.name}</Option>
    {/each}
</Select>
```
