### ISSUE TITLE
[vite] Internal server error: ENOENT: no such file or directory, open 'E:\projects\mine\wisper-web\node_modules\@material\textfield\icon\index.ts

### ISSUE THREAD

**Issue by qianwj** [hperrin/svelte-material-ui#253]
**Describe the bug**
I want to try use `@smui/textfield` in my app which is in [http://sveltematerialui.com/demo/textfield/](http://sveltematerialui.com/demo/textfield/), but when I typed `yarn dev`, console report `[vite] Internal server error: ENOENT: no such file or directory, open 'E:\projects\mine\wisper-web\node_modules\@material\textfield\icon\index.ts'`

**To Reproduce**
1. create app:  `yarn create @vitejs/app wisper-web --template svelte`
2. `cd wisper-web && yarn`
3. add smui: `yarn add @smui/textfield -D`
4. add Test.svelte into `lib`
5. run app: `yarn dev`
```svelte
// Test.svelte
<script>
    import Textfield from "@smui/textfield";
    import Icon from "@smui/textfield/icon";
    import HelperText from "@smui/textfield/helper-text/index";
    let valueB = "";
</script>

<div>
    <Textfield
        class="shaped-outlined"
        variant="outlined"
        bind:value={valueB}
        label="Leading Icon"
    >
        <Icon class="material-icons" slot="leadingIcon">event</Icon>
        <HelperText slot="helper">Helper Text</HelperText>
    </Textfield>

    <pre class="status">Value: {valueB}</pre>
</div>
```
```svelte
// App.svelte
<script>
  import logo from './assets/svelte.png'
  import Counter from './lib/Counter.svelte'
  import Test from './lib/Test.svelte'
</script>

<main>
  <img src={logo} alt="Svelte Logo" />
  <h1>Hello world!</h1>

  <Counter />

  <Login />

  <p>
    Visit <a href="https://svelte.dev">svelte.dev</a> to learn how to build Svelte
    apps.
  </p>

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme">SvelteKit</a> for
    the officially supported framework, also powered by Vite!
  </p>
</main>

<style>
  :root {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
      Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  }

  main {
    text-align: center;
    padding: 1em;
    margin: 0 auto;
  }

  img {
    height: 16rem;
    width: 16rem;
  }

  h1 {
    color: #ff3e00;
    text-transform: uppercase;
    font-size: 4rem;
    font-weight: 100;
    line-height: 1.1;
    margin: 2rem auto;
    max-width: 14rem;
  }

  p {
    max-width: 14rem;
    margin: 1rem auto;
    line-height: 1.35;
  }

  @media (min-width: 480px) {
    h1 {
      max-width: none;
    }

    p {
      max-width: none;
    }
  }
</style>
```

**Expected behavior**
yarn add was succeed, so It should be running normally....

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Microsoft Edge

**Comment by hperrin** [comment]
Vite requires a workaround, since it has a "feature" where a file that doesn't exist referenced in a source map breaks the build. You can see the workaround in the SvelteKit instructions:

https://github.com/hperrin/svelte-material-ui/blob/master/SVELTEKIT.md

**Comment by hperrin** [comment]
Since it looks like you're on Windows, there is a Node script in the SvelteKit SMUI example repo that will work for you.

**Comment by qianwj** [comment]
Oh, It worked!!!!! Thanks :kissing_heart:
