### ISSUE TITLE
Error when changing Textfield value from a string to null

### ISSUE THREAD

**Issue by tuckergordon** [hperrin/svelte-material-ui#259]
**Describe the bug**
If the value of a Textfield element changes from a string to `null`, it results in an error:
> Cannot read property 'length' of null

**To Reproduce**
Here is a REPL demonstrating the bug: https://svelte.dev/repl/aa857c3bb5eb478cbe6b1fd6c6da522a?version=3.37.0
1. Create a Textfield and set it's value to a string
2. Change value to `null` to produce error in console

**Expected behavior**
`Textfield`'s `value` should be able to switch between a string and `null` without throwing an error, as `null` is a valid setting for `value`

**Comment by skaryys** [comment]
Hello, I really hope this will be fixed. If you have code, where you cant get rid of the `null` value, it can be fixed like below:

`
<Textfield class="fullwidth" variant="outlined" value={''}>
  <input
     class="mdc-text-field__input"
     type="text"
     bind:value={filterSelections[col.key]} //here put your variable instead of this
  />
</Textfield>
`

and in script part do something like this:

`
onMount(() => {
		document.querySelectorAll('.mdc-text-field input:last-child').forEach((input) => {
			input.parentNode.removeChild(input);
		});
});
`

I know its terrible solution but it works for my case. But I really hope that Textfield component will be fixed.

**Comment by risalfajar** [comment]
I experienced this too, my current workaround is prevent the value to be null, you can use Typescript null coalescing (`??`) for that

**Comment by hperrin** [comment]
This is fixed now in v5. Basically, if the value is null on initialization, it will be set back to null if the box is made empty. Same with undefined. You can also use `input$emptyValueNull` and `input$emptyValueUndefined` to get the same behavior.
