### ISSUE TITLE
Please clarify the location of the _smui-theme.scss

### ISSUE THREAD

**Issue by MintyMods** [hperrin/svelte-material-ui#26]
Hi,

After spending all morning and failing to get this working with my original rollup.config I gave in and decided to try using webpack but have also royally failed with that. The error I am hitting is mostly:-

```
✗ server
node_modules/@smui/fab/_index.scss 1:0
Module parse failed: Unexpected character '@'
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import "smui-theme.scss";
| @import "./_style.scss";
```

I created the _smui-theme.scss file within a directory called theme within my site and I think this is being found as creating another file without the underscore prefix causing a different error:-

```
@import "smui-theme";
^
      It's not clear which file to import for '@import "smui-theme"'.
Candidates:
  _smui-theme.scss
  smui-theme.scss
Please delete or rename all but one of these files.
```

I have tried to follow the instructions and provide what I think is a scss processor within the webpack.config

```
const alias = { svelte: path.resolve('node_modules', 'svelte') };
const extensions = ['.mjs', '.js', '.json', '.svelte', '.html', '.scss'];
const mainFields = ['svelte', 'module', 'browser', 'main'];

const sassOptions = {
		  includePaths: [
		    './src/main/sapper/theme/',
		    './node_modules/',	    
		    path.resolve(__dirname, 'src/main/sapper/theme/')
		  ]
		};

module.exports = {
	client: {
		entry: config.client.entry(),
		output: config.client.output(),
		resolve: { alias, extensions, mainFields },

		devtool: dev && 'inline-source-map',
		module: {
		    rules: [
		      {
				test: /\.(svelte|html)$/,
				use: {
					loader: 'svelte-loader',
					options: {
						emitCss: true,
						hotReload: true
					}
				}
		      },
		      {
		        test: /\.(sa|sc|c)ss$/,
		        use: [
		          isDevelopment ? 'style-loader' : MiniCssExtractPlugin.loader,
		          'css-loader',
		          {
		            loader: 'sass-loader',
		            options: {
		              ...sassOptions
		            },
		          },
		        ],
		      },
		      {
		        test: /\.js$/,
		        exclude: /node_modules/,
		        use: {
		          loader: 'babel-loader',
		          options: {
		            presets: ['@babel/preset-env'],
		          },
		        },
		      },
		    ],
		  },
			mode,
			plugins: [
				// pending https://github.com/sveltejs/svelte/issues/2377
				// dev && new webpack.HotModuleReplacementPlugin(),
				new webpack.DefinePlugin({
					'process.browser': true,
					'process.env.NODE_ENV': JSON.stringify(mode)
				}),
			    new MiniCssExtractPlugin({
			    	filename: isDevelopment ? '[name].css' : '[name].[hash].css',
			    	chunkFilename: isDevelopment ? '[id].css' : '[id].[hash].css'
			    }),
			      new OptimizeCssAssetsPlugin({
			        assetNameRegExp: /\.css$/g,
			        cssProcessor: require('cssnano'),
			        cssProcessorPluginOptions: {
			          preset: ['default', { discardComments: { removeAll: true } }],
			        },
			        canPrint: true
			      })
			].filter(Boolean),		  
	},

	server: {
		entry: config.server.entry(),
		output: config.server.output(),
		target: 'node',
		resolve: { alias, extensions, mainFields },
		externals: Object.keys(pkg.dependencies).concat('encoding'),
		module: {
			rules: [
				{
					test: /\.(svelte|html)$/,
					use: {
						loader: 'svelte-loader',
						options: {
							css: false,
							generate: 'ssr',
							dev
						}
					}
				}
			]
		},
		mode: process.env.NODE_ENV,
		performance: {
			hints: false // it doesn't matter if server.js is large
		}
	},

	serviceworker: {
		entry: config.serviceworker.entry(),
		output: config.serviceworker.output(),
		mode: process.env.NODE_ENV
	}
};
```

but this doesn't seem to be processing the scss files and resolving the imports.

> "You must also have a _smui-theme.scss file in one of the Sass include paths"

Could you please expand on that instruction in terms of what a 'Sass include path' is? Do you mean on the file system or imported into a page?

Any help or advice on how I can proceed to debug this issue further is much appreciated as I really want to use svelte-material-ui but have already wasted a day just trying to install it.

**Comment by safaiyeh** [comment]
I had this issues as well today. Here is my webpack config:

```

const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const path = require('path');

const mode = process.env.NODE_ENV || 'development';
const prod = mode === 'production';

const sassOptions = {
	includePaths: [
	  './src/theme',
	  './node_modules',
	  // This is only needed because we're using a local module. :-/
	  // Normally, you would not need this line.
	  path.resolve(__dirname, '..', 'node_modules')
	]
  };

module.exports = {
	entry: {
		bundle: ['./src/main.js']
	},
	resolve: {
		alias: {
			svelte: path.resolve('node_modules', 'svelte')
		},
		extensions: ['.mjs', '.js', '.svelte'],
		mainFields: ['svelte', 'browser', 'module', 'main']
	},
	output: {
		path: __dirname + '/public',
		filename: '[name].js',
		chunkFilename: '[name].[id].js'
	},
	module: {
		rules: [
			{
				test: /\.svelte$/,
				use: {
					loader: 'svelte-loader',
					options: {
						emitCss: true,
						hotReload: true
					}
				}
			},
			{
				test: /\.(sa|sc|c)ss$/,
				use: [
					/**
					 * MiniCssExtractPlugin doesn't support HMR.
					 * For developing, use 'style-loader' instead.
					 * */
					prod ? MiniCssExtractPlugin.loader : 'style-loader',
					'css-loader',
					{
						loader: 'sass-loader',
						options: {
						  ...sassOptions
						},
					},
				]
			}
		]
	},
	mode,
	plugins: [
		new MiniCssExtractPlugin({
			filename: '[name].css'
		})
	],
	devtool: prod ? false: 'source-map'
};

```

**Comment by hperrin** [comment]
In your Sass include path, you need to have a directory that has a `_smui-theme.scss` file. The underscore just tells Sass not to your it into its own CSS file.

**Comment by MintyMods** [comment]
Thank you both for the prompt responses - much appreciated. 

@safaiyeh Thank you for sharing your webpack.config - as I would like to use Sapper I am unable to directly copy your config but I did compare yours to mine and see no obvious difference apart from mine fails with the above error when run!

@hperrin So ignoring my total lack of experience with using NPM/Webpack, by 'Sass include path' you mean the following part of my config:-

```
const sassOptions = {
		  includePaths: [
		    './src/main/sapper/theme/',
		    './node_modules/',	    
		  ]
		};
```

I have tried different values here but it is mostly guessing as I have no idea how to confirm the file is found and find the error messages to be somewhat hard to debug. Any help on debugging the issue is welcome, for example is it possible to enable any logging, extended output or breakpoints within webpack to determine what it is doing?

I understand my issue is probably not directly related to SMUI but I have been unable to find any documentation on this 'sass process' stage (pre-processing seems to be the thing when using SASS but your instructions state this is not the same as just processing).

Could you clarify the sections within the demo site config where you have commented:-

> "Normally, you would not need this line" / "Normally, you wouldn't do this."

Are these parts required outside of the demo site? E.g. should my config include something similar when using the SMUI components or are those additions specific just to the demo site?

Thank you for any further advice on resolving this very frustrating stage which I hope can be simplified or better documented along with some support for Rollup configuration if this is possible.

**Comment by MintyMods** [comment]
After some further attempts to debug this I finally managed to get a decent error message:-

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'serviceworker'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, serve?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack >= v2.0.0 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           serviceworker: …
         }
       })
     ]
```

Removing the Service Worker just proceeds to complain about Client, then Server. Which suggests it is not compatible with Sapper (or more likely I do not understand how to make it work) so as to not waste anymore time with this I just removed Sapper and replaced my previous config with the following modified config (from [@LaughingBubba](https://github.com/LaughingBubba/svelte-sass-webpack) similar to the suggestion made by @safaiyeh above):-

```
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const path = require('path');
const mode = process.env.NODE_ENV || 'development';
const prod = mode === 'production';

const sassOptions = {
  includePaths: [
    './node_modules',
    './src/main/svelte/theme/'
  ],
};

module.exports = {
	entry: {
		bundle: ['./src/main/svelte/main.js']
	},
	resolve: {
		alias: {
			svelte: path.resolve('node_modules', 'svelte')
		},
		extensions: ['.mjs', '.js', '.svelte'],
		mainFields: ['svelte', 'browser', 'module', 'main']
	},
	output: {
		path: __dirname + '/src/main/resources/public',
		filename: '[name].js',
		chunkFilename: '[name].[id].js'
	},
	module: {
		rules: [
			{
				test: /\.svelte$/,
				use: {
					loader: 'svelte-loader',
					options: {
						emitCss: true,
						hotReload: true
					}
				}
			},
		{
        test: /\.(sa|sc|c)ss$/,
        use: [
          'style-loader',
          MiniCssExtractPlugin.loader,
          'css-loader',
          {
            loader: 'sass-loader',
            options: sassOptions,
          },
        ],
      },
		]
	},
	mode,
	plugins: [
		new MiniCssExtractPlugin({
			filename: '[name].css'
		})
	],
	devtool: prod ? false: 'source-map'
};
```

This is now working fine and I can finally progress to re-implementing my UI using these very awesome SMUI components! 

Thanks Guys for your help. Very much appreciated.

@hperrin as a side question do you have any plans to integrate PNotify into these SMUI components? That would be so cool.

**Comment by hperrin** [comment]
Awesome! I'm glad you got it working. What I meant about preprocessor vs processor is that a preprocessor takes Sass that is embedded in a Svelte file, whereas a processor works on whole Sass files that are `import`ed from the JS.

**Comment by hperrin** [comment]
Yeah, I could integrate PNotify pretty easily, once I finish the Svelte 3 version of it. :D

**Comment by MintyMods** [comment]
Thank you for the clarification and I look forward to the PNotify integration

I am loving Svelte & these components - the code is so clean compared to what I am used to!
