### ISSUE TITLE
The variable bound to a Slider component can only be named as 'value'

### ISSUE THREAD

**Issue by pacifi5t** [hperrin/svelte-material-ui#265]
**Describe the bug**
The variable bound to a Slider component can only be named 'value'. Using any other name will cause an error 

**To Reproduce**
Declare a Slider component and bind it's value to a variable that isn't named 'value'

**Screenshots**
![image](https://user-images.githubusercontent.com/57317100/123461213-7d3e4680-d5f1-11eb-8a80-b62999eda329.png)
![image](https://user-images.githubusercontent.com/57317100/123461410-c4c4d280-d5f1-11eb-88b3-94a41fccdce1.png)
![image](https://user-images.githubusercontent.com/57317100/123461183-73b4de80-d5f1-11eb-80bb-9f2c29dc2ed3.png)

**Comment by rururux** [comment]
This is not a bug, Svelte's binding does not have the ability to accept any name, like ESM's `default export`.

example:
![Screenshot_20210915-064154~01~01](https://user-images.githubusercontent.com/5568054/133339161-945f6c74-4494-44b9-960b-da724ad1f0b3.png)


If you want to use the name sliderValue, you can do this.

```svelte

<Slider
  bind:value={sliderValue}
  ...
```
