### ISSUE TITLE
read only text field

### ISSUE THREAD

**Issue by risalfajar** [hperrin/svelte-material-ui#280]
**Is your feature request related to a problem? Please describe.**
In material documentation, there's a read only text field https://material.io/components/text-fields#input-types
But I can't find this implementation in SMUI

**Describe the solution you'd like**
Provide implementation for read-only textfield

**Additional context**
![image](https://user-images.githubusercontent.com/28381124/132138299-3f93c4ed-8513-4fed-a13b-bb87be894569.png)

**Comment by kasokz** [comment]
This should be implicitly controlled by the 'disabled' property. If you set `disabled={true}`, the CSS classes should automatically be set. At least that was the case in SMUI 2.0. I would expect it to have the same behavior since it is not mentioned in the Migration guides.

**Comment by risalfajar** [comment]
I don't think read-only is the same with disabled, they have different implementations (you can view in the link i gave above)

![image](https://user-images.githubusercontent.com/28381124/132167960-34b5509b-a131-44ec-a8aa-f6178c85a682.png)

**Comment by hperrin** [comment]
You can use `input$readonly` on the `Textfield` component.
