### ISSUE TITLE
Ability to Expand and Collapse Lists

### ISSUE THREAD

**Issue by NickantX** [hperrin/svelte-material-ui#282]
I was hoping to use the expansion panel component for an FAQ/help center page, however it seems SMUI does not support these. They are officially documented components on the [Material Design Guidelines](https://material.io/archive/guidelines/components/expansion-panels.html) website, and are support by the [React version of Material UI](https://material-ui.com/components/accordion), although they are referred to as accordions here.

**Comment by major-mayer** [comment]
Maybe your needs are covered by the Accordion component? https://sveltematerialui.com/demo/accordion/

**Comment by NickantX** [comment]
> Maybe your needs are covered by the Accordion component? https://sveltematerialui.com/demo/accordion/

They are, this issue was opened before the Accordion component was added. I forgot to close it, thanks for the reminder.
