### ISSUE TITLE
Add layout grid component

### ISSUE THREAD

**Issue by hkh12** [hperrin/svelte-material-ui#30]
[Grid](https://material.io/develop/web/components/layout-grid) is a very useful component. Would be great to see them in the library. :thinking:

**Comment by hkh12** [comment]
I'm working on a [similar library](https://github.com/hkh12/svmd). It uses MDC underlying but has some differences with your repository. I think it would be nice if we merge these two into one library.
I've created [LayoutGrid](https://github.com/hkh12/svmd/blob/master/src/Grid.svelte) & [LayoutCell](https://github.com/hkh12/svmd/blob/master/src/Cell.svelte) components, and I think they would be helpful in here too. Have a look at them!

**Comment by Dragomir-Ivanov** [comment]
Please, don't waste resources doing the same thing twice. I would love to swap React for Svelte, but I do like Material UI too :)

**Comment by hkh12** [comment]
> Please, don't waste resources doing the same thing twice. I would love to swap React for Svelte, but I do like Material UI too :)

Sorry, I didn't understand. Could you please explain more?

**Comment by Dragomir-Ivanov** [comment]
Yes, I have a an React App of moderate size, using Material-UI. Sometimes It works sluggish, and I would love to port it to Svelte. Focusing on one implementation of Material Design on Svelte will make it much more popular. So please guys, join forces and make just one implementation of Material Design. I guess I can help as well, when have some time :)

**Comment by hkh12** [comment]
> Well, grid is a fully Sass component, like Typography. I could make a demo showing how to use it, but I don't think it would benefit from being a Svelte component.

Why it wouldn't? Because they don't have any "JavaScript Instantiation"?
Buttons are also Sass components, but it is better for them to be extracted into new components, for more ease of use.
I think having typography and grid components included in the library would be really, really good.
```svelte
<H1>Do you prefer this?</H1>
<h1 class="mdc-typography--headline6">or this?</h1>
```

**Comment by hperrin** [comment]
I could do it, but it would add code to your bundle without really giving you any value. The button provides value by handling classes for its current location (eg, in the actions in a dialog).

**Comment by acim** [comment]
> Well, grid is a fully Sass component, like Typography. I could make a demo showing how to use it, but I don't think it would benefit from being a Svelte component.

It would be nice to have a demo.

**Comment by Zahara-Nour** [comment]
I tried to use MDC Grid Layout in a top .scss file or in <style> section in a component  with :

- `@import "@material/layout-grid/mdc-layout-grid"`
=>   got error :
```
[!] (plugin postcss) Error: Invalid CSS after "...ch $size in map": expected expression (e.g. 1px, bold), was ".keys(variables.$co"
src/main.scss
```

- `@use "@material/layout-grid/mdc-layout-grid"`
=> mdc classes are not applied

@hperrin can you show us how to do ?

**Comment by nateshmbhat** [comment]
is Grid component gonna be added ? @hperrin

**Comment by hperrin** [comment]
It is, in the next version.

**Comment by hperrin** [comment]
Done!

**Comment by hperrin** [comment]
Check it out: https://sveltematerialui.com/demo/layout-grid/
