### ISSUE TITLE
Tab doesn't handle click correctly.

### ISSUE THREAD

**Issue by hperrin** [hperrin/svelte-material-ui#320]
**Describe the bug**
Tab doesn't handle click correctly.

**To Reproduce**
See https://github.com/hperrin/svelte-material-ui/blob/fa150f3f35244d314d3739857e8a70f9c32b6500/packages/tab/Tab.svelte#L34

**Expected behavior**
The function should be called on click, not on load.

**Comment by c2j** [comment]
on:click={() => (instance && instance.handleClick())}

**Comment by hperrin** [comment]
Is that not how it is?

**Comment by hperrin** [comment]
This issue points to code from a specific commit...

**Comment by hperrin** [comment]
Yeah, this is fixed now.

https://github.com/hperrin/svelte-material-ui/blob/master/packages/tab/src/Tab.svelte

Thanks for raising it up. :) Always good to close old issues.
