### ISSUE TITLE
[docs] Checkbox in Data Table header does not work correctly

### ISSUE THREAD

**Issue by KoichiKiyokawa** [hperrin/svelte-material-ui#321]
Thank you for maintaining such a nice library.
And I'm so glad you've been working on the migration to TypeScript!

**Describe the bug**
In the [Data Table doc page](https://sveltematerialui.com/demo/data-table/), the checkbox in Data Table header does not work correctly.
(Maybe, the behavior used to be that all rows were selected when checked it.)

**To Reproduce**
1. Go to https://sveltematerialui.com/demo/data-table/
2. Go to `Row selection`
3. Click checkbox in the header.

**Expected behavior**
- all rows are selected when checked it.
- all rows are unselected when unchecked it.

**Screenshots**

https://user-images.githubusercontent.com/40315079/133206222-b8c40591-143e-4acf-98a4-74f83a97dd65.mp4

(accessed at 2021/09/14 06:27 UTC)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 93.0.4577.63

**Comment by hperrin** [comment]
Fixed!

**Comment by KoichiKiyokawa** [comment]
@hperrin Thank you so much!!

**Comment by markusschmitz53** [comment]
> Fixed!

Thanks @hperrin . Is the fix released already in v5.0.0-beta.2?

**Comment by hperrin** [comment]
@markusschmitz53, it's in 5.0.0-beta.1. The only release that had it was the .0 beta.
