### ISSUE TITLE
SMUI 5.0.0-beta.1 Typescript Bundle Error

### ISSUE THREAD

**Issue by roociferSonOfTheMorning** [hperrin/svelte-material-ui#326]
**Describe the bug**
SMUI 5.0.0-beta.1 bundle error:

[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
node_modules/@smui/common/smui.d.ts (5:7)

**To Reproduce**
1. Go to [svelte-typescript](https://github.com/bchurlinov/svelte-typescript)
2. Follow Install w/ "Using Typescript" step
3. Go to [smui Install](https://sveltematerialui.com/INSTALL.md)
4. Install Button and add a button to App.svelte
5. Run `npm run dev`

**Expected behavior**
The web app launches and a smui button is on the screen.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version 93

**Comment by hperrin** [comment]
This is fixed with the latest beta. :)

**Comment by roociferSonOfTheMorning** [comment]
Thank You! It's working!
