### ISSUE TITLE
Cannot access 'internals' before initialization

### ISSUE THREAD

**Issue by mdiener** [hperrin/svelte-material-ui#329]
**Describe the bug**
I'm trying to have a simple Textfield component loading on a page. It however throws the following error after a quick second of rendering it correctly. This also only occurs when running `npm run dev` and not when doing a full `npm run build && npm run preview`. The provided output is rather sparse:
```
500
Cannot access 'internals' before initialization
ReferenceError: Cannot access 'internals' before initialization
    at http://localhost:3000/node_modules/@smui/common/internal/classAdderBuilder.js:3:36
```

**To Reproduce**
1. `npm init svelte@next test` (chose typescript support)
2. `cd test`
3. `npm install`
4. `npm install --save-dev @smui/textfield smui-theme`
5. create a Textfield component in index.js
6. `npm run dev`

**Expected behavior**
The component should display normally as a text field.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Additional context**
This is the content of my index.js file for the textfield component:
```
<script lang="ts">
  import Textfield from '@smui/textfield'

  let value: string | null = null;
</script>

<Textfield bind:value />
```

**Comment by Serjlee** [comment]
This is also baffling me. I discovered you can fix it by monkey patching `node_modules/@smui/common/internal/classAdderBuilder.js:3` with: 
```js
const defaults = Object.assign({}, {
    class: '',
    classMap: {},
    contexts: {},
    props: {}})
```

But I've frankly got no clue on why it doesn't work out of the box

**Comment by mdiener** [comment]
At least the explanation for why a `ReferenceError` is thrown appears to be that something tries to access the internals variable before it is being initialized. I can only assume this doesn't happen during regular "build" because it moves the different pieces of code around and somehow moves the initialization of this variable up.

**Comment by tuchuants** [comment]
I have no idea why this happened, but at least downgrade to 4.2.0 would be a workaround.

**Comment by hperrin** [comment]
I think I've figured this out. I'm moving internals back into the Svelte components and just ignoring the TS error about it not being exported. It is exported.

**Comment by Serjlee** [comment]
@hperrin I'm still getting the same issue on beta.6 :(

**Comment by michapixel** [comment]
me too, but i have another situation. this is a sveltekit-nwjs app, so i wouldn't wonder.

But sometimes - if i rearrange my imports - the error goes away. next time i'm adding an import: boom.

**Comment by michapixel** [comment]
> 
> 
> This is also baffling me. I discovered you can fix it by monkey patching `node_modules/@smui/common/internal/classAdderBuilder.js:3` with:
> 
> ```js
> const defaults = Object.assign({}, {
>     class: '',
>     classMap: {},
>     contexts: {},
>     props: {}})
> ```
> 
> But I've frankly got no clue on why it doesn't work out of the box

how do you monkeypatch this?

**Comment by hperrin** [comment]
I didn't figure it out...
But I did now. I had a circular dependency that TypeScript didn't recognize.

**Comment by hperrin** [comment]
I have no idea why this issue doesn't appear all the time. Very strange.

**Comment by michapixel** [comment]
I really don't know why it's so unstable in it's errors.

But i messed up my package.json an therefore deleted all modules and reinstalled with latest and boom. It works. 

I'm sorry. My best gess it's been the svelte-kit package which caused all the trouble.

The error always occurred in Button.js which was the first one imported in my project..
I guess that error is terribly misleading. 
But since your components are highly complex in code, i thought, maybe ... 😔🤭

**Comment by hperrin** [comment]
Well, once I release this newest change, that should fix it permanently.

**Comment by hperrin** [comment]
Ok, the latest version should fix this permanently.

**Comment by Serjlee** [comment]
I can confirm it works fine with beta.7, thanks a lot!
