### ISSUE TITLE
`@smui/common/internal.js` does not provide an export named 'ActionArray'

### ISSUE THREAD

**Issue by tuchuants** [hperrin/svelte-material-ui#330]
**Describe the bug**
When I'm trying to use the latest beta version of smui to build a website, the console of my browser complains a problem:

![image](https://user-images.githubusercontent.com/34856540/134318219-6e1cb06e-1772-47f2-9d43-2693f43f7ed4.png)

When I dive into the codebase, I found that the `5.0.0-beta-5` version wrongly import a typescript type from js file, which would result in a compile error.

```typescript
// @smui/drawer/Drawer.svelte and so on

...
  import {
    forwardEventsBuilder,
    classMap,
    useActions,
    dispatch,
    ActionArray,
  } from '@smui/common/internal/index.js';
  const { FocusTrap } = domFocusTrap;
...
```

**To Reproduce**
No Steps.

**Expected behavior**
```diff
# @smui/drawer/Drawer.svelte and so on

...
  import {
    forwardEventsBuilder,
    classMap,
    useActions,
    dispatch,
-  ActionArray,
  } from '@smui/common/internal/index.js';
+ import type { ActionArray } from '@smui/common/internal/index.ts'
  const { FocusTrap } = domFocusTrap;
...
```

or

```diff
# @smui/drawer/Drawer.svelte and so on

...
  import {
    forwardEventsBuilder,
    classMap,
    useActions,
    dispatch,
    ActionArray,
-} from '@smui/common/internal/index.js';
+} from '@smui/common/internal/index'
  const { FocusTrap } = domFocusTrap;
...
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: 5.0.0-beta-5
 
**Additional context**

**Comment by hperrin** [comment]
It looks like you're not using a preprocessor, and you need to use the [Svelte Preprocessor](https://github.com/sveltejs/svelte-preprocess) with the latest version. If this is incorrect, feel free to open this issue again.

**Comment by Zielak** [comment]
@hperrin This error pops up today when using `"@tsconfig/svelte": "^3.0.0"`. This with TS 4.5 requires your imported values and types be separate like so:
```ts
  import {
    forwardEventsBuilder,
    classMap,
    exclude,
    prefixFilter,
    useActions,
    dispatch
  } from '@smui/common/internal';
  import type { ActionArray }  from '@smui/common/internal';
```

For now I'll just rollback "@tsconfig/svelte" to v2.
