### ISSUE TITLE
The Beta version shouldn't be the default option in the install.

### ISSUE THREAD

**Issue by flpms** [hperrin/svelte-material-ui#331]
**Describe the bug**
When running `npm i -D @smui/{some-component}` are point to beta versions, which is very bad and break on pura JS project.

**To Reproduce**
1. Create a clean svelte project
2. Try to use any component from `svelte-material-ui`

**Expected behavior**

Install the latest reliable non-beta version of any component

<img width="508" alt="image" src="https://user-images.githubusercontent.com/4911643/134421179-e3a6de07-69af-4f66-8f5f-cffeae114ac2.png">

**Comment by hperrin** [comment]
These don't break a pure JS project, you just need to install the preprocessor.

**Comment by flpms** [comment]
Sorry, maybe I don't fully understand what a break changes is, but If I full setup a project and after update the project don't run anymore because a "you need install preprocessor", the seems a break change to me, and it's not the problem itself. 

I choose  this material due a great work which it's done, but there's small painful flaws, like npm point to beta version instead install the latest non-beta version. (here I not mention at all the typescript change)

The main issue is solved with the release of 5.0.0, but from my understanding the same mistakes could be change for the 6.0.0 release, when it's on the beta version.

**Regards the Typescript** which is more relate to #343 and please don't take my tone as too harsh, but you're javascript developer should be more careful about it, _since people relying on your JS_ (not typescript) library, honestly I don't care about your development processing if you are using Coffeescript, Typescript, whatever. 

But me as a user, when I go to npm search for a front-end library I expect install a JS version in my project, and the maintainer make his work of pre-process files with they choose using something different for JS.

I'm really desire go with you library to production in my project, but these flaws make me think twice with I should keep attached to this plan and rely on it.
