### ISSUE TITLE
Error: SMUI Textfield initialized without Input component

### ISSUE THREAD

**Issue by Peterkmoss** [hperrin/svelte-material-ui#336]
**Describe the bug**
When trying to use the Textfield component, the error `Error: SMUI Textfield initialized without Input component` is produced and the component doesn't render.

I'm on version 5.0.0-beta.7.
 
**To Reproduce**
```
import Textfield from '@smui/textfield'
...
<Textfield />
```

Load page with Textfield and the error is produced.

**Expected behavior**
No error and the Textfield is rendered.

**Desktop (please complete the following information):**
 - OS: MacOS 11.5.2
 - Browser Firefox and Chromium
 - Version 92.0.1 (Firefox) 93.0.4565.0 (Chromium

**Comment by Peterkmoss** [comment]
I played around some more and found out it was since my value was `undefined`, even though I thought it was fixed since #274 is closed though it still seems to give issues for me at least.

**Comment by hperrin** [comment]
You can now work around this in 6.0.0-beta.9. If an empty value should be set to `undefined` use the `input$emptyValueUndefined` prop on the textfield.

**Comment by hperrin** [comment]
The fix for #274 worked, but something since then broke it. It's now fixed again. :D

**Comment by sunath** [comment]
Make sure to bind it to a local variable.
Variable must be initialize with  " " or your default value
This work for me

**Comment by igorsantos07** [comment]
Shouldn't this (rather stupid) issue be documented? lol
