### ISSUE TITLE
Make new release for fixes since 1.0.0-beta15?

### ISSUE THREAD

**Issue by eddiew** [hperrin/svelte-material-ui#34]
I'd like to use the fixes for the onDestroy() functions in sapper, and it's really annoying to try to install the packages directly from the git repo because they're nested packages

**Comment by pro7tech** [comment]
What/Where are the fixes? Is there a way to patch them in manually?

**Comment by hperrin** [comment]
Oh. I thought I had released them to npm. I call cut a release today. I think I've only got a few more bugs to fix and docs to write before version 1.

**Comment by pro7tech** [comment]
@hperrin Thanks so much for your incredible work!  I'd been developing an app with React and the most popular material UI library in the world (50,000 github stars - https://material-ui.com/) and switching to Svelte and your beta version is already a much better experience!  Less boilerplate, more fun.  Hope you become the next #1 !

**Comment by hperrin** [comment]
@eddiew @pro7tech New version is out, that should work with Sapper! @pro7tech Thank you! I'm really happy to hear that. I'm hoping to expand on what I have a lot. :D
