### ISSUE TITLE
is there a way to programmaticaly select a list entry

### ISSUE THREAD

**Issue by christophemacabiau** [hperrin/svelte-material-ui#363]
** Is this for an existing documentation file? **
[_Simple.svelte](https://github.com/hperrin/svelte-material-ui/blob/master/packages/site/src/routes/demo/list/_Simple.svelte)

** What needs improvement? **
I do not even know if it's feasible. I need when the list is shown  to have the first element selected

**Comment by hperrin** [comment]
Use a singleSelection list.

**Comment by hperrin** [comment]
Like this one:

https://github.com/hperrin/svelte-material-ui/blob/master/packages/site/src/routes/demo/list/_TwoLineSelection.svelte

**Comment by christophemacabiau** [comment]
Thanks for your quick answer @hperrin 
I wrongly formulated my question. Is there a way to focus the selected item of a list? (when the list appears, I want to be able to be able to change the selected item immediately)
And thanks for your work!
