### ISSUE TITLE
Dialog showModal() support

### ISSUE THREAD

**Issue by MintyMods** [hperrin/svelte-material-ui#37]
Hi Hunter,

More of a question than an issue but I am trying to use the dialog in a modal format so that the dialog needs to be dismissed via a button rather than clicking on the `scrim`. 

HTML5 has modal via the [`HTMLDialogElement.showModal()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal) although [caniuse](https://caniuse.com/#search=dialog) shows this is not yet widely supported. There is also [`window.showModalDialog()`](https://caniuse.com/#search=showModalDialog) which seems to be an legacy thing and now deprecated. 

Checking the code for `@smui/dialog` and `MDCDialog` shows no current support for opening as modal so my options seem to be:-

- Using `dialog.showModal()` with the limited browser support.
- Implement my own modal support e.g listen for the close event and cancel it.

When considering all this my thoughts are why does `@smui/dialog` not support modal which I guess is because `MDCDialog` in turn doesn't support modal. Searching various other dialog components shows the same lack of any modal support.

Does this suggest that a modal approach is wrong in terms of UI/UX and I should just use the `@smui/dialog` as is (assuming #35 is resolved) and code accordingly to cope with the dialog being dismissed by clicking the scrim (or pressing ESC) or do you have any plans on implementing support for a `showModal()` version of `@smui/dialog`?

Interested to hear what your thoughts as a font end developer are in regards to using a fully modal dialog?

**Comment by MintyMods** [comment]
There is a [dialog-polyfill](https://github.com/GoogleChrome/dialog-polyfill) so that is also an option.

**Comment by hperrin** [comment]
(Thought this was a different issue.)
