### ISSUE TITLE
Error of `Unknown file extension ".svelte"` in SvelteKit

### ISSUE THREAD

**Issue by alanko0511** [hperrin/svelte-material-ui#375]
**Describe the bug**
I followed steps in [the SvelteKit installation](https://sveltematerialui.com/SVELTEKIT.md), but when I run `npm run dev`, whatever what components are used, there is always an error of `Unknown file extension ".svelte...`. After the first load, the issue seems to be gone, but if I run `npm run build` and `npm run preview` to build the website, the error happens with `500 Cannot find package '/.../node_modules/@smui/button/'`

For example when I used [buttons](https://github.com/hperrin/svelte-material-ui/blob/master/packages/site/src/routes/demo/button/_Simple.svelte), the error is:
`Unknown file extension ".svelte" for /.../node_modules/@smui/button/dist/Button.svelte`

**To Reproduce**
1. `npm init svelte@next users` Which Svelte app template? > Skeleton project, Use TypeScript? Yes
2. Follow steps [here](https://sveltematerialui.com/SVELTEKIT.md) without dark mode support.
3. Replace content in `index.svelte` with [button example svelte](https://github.com/hperrin/svelte-material-ui/blob/master/packages/site/src/routes/demo/button/_Simple.svelte)

**package.json**
```json
{
  "name": "project",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "package": "svelte-kit package",
    "preview": "svelte-kit preview",
    "check": "svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-check --tsconfig ./tsconfig.json --watch",
    "prepare": "npm run smui-theme",
    "smui-theme": "smui-theme compile static/smui.css -i src/theme"
  },
  "devDependencies": {
    "@smui/button": "^6.0.0-beta.4",
    "@smui/card": "^6.0.0-beta.4",
    "@sveltejs/adapter-auto": "next",
    "@sveltejs/kit": "next",
    "smui-theme": "^6.0.0-beta.4",
    "svelte": "^3.44.0",
    "svelte-check": "^2.2.6",
    "svelte-preprocess": "^4.9.4",
    "tslib": "^2.3.1",
    "typescript": "^4.4.3"
  },
  "type": "module"
}
```

**svelte.config.js**
```js
import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: adapter(),

		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte'
	}
};

export default config;
```

**Comment by BlockListed** [comment]
Same issue here!

**Comment by benmccann** [comment]
@alanko0511 can you create a repository with the code in the end state per your instructions and post it here? We get quite a lot of issue reports, so it's too hard for us to do for every single issue that comes in. Thanks!

**Comment by alanko0511** [comment]
> @alanko0511 can you create a repository with the code in the end state per your instructions and post it here? We get quite a lot of issue reports, so it's too hard for us to do for every single issue that comes in. Thanks!

Sure, here is a simple repo to reproduce the issue:
https://github.com/alanko0511/smui-bug

**Comment by benmccann** [comment]
This library is not packaged in a valid manner. There's no `main` in the `package.json`. It's also recommended to have a `svelte` field. If I add those locally then it works:
```
  "main": "dist/index.js",
  "module": "dist/index.js",
  "svelte": "dist/index.js",
```

**Comment by alanko0511** [comment]
> This library is not packaged in a valid manner. There's no `main` in the `package.json`. It's also recommended to have a `svelte` field. If I add those locally then it works:
> 
> ```
>   "main": "dist/index.js",
>   "module": "dist/index.js",
>   "svelte": "dist/index.js",
> ```

I tried and it works great. It seems that the temporary solution is to add these fields to all components installed inside `@smui`.

**Comment by kwangure** [comment]
@benmccann Is this documented somewhere (docs/issue/PR)? Somewhere I can read further details (e.g What exactly is in the `dist/index.js`? What if I have more than one `index.js`?  

Suppose, I have a Svelte library like `svelte-material-ui`. I'd like to do this in my package.json:

```json
"exports": {
    "./package.json": "./package.json",
	"./components/Dropdown": "./components/Dropdown/index.js",
	"./components/Select": "./components/Select/index.js",
    "./style.css": "./deep/folder/style.css"
}
```

Then `Dropdown` exports its dependents such as a popup menu and button, while `Select` exports select and option components. How does the `"exports"` field fit in with the `"main"/"svelte": "dist/index.js"` field? I'm using `svelte-kit package` if that makes a difference.

Can I import a `.svelte` components independently without going through an `index.js`?

**Comment by benmccann** [comment]
If you provide an `exports` then `main` and `module` are not used

**Comment by kwangure** [comment]
I have an "exports" field in my package and I'm still getting this error. I'll investigate further. If there's something to report, I'll do it in a relevant repo to avoid derailing this issue.

**Comment by hperrin** [comment]
I've found a workaround for this.

The following in `config.kit` in the `svelte.config.js` file seems to do the trick:

```
vite: {
  ssr: {
    noExternal: [/^@smui(?:-extra)?\//],
  },
},
```

**Comment by hperrin** [comment]
I'll add that to the SvelteKit instructions. The reason there's no "main" or "svelte" entries in the package.json files is that "main" is only needed for commonjs (AFAICT), and all the SMUI packages are ES modules, and "svelte" is only needed if it differs from "main" or "module".

https://docs.npmjs.com/cli/v6/configuring-npm/package-json#main

The proper fix would be for Vite to recognize that the packages are using the "module" prop, signifying that they are ES modules, and should treat them as such.

**Comment by benmccann** [comment]
> I'll add that to the SvelteKit instructions

Please don't. Users should not have to manually specify `noExternal`. Just fix the `package.json` instead

> main" is only needed for commonjs

That's not true. Node.js still uses the `main` even for ES6 modules.

> The proper fix would be for Vite to recognize that the packages are using the "module" prop, signifying that they are ES modules, and should treat them as such.

It does recognize that the package is an ES6 module, but Node.js still requires a `main`. You can test that by creating an ES6 package in `node_modules`, importing it from a script, and running `node script.js`. Vite is following the Node.js spec here. Perhaps it would be more error tolerant of broken packages to do what you're suggesting, but it would not be inline with how Node works nor should package authors expect a behavior deviating from the spec

**Comment by confraria** [comment]
@hperrin thanks for the work-around! Would you accept a PR with a fix for this?

**Comment by hperrin** [comment]
If the fix would work for every package (including textfield, select, and snackbar, which have multiple exports defined in an `"exports"` field) and wouldn't break usage with other bundlers, yeah, I would accept a PR.

**Comment by hperrin** [comment]
> Vite is following the Node.js spec here.

@benmccann Until very recently, Node.js' ES module support was behind a `--experimental-modules` flag, so if Vite supported ES modules without that flag, then isn't it not according to the spec? And if you were to try to use one of my modules without that flag in vanilla Node, wouldn't it break if it had a `"main"` entry? Forgive me if I'm wrong in my assumptions in this thread; we're on the outskirts of my knowledge with regard to Node and Vite.

**Comment by benmccann** [comment]
A flag has not been needed for basically as long as SvelteKit has been using Vite. I believe the flag was no longer required as of March 2020, which is also when SvelteKit switched to Vite.

Vite does support `"exports"`. I'm not aware of any issues with its support of it. I'm happy to take a look if there's some issue in particular you're hitting with it

**Comment by hperrin** [comment]
Hmm. I thought I remembered running into an issue with just the components that use `"exports"` when I had a `"main"` entry. Let me try it out right now.

**Comment by hperrin** [comment]
@benmccann Alright, it seems it does work with `"exports"`, but it also requires a `"svelte"` field to recognize Svelte files, and when there is an `"exports"` field, the `"svelte"` field has no logical value. This doesn't seem to be an issue, as I just added the "default" export to the `"svelte"` field, and that's working, but it does seem odd.

**Comment by benmccann** [comment]
Yeah, there's an issue someplace in the SvelteKit issue tracker about revisiting the `svelte` field. It hasn't been the highest priority yet as it's generally been easy enough to add, but I imagine some day we'll take another look at it. I think it's mainly used to help identify which packages are Svelte packages, so possibly it could just be a boolean or maybe we could look for Svelte in the dependencies.

Anyway, glad it's working now!

**Comment by hperrin** [comment]
@benmccann No worries. I'm glad it's working now without needed the workaround! Sorry for the confusion, and thank you for your guidance! I'll make sure this is working with webpack and rollup and release a new version that doesn't need `noExternal`! :D

Btw, I see you work on SvelteKit, and I gotta say, SvelteKit is absolutely amazing! I'm building an email service with it right now, and it's such an awesome developer experience!

**Comment by hperrin** [comment]
Well, f...

Apparently `@material/dom` is packaged as both cjs and es6, and it's causing issues.

```
> Using @sveltejs/adapter-static
file:///home/hperrin/repos/smui/packages/site/.svelte-kit/output/server/chunks/index-5a6b7126.js:7
import { announce } from "@material/dom/announce.js";
         ^^^^^^^^
SyntaxError: Named export 'announce' not found. The requested module '@material/dom/announce.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@material/dom/announce.js';
const { announce } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.load_component (file:///home/hperrin/repos/smui/packages/site/.svelte-kit/output/server/chunks/app-76386b54.js:865:13)
    at async Promise.all (index 1)
    at async respond$1 (file:///home/hperrin/repos/smui/node_modules/@sveltejs/kit/dist/ssr.js:1211:11)
    at async render_page (file:///home/hperrin/repos/smui/node_modules/@sveltejs/kit/dist/ssr.js:1454:19)
    at async resolve (file:///home/hperrin/repos/smui/node_modules/@sveltejs/kit/dist/ssr.js:1717:10)
    at async respond (file:///home/hperrin/repos/smui/node_modules/@sveltejs/kit/dist/ssr.js:1696:10)
    at async visit (file:///home/hperrin/repos/smui/node_modules/@sveltejs/kit/dist/chunks/index4.js:167:20)
> 500 /demo/chips (linked from /demo/checkbox)
```

**Comment by hperrin** [comment]
Everything outside of `dist` is es6 modules, but the package.json doesn't have `"type": "module"`.

**Comment by hperrin** [comment]
I might be able to get around this with a dynamic import.

**Comment by hperrin** [comment]
With 7ac0383ebe384332a7666a451caa6209a1af0da9, this is now fully fixed. I just implemented my own announce function, since it's relatively simple anyway.

**Comment by benmccann** [comment]
That's great! Thanks so much for providing the great library @hperrin! And thanks for the kind words earlier :smile:

**Comment by perciag** [comment]
> I've found a workaround for this.
> 
> The following in `config.kit` in the `svelte.config.js` file seems to do the trick:
> 
> ```
> vite: {
>   ssr: {
>     noExternal: [/^@smui(?:-extra)?\//],
>   },
> },
> ```

This worked for me!

**Comment by shuaixr** [comment]
Looks like the bug has been fixed...
But still have this error in `6.0.0-beta.16`...
Where am I doing wrong?
Error log:
```
Unknown file extension ".svelte" for /ProjectPath/node_modules/@smui/common/dist/classadder/ClassAdder.svelte
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".svelte" for /ProjectPath/node_modules/@smui/common/dist/classadder/ClassAdder.svelte
    at new NodeError (node:internal/errors:387:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:80:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:122:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:173:28)
    at ESMLoader.load (node:internal/modules/esm/loader:616:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:472:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at #createModuleJob (node:internal/modules/esm/loader:491:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:449:34)
```
package.json:
```
{
	"name": "name",
	"version": "0.0.1",
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"package": "svelte-kit package",
		"preview": "vite preview",
		"test": "playwright test",
		"check": "svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --check --plugin-search-dir=. . && eslint .",
		"format": "prettier --write --plugin-search-dir=. .",
		"prepare": "svelte-kit sync && npm run smui-theme-light && npm run smui-theme-dark",
		"smui-theme-light": "smui-theme compile static/smui.css -i src/theme",
		"smui-theme-dark": "smui-theme compile static/smui-dark.css -i src/theme/dark"
	},
	"devDependencies": {
		"@playwright/test": "^1.22.2",
		"@smui/paper": "^6.0.0-beta.16",
		"@smui/top-app-bar": "^6.0.0-beta.16",
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"@types/cookie": "^0.5.1",
		"@typescript-eslint/eslint-plugin": "^5.27.0",
		"@typescript-eslint/parser": "^5.27.0",
		"eslint": "^8.16.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.7.0",
		"smui-theme": "^6.0.0-beta.16",
		"svelte": "^3.47.0",
		"svelte-check": "^2.7.1",
		"svelte-preprocess": "^4.10.6",
		"tslib": "^2.3.1",
		"typescript": "^4.7.4",
		"vite": "^3.0.0"
	},
	"type": "module",
	"dependencies": {
		"@fontsource/fira-mono": "^4.5.0",
		"cookie": "^0.4.1"
	}
}
```

**Comment by sharu725** [comment]
> This library is not packaged in a valid manner. There's no `main` in the `package.json`. It's also recommended to have a `svelte` field. If I add those locally then it works:
> 
> ```
>   "main": "dist/index.js",
>   "module": "dist/index.js",
>   "svelte": "dist/index.js",
> ```

Adding these and removing ``exports`` filed helped solving the same issue I had.

**Comment by s1nistr4** [comment]
Still an issue in 2023, shipping broken and unusable with sveltekit, top result in google with multiple people reporting the same issue and no fix

I recommend checking out uikit or ionic until framework7 can start fixing severe issues like this

**Comment by fivaz** [comment]
still a problem in 2024, such a shame because the design of your components is beautiful.

**Comment by LarryEmerson12** [comment]
I have the same problem.

![image](https://github.com/user-attachments/assets/2f64d2b3-74bb-4a70-ade8-d0600e8e5097)

**Comment by hideosnes** [comment]
It happened with lucide/svelte. While the library is correctly packed, this helped:

> > I've found a workaround for this.
> > The following in `config.kit` in the `svelte.config.js` file seems to do the trick:
> > ```
> > vite: {
> >   ssr: {
> >     noExternal: [/^@smui(?:-extra)?\//],
> >   },
> > },
> > ```
> 
> This worked for me!
