### ISSUE TITLE
Icon Button Toggle inverted when not using "bind"

### ISSUE THREAD

**Issue by Egnus** [hperrin/svelte-material-ui#38]
I found a bug in the Icon-Button Component.
With certain conditions the icons are not toggling as expected when we disable bindings and use events and props instead.

I left a very self explanatory example in REPL:

https://svelte.dev/repl/f4b9646e2afe41eca3a1f788e62e0e46?version=3.12.1

**Comment by hperrin** [comment]
It looks like the problem comes from using `toggle` without binding to the var. I'll update the demos to show this. Here is a working version of the REPL:
https://svelte.dev/repl/1db1aa67b1ad4b928dfa146902239c13?version=3.12.1

**Comment by hperrin** [comment]
I think this behavior should be expected, since the component is handing off management of the variable to the MDC component when the `toggle` prop is set.
