### ISSUE TITLE
Demo Select page is broken

### ISSUE THREAD

**Issue by rhscjohn-dev** [hperrin/svelte-material-ui#388]
**Describe the bug**
None of the examples for the component Select are working.  Clicking on the source code shows no source code.

**To Reproduce**
1. Go to ['link'](https://sveltematerialui.com/demo/select/)
2. Click on any of the examples

**Expected behavior**
Each of the examples should show a list of fruits when when clicking on the example.  Also clicking on the source code should show the source code for the example in question.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 96.0.4664.110

**Additional context**

**Comment by hperrin** [comment]
Fixed!
