### ISSUE TITLE
Error theming Snackbar component with Sass

### ISSUE THREAD

**Issue by msmolens** [hperrin/svelte-material-ui#409]
**Describe the bug**
When following the [Theming with Sass](https://github.com/hperrin/svelte-material-ui/blob/9a2fa28a19242cf474c1b8b82f016e75575dd0ee/THEMING.md) instructions, attempting to theme the Snackbar component gives an error when building the CSS.

**To Reproduce**
1. Clone https://github.com/hperrin/smui-example-rollup. I tested at revision hperrin/smui-example-rollup@97b3aa8339685ebc188e08f51d1bb8903fb35bc6.
1. In the `smui-example-rollup` directory run:
    1. `mkdir dist` (avoids error when `npm prepare` runs)
    2. `npm install`
    3. `npm install --save-dev @smui/snackbar@6.0.0-beta.14`
1. In `style/_smui-theme.scss` add the following line:
    ```sass
    @use "@material/snackbar";
    ```
    This allows using [Sass Mixins](https://github.com/material-components/material-components-web/tree/v13.0.0/packages/mdc-snackbar#sass-mixins), like:
    ```sass
    .my-snackbar {
      @include snackbar.viewport-margin(24px);
    }
    ```
1. Run `npm run prepare` to rebuild the CSS.
2. See error like:
    ```
    Error: This module was already loaded, so it can't be configured using "with".
       ┌──> node_modules/@smui/snackbar/_style.scss
    2  │ ┌ @use '@material/snackbar/index' as snackbar with
    3  │ │   ($action-ink-color: theme-color.prop-value(primary));
       │ └──────────────────────────────────────────────────────^ new load
       ╵
       ┌──> style/_smui-theme.scss
    14 │   @use "@material/snackbar";
       │   ━━━━━━━━━━━━━━━━━━━━━━━━━ original load
    ```
    Note that I can successfully theme other components this way, for example:
    ```sass
    @use "@material/dialog";
    
    .my-dialog {
      @include dialog.min-width(480px);
    }
    ```

**Expected behavior**
Writing `@use "@material/snackbar";` in `_smui-theme.scss` doesn't cause an error when building the CSS. This would allow customizing the theme of the Snackbar component.

**Desktop**
 - OS: Ubuntu 20.04.3 LTS
 - Node.js 16.13.2

**Comment by hperrin** [comment]
Try `@use "@material/snackbar/mixins" as snackbar;` instead.

**Comment by msmolens** [comment]
When replacing `@use "@material/snackbar";` with `@use "@material/snackbar/mixins" as snackbar;` in `_smui-theme.scss` I see a similar error:

```
Error: This module was already loaded, so it can't be configured using "with".
  ┌──> node_modules/@material/snackbar/_index.scss
1 │   @forward "./variables";
  │   ^^^^^^^^^^^^^^^^^^^^^^ new load
  ╵
  ┌──> node_modules/@material/snackbar/_mixins.scss
34│   @use './variables';
  │   ━━━━━━━━━━━━━━━━━━ original load
  ╵
  ┌──> node_modules/@smui/snackbar/_style.scss
2 │ ┌ @use '@material/snackbar/index' as snackbar with
3 │ │   ($action-ink-color: theme-color.prop-value(primary));
  │ └──────────────────────────────────────────────────────^ configuration
  ╵
```

As suggested by the error message, I found that removing the `with (...)` configuration from the `@use` statement in `node_modules/@smui/snackbar/_style.scss` avoids the build error. But, presumably, SMUI wants that configuration.

**Comment by hperrin** [comment]
I'm not sure how you'd go about working around this. You can ask on the upstream MDC-Web repo here:
https://github.com/material-components/material-components-web/issues
