### ISSUE TITLE
Wrong Select initialisation?

### ISSUE THREAD

**Issue by mwamp** [hperrin/svelte-material-ui#41]
I have the following issue (which I have not tested on a minimal example)

```
value="orange"
<Select bind:value={value}>
 <Option value="" selected={value===""}></Opt>
<Option value="orange" selected={value==="orange}></Opt>
</Select>
```
In my case, the previous code would start with value=""

Proposed fix (Select.svelte)
```
onMount(async () => {
    select = new MDCSelect(element);
    select.value = value; //FIX is Here
    
    menuPromiseResolve(select.menu_);

    if (!ripple && select.ripple) {
      select.ripple.destroy();
    }

    if (updateInvalid) {
      invalid = inputElement.matches(':invalid');
    }
  });
```
works for me

**Comment by MintyMods** [comment]
+1 Also works for me. I have previously been using the following to trigger the update for selects:-

```
  let selected;
  onMount(async()=>{
    await tick();
    selected = shape;
  })
...<Option value={option.type} selected={option.type === selected}>
```
Sticking that fix in allows me to remove 6 lines of code from each select component I use.

**Comment by mwamp** [comment]
Thx for the feedback, let me propose the change 
#42

**Comment by Eradash** [comment]
I tested the fix in my project and it works well!

**Comment by hperrin** [comment]
I don't think any of my demos actually start with a value. That should be fixed. xD

**Comment by hperrin** [comment]
Fixed in https://github.com/hperrin/svelte-material-ui/commit/66af45d2ec6f3c3bbe7c7ee982fbf6f8b48ac3ce
