### ISSUE TITLE
SvelteKit now generates its own prepare script

### ISSUE THREAD

**Issue by PazJal** [hperrin/svelte-material-ui#425]
In the [SvelteKit docs](https://github.com/hperrin/svelte-material-ui/blob/b4ee7ebe8c0dc47b44ab760a5b0b8cea25aed5f5/SVELTEKIT.md) - 

SvelteKit now generates it own "prepare" script on skeleton projects - just rename the script in the docs.

**Comment by hperrin** [comment]
It has to be in prepare so it runs on `npm install`, but yeah, the docs need to be updated.

**Comment by YasharSL** [comment]
I have the same problem. How should I solve this?
I added this line in my scripts
```
{
    "prepare": "npm run smui-theme-light && npm run smui-theme-dark && svelte-kit sync",
}

```

**Comment by hperrin** [comment]
That line should work.
