### ISSUE TITLE
Accordions can not be nested

### ISSUE THREAD

**Issue by choofy** [hperrin/svelte-material-ui#436]
**Describe the bug**
I have an accordion consisting of 1 panel, and on that panel, I have another accordion. Opening the outer panel goes fine, but then when I try to open the panel of the inner accordion, it does not open.

**To Reproduce**
1. Create and accordion within the panel of another accordion
2. Open the outer accordion by clicking on its header
3. Click on the header of the inner accordion
4. See error: Inner accordion does not open

**Expected behavior**
Accordions within other accordions respond properly (independently of their outer accordion).

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version  99.0.4844.84

**Additional context**
Cause could be that accordions use getContext/setContext for the "open" flag. Because contexts are accessible for all child nodes, the inner accordion uses the same "open" flag as the outer accordion. This is suspicious.

**Comment by CryptAlchemy** [comment]
Bump

Repl with unexpected behavior:
https://svelte.dev/repl/03b6e62f865d42f3adc6e6923ad6dbd7?version=3.37.0
