### ISSUE TITLE
how to prevent screen flicker when page refresh

### ISSUE THREAD

**Issue by msh2050** [hperrin/svelte-material-ui#450]
I flowed the tutorial on this [video ](https://www.youtube.com/watch?v=OyjZ7dezADw) to set the theme.
but if I add a local store the screen will flicker if the stored them is not as the media preferred theme.

I checked the source code of the "[Svelte Material UI](https://sveltematerialui.com/)" site it did not implement a local store.

so is there a way to add await or block to prevent the flicker.

**Comment by NickantX** [comment]
The best solution I can think of is to use cookies instead of local storage to store the user's selected theme. This way, the user's selected theme will be available during SSR and you will avoid that flash of incorrectly styled content.

**Comment by msh2050** [comment]
thanks a lot, that is what I did and it works like charm. I am shocked how the site is loading without any flickering...
I depend on this [repo](https://github.com/jmagrippis/with-svelte) 
I think the sample site should be updated to use this method
