### ISSUE TITLE
Chip action submits the parent form

### ISSUE THREAD

**Issue by amccausl** [hperrin/svelte-material-ui#456]
**Describe the bug**
When the chip is under a form, it will submit the parent form on action

**To Reproduce**
1. Add component to a page
2. Click on the `x` for one of the chips
3. Console displays submit

```svelte
<script>
let chips = [ "1", "2", "3" ]

function handleSubmit() {
  console.info("submit code should not be run")
}

function handleRemove(event) {
  console.info("code here is not important")
}
</script>

<form on:submit|preventDefault={handleSubmit}>
  <ChipSet chips={chips} let:chip input>
    <Chip {chip} shouldRemoveOnTrailingIconClick={false} on:MDCChip:trailingIconInteraction={handleRemove}>
      <Text>{chip}</Text>
      <TrailingAction icon$class="material-icons">cancel</TrailingAction>
    </Chip>
  </ChipSet>
</form>
```

**Expected behavior**
should not print "submit code should not be run"

**Comment by hperrin** [comment]
Fixed with merge https://github.com/hperrin/svelte-material-ui/commit/5b37ea7a733cb8da999f54b7de25162c969ceba7
