### ISSUE TITLE
is that possible to have a clean output , with no warning, when executing npm run prepare ?

### ISSUE THREAD

**Issue by regnou** [hperrin/svelte-material-ui#482]
# is that possible to have a clean output , with no warning, when executing npm run prepare ?

> smui-theme compile static/smui-dark.css -i src/theme/dark

Compiling SMUI Styles...
WARNING: both $level and $color are required; received $level: '0', $color: ''
    node_modules/@material/elevation/_elevation-theme.scss 234:5   -shadow()
    node_modules/@material/elevation/_elevation-theme.scss 466:20  resolver()
    node_modules/@material/tokens/_resolvers.scss 5:11             -material-elevation()
    node_modules/@material/elevation/_elevation-theme.scss 426:21  with-resolver()
    node_modules/@material/banner/_banner-theme.scss 437:3         -banner-elevation()
    node_modules/@material/banner/_banner-theme.scss 154:3         theme-styles()
    node_modules/@material/banner/_banner.scss 63:5                core-styles()
    node_modules/@material/banner/styles.scss 25:1                 @use
    node_modules/@smui/banner/_style.scss 1:1                      @use
    node_modules/smui-theme/_style.scss 2:1                        @use
    node_modules/smui-theme/_index.scss 2:1                        root stylesheet

Writing CSS to static/smui-dark.css...

**Comment by igorsantos07** [comment]
What's the solution to this @regnou? I'm facing this as well, right after `npm i -D @smui/banner`... No clue what's going on, and debugging MD internals is a bit daunting.

@hperrin Is something special needed when including the banner and using a custom theme as instructed in the SMUI docs?
