### ISSUE TITLE
i don t understand the setup with directories in readme.md

### ISSUE THREAD

**Issue by regnou** [hperrin/svelte-material-ui#483]
In the readme, theses lines are following. I am understanding, that you generate an ouput file here : `build/smui.css`, but then you do an import here: `/static/smui.css`

Is taht normal to have buid and static directories ? Or should it be the same directory ?

STEP 1 - 
"prepare": "npm run smui-theme-light && npm run smui-theme-dark",
"smui-theme-light": "smui-theme compile build/smui.css -i src/theme",
"smui-theme-dark": "smui-theme compile build/smui-dark.css -i src/theme/dark",
Now run npm run prepare to build the CSS file(s), then add it/them on your page. Something like this, adjusting the paths as needed.

STEP 2 - 

<link rel="stylesheet" href="/static/smui.css" />

--
--

I  am now using sveltkit and I have this error using this material lib:
`The request url "/Users/yo/0HOME/0GARAGE/6-PROJECT/build/smui.css" is outside of Vite serving allow list.`

Do you know to solve this error ?

**Comment by jwsinner** [comment]
1. Install packages you want to use e.g. `npm i -D @smui/button`
2. Run `npx smui-theme template src/theme`
3. Add the following to `package.json`:
```
"prepare": "svelte-kit sync && npm run smui-theme-light && npm run smui-theme-dark",
"smui-theme-light": "smui-theme compile static/smui.css -i src/theme",
"smui-theme-dark": "smui-theme compile static/smui-dark.css -i src/theme/dark"
```
4. Add this `<link rel="stylesheet" href="/smui.css" />` (if not using dark theme) or this
 ```
<link rel="stylesheet" href="/smui.css" media="(prefers-color-scheme: light)" />
<link
  rel="stylesheet"
  href="/smui-dark.css"
  media="screen and (prefers-color-scheme: dark)"
/>
```
to the `head` section of `src/app.html`
5. Run `npm run prepare` then `npm run dev` to start the application.

Step 2 creates the theme files in your `src` directory that you an edit. `npm run prepare` then uses that theme to generate `static/smui.css`.

**Comment by regnou** [comment]
thanks you

new error:
```
/Users/yo/0HOME/0GARAGE/6-tinax-2/node_modules/@smui/drawer/src/Scrim.svelte:17:14 Unexpected token
/Users/yo/0HOME/0GARAGE/6-tinax-2/node_modules/@smui/list/src/Separator.svelte:20:14 Unexpected token
/Users/yo/0HOME/0GARAGE/6-tinax-2/node_modules/@smui/icon-button/src/IconButton.svelte:67:14 Unexpected token
/Users/yo/0HOME/0GARAGE/6-tinax-2/node_modules/@smui/icon-button/src/IconButton.svelte:67:14 Unexpected token (x2)
/Users/yo/0HOME/0GARAGE/6-tinax-2/node_modules/@smui/drawer/src/Scrim.svelte:17:14 Unexpected token
 15 |  
 16 |  <script lang="ts">
 17 |    import type { SvelteComponentDev } from 'svelte/internal';
                     ^
 18 |    import { get_current_component } from 'svelte/internal';
 19 |    import type { ActionArray } from '@smui/common/internal';
/Users/yo/0HOME/0GARAGE/6-tinax-2/node_modules/@smui/drawer/src/Scrim.svelte:17:14 Unexpected token
 15 |  
 16 |  <script lang="ts">
 17 |    import type { SvelteComponentDev } from 'svelte/internal';
                     ^
 18 |    import { get_current_component } from 'svelte/internal';
 19 |    import type { ActionArray } from '@smui/common/internal';
3:59:59 PM [vite] ✨ new dependencies optimized: @material/banner, @material/dom, @material/ripple
3:59:59 PM [vite] ✨ optimized dependencies changed. reloading


```

I am sorry for not being precise in my error analisis, but, I often have issues when using smui. I am using the last version of sveltkit, and it uses vite, and I don t know, why this error in node module exists ?

**Comment by jwsinner** [comment]
I can't reproduce these issues, so if you could put your project (or a similar one with the same issues) in a public repo, I'll take a look at it.

**Comment by regnou** [comment]
<img width="711" alt="image" src="https://user-images.githubusercontent.com/978518/178488014-e13c4b6e-eb71-4af9-bca3-84eeac9bfcf3.png">

i am starting another project, i dont understand, where to you import the scss files ?
