### ISSUE TITLE
Add prefix and suffix to text area

### ISSUE THREAD

**Issue by moshe5745** [hperrin/svelte-material-ui#485]
In the current situation we cant use the prefix and suffix attributes like in regular text field.

It would be nice if we could.

**Comment by hperrin** [comment]
There are prefix and suffix demos on the demo site:

https://sveltematerialui.com/demo/textfield/

**Comment by hperrin** [comment]
I see what you mean about textarea, but this would have to be something the upstream library supports. You can direct this feature request here:

https://github.com/material-components/material-components-web
