### ISSUE TITLE
href support for Tab?

### ISSUE THREAD

**Issue by MennoAret** [hperrin/svelte-material-ui#50]
Hi,

First of all, great project! I just started to us this library in my project. How can I make a normal hyperlink in a Tab within a Tabbar. I would like to do this:
`
<TabBar tabs={buttons} let:tab bind:active>
	<Tab {tab} href={tab.path}>
		<Label>{tab.label}</Label>
	</Tab>
</TabBar>`
But the click will not work.
In the svelte code for Tab I see a button element is being created but no a element.
Hopefully someone can point me in the good direction.
Thanks in advance.

Regards,
Menno Aret

**Comment by MintyMods** [comment]
Hi @MennoAret,

What use case do you have for wanting a href? The [HREF](https://www.w3schools.com/tags/att_href.asp) attribute is not part the [MDC Tab](https://github.com/material-components/material-components-web/tree/master/packages/mdc-tab) component and usually links to an external resource.

I assume you are asking as it is not clear how to use the tab component in terms of showing and hiding content _( I struggled with this when first using them)_. 

II think the [MDC Tab](https://github.com/material-components/material-components-web/tree/master/packages/mdc-tab) component has no attached content and works simply as visual toolbar. SMUI tabbar has an active tab property you can use to show and hide the tab content as you wish ([see the following example](https://svelte.dev/repl/119cccc65fdd4eff8ddb90500d7485f5?version=3.15.0)) or you can listen to the [onClick event](https://svelte.dev/repl/4daeb5c501cb42f69a41f24e9289db46?version=3.15.0) to decide.

Does this give you what you need or do you specifically want to use a href?

**Comment by jsessink** [comment]
I came across this when searching for issues surrounding href/goto handling with the Tabs component as well.  For me, it acted really funk when using the click binding on a Tab (which is called out in the MDC Tab component as legitimate).  

I'm not sure if the OP meant to have his routing be handled in a sub slot, as shown in [Sapper's docs](https://sapper.svelte.dev/docs#Nested_routes), however I believe that to be a very valid use case for this component.

Here's what happens with using href that is now on the component itself:
![tabs-active](https://user-images.githubusercontent.com/2416081/108942825-4b09e180-761d-11eb-8f33-5952e1342364.gif)

I assumed using a writable on the $activeTab would suffice, but it looks like the TabBar built-in methods must be overriding it somehow (I honestly didn't look). 

```svelte
    <TabBar
      tabs={tabs}
      let:tab
      key={tab => tab.k}
      bind:active={$activeTab}
    >
      <Tab
        {tab}
        href={tab.path}
      >
        <Icon class="material-icons">{tab.icon}</Icon>
        <Label>{tab.label}</Label>
      </Tab>
    </TabBar>

    <slot></slot>
    
<script lang="ts">
  interface Tab {
    k     : number;
    icon  : string;
    label : string;
    path  : string;
  };

  const tabs: Tab[] = [
    {
      k: 0,
      icon: 'access_time',
      label: 'Account',
      path: '/i/settings/account'
    },
    {
      k: 1,
      icon: 'near_me',
      label: 'Profile',
      path: '/i/settings/profile'
    }
  ];
  let activeTab = writable(activeTabFinder());

  function activeTabFinder(): Tab {
    const tab = tabs.find(u => u.path === $page.path);
    return tabs[tab.k] || tabs[0];
  }
</script>
```

I also tried using a more native on:click of the <Tab> component itself with a goto Sapper method - same result as above.

I ended up resorting to overwriting the classlist entirely after it gets triggered and it appears to work well now:
![tabs-active2](https://user-images.githubusercontent.com/2416081/108943321-30843800-761e-11eb-925a-bb0d2a13bc2a.gif)


```svelte
    <TabBar
      tabs={tabs}
      let:tab
    >
      <Tab
        {tab}
        class={tab.path === $page.path ? `tab-bar__tab tab--actually-active` : `tab-bar__tab`}
        aria-selected={tab.path === $page.path}
        on:click={navigateAndUpdateTab(tab)}
      >
        <Icon class="material-icons">{tab.icon}</Icon>
        <Label>{tab.label}</Label>
      </Tab>
    </TabBar>

    <slot></slot>
    
<script lang="ts">
  interface Tab {
    k     : number;
    icon  : string;
    label : string;
    path  : string;
  };

  const tabs: Tab[] = [
    {
      k: 0,
      icon: 'access_time',
      label: 'Account',
      path: '/i/settings/account'
    },
    {
      k: 1,
      icon: 'near_me',
      label: 'Profile',
      path: '/i/settings/profile'
    }
  ];

  onMount(() => {
    updateClassesOfTabsManually();
  });

  function updateClassesOfTabsManually() {
    const tabList = document.getElementsByClassName('tab-bar__tab');

    for (let i = 0; i < tabList.length; i++) {
      const tab = tabList[i];
      let isActuallyActive = false;

      tab.classList.forEach(u => {
        if (u === 'tab--actually-active') {
          return isActuallyActive = true;
        }
      });

      if (isActuallyActive) {
        tab.classList.add('mdc-tab--active');
        tab.querySelector('.mdc-tab-indicator').classList.add('mdc-tab-indicator--active');
      } else {
        tab.classList.remove('mdc-tab--active');
        tab.querySelector('.mdc-tab-indicator').classList.remove('mdc-tab-indicator--active');
      }
    }
  }

  async function navigateAndUpdateTab(tab: Tab) {
    await goto(tab.path);

    // bleh
    updateClassesOfTabsManually();
  }
</script>
```


Anyway, there is still probably a better way to handle this, but I honestly couldn't find a proper result and this is just what I came up with.  I'm hoping someone can follow up with a better solution to these nested routes with tabs.   Leaving this here in case someone finds it of use, however.

**Comment by hperrin** [comment]
Oh, this is done now. :)
