### ISSUE TITLE
segmented-button is reporting a syntax error.

### ISSUE THREAD

**Issue by michaelcuneo** [hperrin/svelte-material-ui#500]
**Describe the bug**
segmented-button is reporting a syntax error.

**To Reproduce**
npm i @smui/segmented-button --save-dev
npm run prepare
npm run dev -- --host --port 3000

Implement segmented-button.

Uncaught SyntaxError: The requested module '/node_modules/@material/segmented-button/dist/mdc.segmentedButton.js?v=963b7288' does not provide an export named 'MDCSegmentedButtonFoundation' (at SegmentedButton.svelte? [sm]:28:18)

**Expected behavior**
Functional Buttons

**Comment by hperrin** [comment]
This is basically a two bad ways to do it situation, because the upstream segmented button package.json is broken. Are you able to pin it to v6.1.1 until v7 comes out?

**Comment by michaelcuneo** [comment]
Ahh, so just throw an @material/segmentedbutton: "v6.1.1" and rm -r node_modules package-lock.json | npm i @material/segmentedbutton...

**Comment by michaelcuneo** [comment]
I've just got back to the office to have a play around with this, and it's not working.

I tried adding @material/segmented-button: v6.1.1 to the config, and no such version exists, so I figured maybe you meant your @smui/segmented-button to v6.1.1 so I reinstalled, and it's still dead.

@smui/segmented-button: v6.1.1 still breaks. I tried clamping to v6.0.0 and it's still broken.

**Comment by shadowempire123** [comment]
Having the same problem...

**Comment by michaelcuneo** [comment]
@shadowempire123 I fixed it eventually... it seems that 6.1.1 is missing and won't install... if it is still in existence my computer is being crap and won't find it... so I just went one lower, and ran `npm i @smui/segmented-button@v6.0.0 -D` ... and everything is back to normal.

**Comment by shadowempire123** [comment]
@michaelcuneo, thx that works for me!

**Comment by hperrin** [comment]
I believe I've figured out how to fix this permanently.
