### ISSUE TITLE
`svelte-kit sync` now runs on "postinstall" — please remove it from your "prepare" script

### ISSUE THREAD

**Issue by w3rafu** [hperrin/svelte-material-ui#507]
**Describe the bug**
Followed documentation to use SMUI on current svelte kit version. 

**To Reproduce**
npm run prepare

> svelte-cvcard@0.0.1 prepare
> svelte-kit sync && npm run smui-theme-light && npm run smui-theme-dark

**error**
`svelte-kit sync` now runs on "postinstall" — please remove it from your "prepare" script
Error: Cannot find module '@material/dom/package.json'

[log.txt](https://github.com/hperrin/svelte-material-ui/files/9498714/log.txt)

**Comment by NickantX** [comment]
As the first error says, you can remove the `svelte-kit sync &&` portion from your `prepare` script if you are using a newer version of SvelteKit. This was necessary for previous versions but Svelte has changed how syncing is handled now.
For your other issue, please make sure you have at least one SMUI component installed in your project before running `smui-theme`. If you're still having issues, please try removing your node_modules folder and re-installing your dependencies. If that doesn't fix it, please post your package.json

**Comment by w3rafu** [comment]
Thanks!
