### ISSUE TITLE
When upgrade:  No matching version found for @smui/common@^6.1.4

### ISSUE THREAD

**Issue by kuchaguangjie** [hperrin/svelte-material-ui#515]
**Describe the bug**
When upgrade dependencies, got error:
```
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @smui/common@^6.1.4

This error happened while installing the dependencies of @smui/button@6.1.4

The latest release of @smui/common is "6.1.0".

If you need the full list of all 60 published versions run "$ pnpm view @smui/common versions".
```

**Comment by kuchaguangjie** [comment]
I'm using `pnpm`, it used to work.

**Comment by hperrin** [comment]
That seems like a bug in pnpm. There is definitely a `@smui/common` 6.1.4 package:
https://www.npmjs.com/package/@smui/common

**Comment by kuchaguangjie** [comment]
Maybe, but I don't see error when upgrade other dependencies.

**Comment by hperrin** [comment]
I don't even know how I would fix that. NPM shows there are 61 versions, so there must be some cache pnpm is using that is behind. I'm going to go ahead and close it, because there's nothing I can do.

**Comment by kuchaguangjie** [comment]
Turns out it's the mirror's problem, there mirror's latest version was `6.1.0`, that's the problem.
Luckly, the mirror provides a `sync missing` feature, and I synced the mirror by hand:

https://npmmirror.com/sync/@smui/common?spm=a2c6h.24755359.0.0.41bb40d11qcutz#logid=63379f0f0012f97934db68da

Then it all worked.

It's not smui or pnpm's problem ..
