### ISSUE TITLE
Select 'enhanced' component fails against Svelte 3.13.alpha.2

### ISSUE THREAD

**Issue by MintyMods** [hperrin/svelte-material-ui#52]
Hi Hunter,

I am not sure if this issue should be directed at @SMUI or Svelte so have raised issues against both. Excuse me if this is nothing to do with your component directly. 

At the request of the Svelte team I recently upgraded to the @next version of Svelte (^3.13.0-alpha.2) and this seems to break the `enhanced` version of the `Select` component in that it no longer displays a menu when clicked.

- Repl [showing the issue](https://svelte.dev/repl/4d04ea22706649d8b45fc226e35b9a62?version=3.13.0-alpha.2) against 3.13.0.-alpha.2
- Same Repl [working ](https://svelte.dev/repl/4d04ea22706649d8b45fc226e35b9a62?version=3.13.0-alpha.1)against 3.13.0.aplha.1
- Same Repl [working](https://svelte.dev/repl/4d04ea22706649d8b45fc226e35b9a62?version=3.12.1) against 3.12.1.

The menu seems to initially open:-

![image](https://user-images.githubusercontent.com/2349765/67628333-54354380-f85b-11e9-8fad-ca1b97bb4124.png)

Before being removed by flush():-

![image](https://user-images.githubusercontent.com/2349765/67628350-baba6180-f85b-11e9-9166-305e9ebec238.png)

I noticed that even after removal of the menu the `onclose` callback is not fired until clicking the body so the component seems to think it is still active.

Can you please review as this incoming change breaks my usage of Select controls.

Thanks

**Comment by Conduitry** [comment]
I suspect this is a bug in SMUI that was relying on buggy behavior in Svelte. See my comment [here on the Svelte issue](https://github.com/sveltejs/svelte/issues/3800#issuecomment-546658606).

**Comment by REDVM** [comment]
Hi.
I don't know if it's relevant but I had a similar problem: when clicking on a button, the menu does not show up, even with the demo example at https://github.com/hperrin/svelte-material-ui/blob/master/site/src/routes/demo/menu.svelte.

One quick & dirty solution was to add that to Menu.svelte:
`<svelte:options accessors={true}/>`

And in my code to replace
`<Button on:click={() => menu.setOpen(true)}>Click to open the menu</Button>`
by 
`<Button on:click={() => menu.open=true}>Click to open the menu</Button>`

**Comment by MintyMods** [comment]
Thanks @REDVM,

While your suggestion didn't fix the issue with the `selects` it did point me in the right direction to trouble shoot and find the bug which turned out to be a simple typo in:-

`node_modules\@smui\menu-surface\MenuSurface.svelte`

Where the open class was being added based on the is static variable:-

` class:mdc-menu-surface--open={isStatic}`

Corrected to use:-

` class:mdc-menu-surface--open={open}`

And this fixes the issue for the Selects.

I suspect this suggested fix will also resolve your specific use case with the menus.

**Comment by hperrin** [comment]
I kinda took a chainsaw approach to solving this instead of a scalpel, since I don't want it coming back in super hard to track ways. Basically I removed all "class:" directives. This should keep Svelte's new code from touching the classes unless some exported option that's used in classes specifically changes.
