### ISSUE TITLE
Failed to install data-table package

### ISSUE THREAD

**Issue by beckren** [hperrin/svelte-material-ui#526]
**Describe the bug**
cloned https://github.com/hperrin/smui-example-sveltekit and ran npm install.
attempts to install the data-table package via "npm i -D @smui/data-table" into an existing project fail with error message:

Error: Undefined mixin.
    ╷
145 │ ┌     @include ripple-theme.states-background-selector(
146 │ │       list-variables.$deprecated-ripple-target
147 │ │     ) {
148 │ │       @include feature-targeting.targets($feat-color) {
149 │ │         opacity: $opacity;
150 │ │       }
151 │ └     }
    ╵
  node_modules/@material/menu/_mixins.scss 145:5  open-item-opacity()
  node_modules/@material/menu/_mixins.scss 58:5   core-styles()
  node_modules/@material/menu/mdc-menu.scss 24:1  @use
  node_modules/@smui/menu/_style.scss 1:1         @use
  node_modules/@smui/select/_style.scss 7:1       @use
  node_modules/@smui/data-table/_style.scss 3:1   @use
  node_modules/smui-theme/_style.scss 8:1         @use
  node_modules/smui-theme/_index.scss 2:1         root stylesheet

**Comment by xpcn2015** [comment]
The example project used smui packages version 6
and now the latest packages version is 7

you can update smui packages in example project to latest:
`npm i -D @smui/icon-button@latest @smui/top-app-bar@latest @smui/button@latest`

or use data-table version 6:
`npm i -D @smui/data-table@6.0.0`

**Comment by beckren** [comment]
That worked, many thanks for your help!
