### ISSUE TITLE
SvelteKit Warning for Card Component

### ISSUE THREAD

**Issue by jdgamble555** [hperrin/svelte-material-ui#527]
**Describe the bug**
I am using the latest version of SvelteKit.  When I compile, I get these warnings:

```sql
7:58:38 PM [vite-plugin-svelte] C:/web projects/my-project/node_modules/@smui/card/dist/PrimaryAction.svelte:1:0 
A11y: noninteractive element cannot have positive tabIndex value
7:58:41 PM [vite-plugin-svelte] C:/web projects/my-project/node_modules/@smui/card/dist/PrimaryAction.svelte:1:0 
A11y: noninteractive element cannot have positive tabIndex value
```
J

**Comment by jdgamble555** [comment]
Getting this for `chips` component too:

```sql
9:02:47 PM [vite-plugin-svelte] C:/web projects/code-build-new/node_modules/@smui/chips/dist/Text.svelte:13:4
 A11y: noninteractive element cannot have positive tabIndex value
9:02:47 PM [vite-plugin-svelte] C:/web projects/code-build-new/node_modules/@smui/card/dist/PrimaryAction.svelte:1:0
 A11y: noninteractive element cannot have positive tabIndex value
9:02:50 PM [vite-plugin-svelte] C:/web projects/code-build-new/node_modules/@smui/card/dist/PrimaryAction.svelte:1:0
 A11y: noninteractive element cannot have positive tabIndex value
9:02:50 PM [vite-plugin-svelte] C:/web projects/code-build-new/node_modules/@smui/chips/dist/Text.svelte:13:4
 A11y: noninteractive element cannot have positive tabIndex value
```

J

**Comment by flpms** [comment]
I've some similar problem, with cards using version 6.1.0
``` bash
A11y: noninteractive element cannot have nonnegative tabIndex value (1:0)
1: <div
   ^
2:   bind:this={element}
3:   use:useActions={use}
 @ ./node_modules/@smui/card/dist/index.js 4:0-60 6:22-44
```

And looking deeper, it's seems PrimaryAction has this tabindex may they shouldn't
``` javascript
import type Component from './PrimaryAction.svelte';

export declare class PrimaryActionComponentDev extends Component {
  /**
   * @private
   * For type checking capabilities only.
   * Does not exist at runtime.
   * ### DO NOT USE!
   */
  $$prop_def: Omit<
    Partial<svelte.JSX.HTMLAttributes<HTMLDivElement>>,
    'use' | 'class' | 'style' | 'ripple' | 'color' | 'padded' | 'tabindex'
  > &
    Component['$$prop_def'];
}
```

**Comment by kbuffington** [comment]
`Icon` seems to generate it for me as well:
```
[vite-plugin-svelte] /node_modules/@smui/textfield/dist/icon/Icon.svelte:1:0 A11y: noninteractive element cannot have nonnegative tabIndex value
```

**Comment by hperrin** [comment]
This seems more like a SvelteKit issue, because non-interactive elements absolutely can have positive tabindexes. That's how you make them interactive.

**Comment by jdgamble555** [comment]
@hperrin - Yes, but the warning is built into Svelte for a reason, as it is considered bad practice.  Svelte usually handles tab indexes automatically.

https://kit-docs-demo.vercel.app/docs/accessibility/warnings#a11y-positive-tabindex

So, you should remove it from this package.

J

**Comment by kbuffington** [comment]
For the warnings I'm seeing with `Icon` inside a `TextField`, the tabIndex is -1 in the browser, so not sure if that's changing at some point after initial page load or not.

**Comment by hperrin** [comment]
> @hperrin - Yes, but the warning is built into Svelte for a reason, as it is considered bad practice.  Svelte usually handles tab indexes automatically.
> 
> https://kit-docs-demo.vercel.app/docs/accessibility/warnings#a11y-positive-tabindex
> 
> So, you should remove it from this package.
> 
> J

I think there may have been some confusion on my part. To me, 0 is a positive integer (because -0 exists in JS), so the error seemed like it was complaining that I set tabindex to 0. SMUI never (by itself) sets tabindex to anything other than -1 or 0. It does let the user set it to whatever they want, but the default is never above 0.

**Comment by jdgamble555** [comment]
@hperrin - Any updates on fixing this? Still getting warnings...

```ts
9:30:00 PM [vite-plugin-svelte] /node_modules/@smui/card/dist/PrimaryAction.svelte:1:0 A11y: noninteractive element cannot have nonnegative tabIndex value
9:30:00 PM [vite-plugin-svelte] /node_modules/@smui/chips/dist/Text.svelte:13:4 A11y: noninteractive element cannot have nonnegative tabIndex value
9:30:00 PM [vite-plugin-svelte] /node_modules/@smui/tab-bar/dist/TabBar.svelte:1:0 A11y: Elements with the 'tablist' interactive role must have a tabindex value.
```

J

**Comment by hperrin** [comment]
I'm actually currently working in this. :D I've fixed it, but I haven't committed the fix yet. Should be out within a day or two. I'm trying to fix all the warnings for the next beta release.

**Comment by hperrin** [comment]
The fix is really dumb. xD I just took these props out and put them in an object that I spread onto the element. Such is life.
