### ISSUE TITLE
Svelte Preprocess scss doesnt play nice with components postcss

### ISSUE THREAD

**Issue by northkode** [hperrin/svelte-material-ui#54]
I still need to use a preprocesser so that I can use scss in my svelte components view

`<style type="text/scss"></style>`

by adding the scss to my rollup it breaks the material ui components 

```
import {scss, postcss} from "svelte-preprocess";
```

```
scss({}),
postcss({
      extract: true,
      minimize: true,
      use: [
           [
                 "sass",
                 {
                     includePaths: ["./theme", "./node_modules"]
                 }
            ]
       ],
      plugins: [require("autoprefixer")]
 })
```

The Error is the same one other people are having which is the 

`Unexpected Character '@' @import "smui-theme";`

**Comment by MintyMods** [comment]
Does the [configuration](https://github.com/hperrin/svelte-material-ui/issues/36#issuecomment-544289545) mentioned in the comment help?

**Comment by northkode** [comment]
@MintyMods i'm not currently using sapper, I could try and take bits out, but I have not done so yet. 
Was assuming that someone has had success with a basic rollup config

Here is my full config atm

```
import {scss, postcss} from "svelte-preprocess";
import svelte from "rollup-plugin-svelte";
import resolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";
import livereload from "rollup-plugin-livereload";
import {terser} from "rollup-plugin-terser";
import builtins from "rollup-plugin-node-builtins";
import replace from "rollup-plugin-replace";
import progress from "rollup-plugin-progress";
import html from "rollup-plugin-bundle-html";
import alias from "rollup-plugin-alias";

import url from "rollup-plugin-url";
const production = !process.env.ROLLUP_WATCH;

export default {
    input: "src/index.js",
    output: {
        sourcemap: true,
        format: "iife",
        name: "app",
        file: "public/bundle.js"
    },
    plugins: [
        alias({
            "@assets": __dirname + "/src/assets",
            "@utils": __dirname + "/src/utils",
            "@API": __dirname + "/src/utils/API.js",
            "@Store": __dirname + "/src/utils/Store.js"
        }),
        url({
            limit: 10 * 1024,
            fileName: "[dirname][hash][extname]",
            sourceDir: "src"
        }),
        progress({clearLine: true}),
        builtins(),
        replace({
            PRODUCTION: production
        }),
        svelte({
            extensions: [".sa", ".svelte"],
            preprocess: [
                scss({}),
                postcss({
                    extract: true,
                    minimize: true,
                    use: [
                        [
                            "sass",
                            {
                                includePaths: ["./theme", "./node_modules"]
                            }
                        ]
                    ],
                    plugins: [require("autoprefixer")]
                })
            ],
            dev: !1,
            css: o => {
                o.write("public/bundle.css");
            }
        }),

        // If you have external dependencies installed from
        // npm, you'll most likely need these plugins. In
        // some cases you'll need additional configuration —
        // consult the documentation for details:
        // https://github.com/rollup/rollup-plugin-commonjs
        resolve({
            browser: true,
            dedupe: importee =>
                importee === "svelte" || importee.startsWith("svelte/")
        }),
        commonjs(),

        // Watch the `public` directory and refresh the
        // browser on changes when not in production
        !production && livereload("public"),

        // If we're building for production (npm run build
        // instead of npm run dev), minify
        production && terser()
    ],
    watch: {
        clearScreen: false
    }
};

```
Error:
```
node_modules/@smui/data-table/_index.scss (1:0)
1: @import "smui-theme";
   ^
```

**Comment by hengnee** [comment]
> @MintyMods i'm not currently using sapper, I could try and take bits out, but I have not done so yet.
> Was assuming that someone has had success with a basic rollup config
> 
> Here is my full config atm
> 
> ```
> import {scss, postcss} from "svelte-preprocess";
> import svelte from "rollup-plugin-svelte";
> import resolve from "rollup-plugin-node-resolve";
> import commonjs from "rollup-plugin-commonjs";
> import livereload from "rollup-plugin-livereload";
> import {terser} from "rollup-plugin-terser";
> import builtins from "rollup-plugin-node-builtins";
> import replace from "rollup-plugin-replace";
> import progress from "rollup-plugin-progress";
> import html from "rollup-plugin-bundle-html";
> import alias from "rollup-plugin-alias";
> import path from "path";
> 
> import url from "rollup-plugin-url";
> const production = !process.env.ROLLUP_WATCH;
> 
> const postcssOptions = () => ({
>   extensions: [".scss", ".sass"],
>   extract: false,
>   minimize: true,
>   plugins: [require("autoprefixer")],
>   use: [
>     [
>       "sass",
>       {
>         includePaths: [
>           "./src/theme",
>           "./node_modules",
>           // This is only needed because we're using a local module. :-/
>           // Normally, you would not need this line.
>           path.resolve(__dirname, "..", "node_modules")
>         ]
>       }
>     ]
>   ]
> });
> 
> export default {
>     input: "src/index.js",
>     output: {
>         sourcemap: true,
>         format: "iife",
>         name: "app",
>         file: "public/bundle.js"
>     },
>     plugins: [
>         alias({
>             "@assets": __dirname + "/src/assets",
>             "@utils": __dirname + "/src/utils",
>             "@API": __dirname + "/src/utils/API.js",
>             "@Store": __dirname + "/src/utils/Store.js"
>         }),
>         url({
>             limit: 10 * 1024,
>             fileName: "[dirname][hash][extname]",
>             sourceDir: "src"
>         }),
>         progress({clearLine: true}),
>         builtins(),
>         replace({
>             PRODUCTION: production
>         }),
>         svelte({
>             extensions: [".sa", ".svelte"],
>             preprocess: [
>                 scss({}),
>             ],
>             dev: !1,
>             css: o => {
>                 o.write("public/bundle.css");
>             }
>         }),
> 
>         postcss(postcssOptions()),
> 
>         // If you have external dependencies installed from
>         // npm, you'll most likely need these plugins. In
>         // some cases you'll need additional configuration —
>         // consult the documentation for details:
>         // https://github.com/rollup/rollup-plugin-commonjs
>         resolve({
>             browser: true,
>             dedupe: importee =>
>                 importee === "svelte" || importee.startsWith("svelte/")
>         }),
>         commonjs(),
> 
>         // Watch the `public` directory and refresh the
>         // browser on changes when not in production
>         !production && livereload("public"),
> 
>         // If we're building for production (npm run build
>         // instead of npm run dev), minify
>         production && terser()
>     ],
>     watch: {
>         clearScreen: false
>     }
> };
> ```
> 
> Error:
> 
> ```
> node_modules/@smui/data-table/_index.scss (1:0)
> 1: @import "smui-theme";
>    ^
> ```

Have you tried using this instead?
```js
svelte({
      preprocess: autoPreprocess({ postcss: true }),
```

**Comment by csaltos** [comment]
If you change extract to false at the postcss and emitCss to false and css to true at the svelte client section it works. Here more info -> https://dev.to/csaltos/sapper-with-material-ui-35id

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
