### ISSUE TITLE
<Switch> on:change does not work

### ISSUE THREAD

**Issue by DetachHead** [hperrin/svelte-material-ui#543]
**Describe the bug**
basically #349 but for `Switch` instead of `Select`. i tried `on:MDCSelect:change` as suggested in that issue but it didn't work.

related: #542

**Comment by KotlinIsland** [comment]
Is this because `Switch` doesn't emit a `change` event?

**Comment by DetachHead** [comment]
epic fail its `on:SMUISwitch:change`

(#542)
