### ISSUE TITLE
snackbar.open() TS issue

### ISSUE THREAD

**Issue by pboguslawski** [hperrin/svelte-material-ui#575]
**Describe the bug**
Typescript marks [`snackbar.open()`](https://sveltematerialui.com/demo/snackbar/) with issue
```
This expression is not callable because it is a 'get' accessor. Did you mean to use it without '()'?
  Not all constituents of type 'NonNullable<boolean | (() => void) | null | undefined>' are callable.
    Type 'false' has no call signatures.
```
(does not break this function and snaskbar opening works fine regardless of this issue).

No such TS issue for `snackbar.close()`.

**To Reproduce**
Run any example with `.open()` from https://sveltematerialui.com/demo/snackbar/ in VSCode + SvelteKit plugin and TS enabled.

**Expected behavior**
No TS issue for `open()` method.

**Comment by hperrin** [comment]
I don't know why it's doing this, and it didn't until recently... hmm...

**Comment by hperrin** [comment]
Oh Jesus Christ. It's because `open` can be an HTML attribute.
