### ISSUE TITLE
Normalise the usage

### ISSUE THREAD

**Issue by ispyinternet** [hperrin/svelte-material-ui#59]
so with Chips...
```
    import Chip, { Set, Icon, Text } from '@smui/chips';
```
but with textfield:
```
    import Textfield, { Input } from '@smui/textfield';
    import Icon from '@smui/textfield/icon/index';
```

should Icon be a named export from @smui/textfield like with chips?

Also not sure of the mechanics behind it but I'm guessing its not simple enough to have one Icon to rule them all?

Kicking the tyres on this hence all the issues / feedback. Hope you don't mind?

**Comment by hperrin** [comment]
This is a complicated question with a complicated answer. Basically, MDC-Web made several different icon requirements, and it's not feasible to have one icon to rule them all, but close.
