### ISSUE TITLE
Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by caschbre** [hperrin/svelte-material-ui#6]
I'm using the [YogliB component template](https://github.com/YogliB/svelte-component-template) as a starter for my svelte project. I was attempting to include svelte-material-ui but am running into a build issue.

```[!] Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
node_modules/svelte-material-ui/components/select/_index.scss (1:0)
1: @import "smui-theme";
   ^
2: @import "./_style.scss";
Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
    at error (/svelte_app/node_modules/rollup/dist/rollup.js:9421:30)
    at Module.error (/svelte_app/node_modules/rollup/dist/rollup.js:13360:9)
    at tryParse (/svelte_app/node_modules/rollup/dist/rollup.js:13275:16)
    at Module.setSource (/svelte_app/node_modules/rollup/dist/rollup.js:13586:33)
    at Promise.resolve.catch.then.then.then (/svelte_app/node_modules/rollup/dist/rollup.js:16412:20)```

I copied the _smui-theme.scss file to my /src folder since that is an included path for the preprocess.  You see see the [rollup config](https://github.com/YogliB/svelte-component-template/blob/master/rollup.config.js) file. I'm assuming because I'm using rollup and not webpack I'm running into the issue but not sure how to resolve it.

Oh, forgot to mention in one of my .svelte files I have the following that triggers the error.

```
<script>
  import Select, { Option } from "svelte-material-ui/components/select";
</script>
```

**Comment by hperrin** [comment]
You'll no longer need the Svelte preprocessor, but you will still need a Sass processor, since MDC components all use Sass. I don't know how to add one to Rollup, so you might want to ask in Rollup's Discord channel. Let me know if you figure it out.

**Comment by caschbre** [comment]
I wasn't tied to Rollup so I ended up switching back over to webpack. If I find time I do want to try to get this loaded with Rollup but deadlines come first. :-)

Thanks for the quick responses!  This package is looking great so far. I had started building my own svelte material combo until I found this one.

**Comment by LaughingBubba** [comment]
Hi, I went in circles trying to get smui working on rollup and parcel. In the end I just cloned the `svelte-webpack` template and used the guidance from your readme. 

I've had some success but it seems that the Material Icons aren't getting imported.
 
![image](https://user-images.githubusercontent.com/1077530/62820324-199a0400-bba6-11e9-97db-55a517e13f19.png)

[my repo replicating the problem](https://github.com/LaughingBubba/svelte-sass-webpack.git)

**Comment by hperrin** [comment]
I'm not loading the material icon font by default, since it's pretty weighty, and people may want to use this without material icons, so you'll have to load the font yourself. Also, anything you want to be an icon, you'll have to put `class="material-icons"`.

**Comment by hperrin** [comment]
I just fixed the example in the readme where I forgot to add that to the icon.

**Comment by LaughingBubba** [comment]
Hmmm ... I think I'm missing something terribly obvious. FYI though, [my example repo replicating the problem](https://github.com/LaughingBubba/svelte-sass-webpack.git) does indeed have `class="material-icons"` on the FAB component. Also none of your examples import the icons.

Isn't the purpose of tree shaking bundlers like webpack, rollup and parcel that only the required references / code are bundled? You've already got `@material` in `node_modules`

Sorry to be pest, I love the work you've done and it's just frustrating no being able to utilize it!

**Comment by LaughingBubba** [comment]
Doh! got this directly from https://google.github.io/material-design-icons/

![image](https://user-images.githubusercontent.com/1077530/62830362-f7a98b80-bc50-11e9-8ab7-48c6230aca9e.png)

Added the stylesheet to my index.html and suddenly the icon buttons etc look and behave as expected.

**Comment by caschbre** [comment]
You can also use [svelte:head](https://svelte.dev/docs#svelte_head) in your App.svelte file. Same goes for the fonts.

```
<svelte:head>
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</svelte:head>
```

**Comment by hperrin** [comment]
@LaughingBubba I'm hoping to release version 1.0 this tomorrow. It depends if I can get snackbars and some documentation done though.

**Comment by hperrin** [comment]
I added a note about the Material Icons font to the readme.

**Comment by yapus** [comment]
> I hit this same issue today. Any chance of adding rollup support in future? I mean just from a documentation point of view.

see https://github.com/rollup/rollup-plugin-svelte/issues/53#issuecomment-491633054

**Comment by hperrin** [comment]
There's a link to a working Rollup config in the readme.

**Comment by rotimi-best** [comment]
> There's now a link to a working Rollup config in the readme.

Where? Can't find any
