### ISSUE TITLE
get_current_component not compatible with svelte 5

### ISSUE THREAD

**Issue by ragingsquirrel3** [hperrin/svelte-material-ui#648]
**Describe the bug**
smui components are not usable with svelte 5 preview because they depend on internal API get_current_component which apparently is not available in 5.

**To Reproduce**
1. upgrade app with SMUI components to svelte 5 by adding a preview version in package.json
2. run npm install/npm run dev
3. get error `TypeError: __vite_ssr_import_1__.get_current_component is not a function`

**Expected behavior**
I can use SMUI with svelte 5.

**Comment by hperrin** [comment]
I figured this day would come. :P I'm going to have to find a new way to forward all events.

**Comment by hperrin** [comment]
I just finished reading the docs, and it looks like it will actually be easier to forward all the events in Svelte 5 than it was in Svelte <=4. Buuuuut, it will require a large rewrite of a lot of code, so that will be done in v8 of SMUI.

**Comment by hperrin** [comment]
I'm going to track this as #650.
