### ISSUE TITLE
Drawer Feature

### ISSUE THREAD

**Issue by hengnee** [hperrin/svelte-material-ui#65]
From the Drawer component, it is only possible to open from the left.
I was thinking whether the app could be opened from the right?

**Comment by MintyMods** [comment]
This may be a limitation of the [Material Components](https://material.io/components/navigation-drawer/#anatomy)

> The contents of a navigation drawer are contained within a side or bottom sheet. Navigation drawers that open from the side are placed on the left of the screen for left-to-right languages, and on the right of the screen for right-to-left languages.

**Comment by hperrin** [comment]
If MDC-Web adds this feature, I will support it, but I don't have any plans to add it specifically for SMUI.
