### ISSUE TITLE
Flash of unstyled content (FOUC) with Sapper

### ISSUE THREAD

**Issue by ajbouh** [hperrin/svelte-material-ui#66]
Seems like there's something in the Material UI libraries that may be forcing a layout or style recalculation before all CSS has been parsed.

Is this something other people are seeing?

I see this on macOS in Chrome Canary and the latest Firefox. I do not see it in Desktop Safari.

This is definitely happening in dev mode with sapper and may be due to my own webpack configuration failing to include appropriate stylesheets in the SSR version of the page.

But some of my investigations using the chrome profiling tools also implicate `detectEdgePseudoVarBug(...)` in https://github.com/material-components/material-components-web/blob/master/packages/mdc-ripple/util.ts (although probably not the exact version that's on the master branch in that repo).

I've tried disabling the ripple effect on components but I wasn't able to do this completely.

**Comment by jobelenus** [comment]
I am also seeing this, but the Nav and Footer are not flashing.  Just the main content, which is just Paper -> Drawer -> List/Table. Everything inside Paper is flashing, nothing outside of it. I'm working on this every day, happy to work through potential issues.

**Comment by hperrin** [comment]
I do see this too.

**Comment by hperrin** [comment]
@jobelenus Were you able to figure anything out?

**Comment by jobelenus** [comment]
No, I don't think so

**Comment by Vehmloewff** [comment]
This happens because the material scss styles that style the components are included in the js.

Sapper first sends down the small static html and css, and when the larger js files (that have all of `@material`'s compiled sass) load, the html is hydrated.

That is why the non-material elements to not flash.

**Comment by Jan-Kuta** [comment]
Hello,

is some progress on this issue?
Or does exist some workaround which doesn't kill Sapper's SSR feature?

According to this issue [https://github.com/hperrin/svelte-material-ui/issues/29](https://github.com/hperrin/svelte-material-ui/issues/29) some solution might exist (@hperrin maybe knows).

Thank you very much for any advice,
Honza

**Comment by gmanfredi** [comment]
I'm assuming there's been no progress on this?  Any news, ideas?  I am also using svelte-material-ui library with Sapper and getting the FOUC and would love to not have to kill SSR.

**Comment by hperrin** [comment]
I have finally fixed this!!! It took literally all day today!

**Comment by hperrin** [comment]
There are new instructions here, which will let you use SMUI in Sapper without a FOUC:
https://github.com/hperrin/svelte-material-ui#integration-for-sapper

![success-kid](https://user-images.githubusercontent.com/195918/113790207-aab3dc00-96f5-11eb-84bc-6e2d2fe988d1.jpg)

**Comment by hperrin** [comment]
https://sveltematerialui.com/ now no longer has a FOUC when loaded! :D

**Comment by JohanHeyvaert** [comment]
This problem seems to have reappeared? I'm using SvelteKit and smui 7.0.0-beta.0.
It even occurs on the demo site ([https://sveltematerialui.com](url)).

The workaround with onMount() and {#if ready} works though.
