### ISSUE TITLE
Svelte5 @next.174 broke SMUI

### ISSUE THREAD

**Issue by Kapsonfire-DE** [hperrin/svelte-material-ui#662]
![image](https://github.com/hperrin/svelte-material-ui/assets/67053124/6a362e02-1064-40b6-aa34-76c6b7c3ef46)

```html
<TextField input$name="base_url" class="w-full mt-3" variant="outlined" label="Base URL" value={data.website.base_url} />

```

**Comment by Kapsonfire-DE** [comment]
Broke with next.174, works fine with next.173

**Comment by Raphael2b3** [comment]
SMUI - IconButton uses  ` import { get_current_component } from 'svelte/internal';`

doesnt work with `"svelte": "^5.0.0-next.215"` and `"@smui/icon-button": "^7.0.0"`

**Comment by hperrin** [comment]
This appears to be resolved in the latest version. Let me know if you keep seeing this issue.
