### ISSUE TITLE
can't add new tab in TabBar

### ISSUE THREAD

**Issue by ianic** [hperrin/svelte-material-ui#67]
Dynamically added tab to the a TabBar remains un selectable.
This is sample component:

```<script>
 import Tab, {Label} from '@smui/tab';
 import TabBar from '@smui/tab-bar';

 let active;
 let tabs = [1, 2, 3];

 window.addTab = () => {
   tabs = [...tabs, tabs.length + 1]
 };
 $: console.log("active", active);
</script>


<TabBar tabs={tabs} let:tab bind:active={active}>
  <Tab {tab}>
    <Label>{tab}</Label>
  </Tab>
</TabBar>
```

I exposed addTab method so I can call it from console.
When I add new tab by calling addTab it appears but click on it does nothing.

**Comment by 4350pChris** [comment]
Just encountered this issue. Any updates?

**Comment by Krisa** [comment]
@4350pChris thanks this was helpful. Also overwriting the tabs reference didn't work for me (logically), but by using a `tabs.push(...[])`, this finally worked as expected.

**Comment by KevinAst** [comment]
Thanks @4350pChris for your insight on this.  My app also relies on the ability to dynamically add/remove tabs.  Using your promise resolution suggestion, adding tabs is now operational.

With that said, I'm not exactly sure what a Promise.resolve() on an array value is doing.
- It seems like it would resolve immediately.
- I assume this is a work-around hack, and not a long-term solution (from a @smui perspective) ... yes?

I have two REPL samples that show this:
- [Dynamic Tabs](https://svelte.dev/repl/cc860cb4e4ba4298bbcf553135072f76?version=3.23.0) _(with the problem)_
- [Dynamic Tabs with Promise](https://svelte.dev/repl/b4c9bbd80bbb40c7990d47813ea0ea10?version=3.23.0) _(with the fix)_

On an unrelated item, I would like to close the tab when clicking on the "close" icon found in each tab.
- However I cannot get the "on:click" to fire when inside Tab component _(please refer the the REPLs above)_
- Any ideas on this?

Your help is greatly appreciated.

`</Kevin>`

**Comment by dmgolembiowski** [comment]
Additionally, to anyone out there who has struggled with dynamically inserting into sets of chips, the `await` method above shown above also solves this issue.
Thank you, @KevinAst and @4350pChris for demonstrating these solutions.

**Comment by 4350pChris** [comment]
@KevinAst 
I gave it a shot, does this solve your issue?
Set an on:click event on the Tab and then find out if the click was within the icon's boundaries.

[REPL](https://svelte.dev/repl/7bee18e7bc1a450faef9f2278a61d923?version=3.23.0)

```svelte
<script>
  function handleClick(e) {
	const { target, clientX, clientY } = e;
	const icon = target.parentElement.querySelector("i");
	const { left, right, bottom, top } = icon.getBoundingClientRect();
	if (left <= clientX && clientX <= right && top <= clientY && clientY <= bottom) {
		console.log("call your function here");
	}
    }
</script>

<TabBar tabs={tabs} let:tab bind:active={activeTab}>
  <Tab {tab} minWidth on:click="{handleClick}">
    <Label>{tab}</Label>
    <Icon class="material-icons">cancel</Icon>
  </Tab>
</TabBar>
```

**Comment by KevinAst** [comment]
Hello @4350pChris,

Regarding my **SideBar** of _closing a tab from a "close" icon within the tab_ ...  **thank you so much for your time and solution**.  It certainly works, and I will use it _(in a pinch)_!!

With that said, this solution seems to very much be a work-around to a limitation of the SMUI tabs implementation.

Why should it have to be so convoluted to do such a simple task _(no reflection on you)_?  I will grant you that the requirements of "dynamic tabs" may be considered an "edge case", but still ...  all we are trying to do is activate a control within the tab.

Seems like this could be a candidate for a "bug report" or "feature request".

Thanks again for your time and solution ... it is very much appreciated!

`</Kevin>`

**Comment by 4350pChris** [comment]
@KevinAst 
Seems to me that this could be solved by replacing the component the tab renders with anything but a button.
Coincidentally, that's just what pull request #132 does.

**Comment by hperrin** [comment]
Is it the button element that is causing this?

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
