### ISSUE TITLE
[v8.0.0-beta.0][typescript] `value` property marked as not bindable 

### ISSUE THREAD

**Issue by KaiVolland** [hperrin/svelte-material-ui#676]
**Describe the bug**
It seems like the value property of the Select component is not marked as bindable.

When creating a component like the one below `bind:value={value}` will be marked as a problem with this note:

> Cannot use 'bind:' with this property. It is declared as non-bindable inside the component.
To mark a property as bindable: 'let { value = $bindable() } = $props()' ts(2322)

The actually binding works so i guess the problem should be easily fixable when following this note. I'm not sure it this applies to other Inputs aswell.

**To Reproduce**
Create a Component that reuses the Select component. e.g like this:

```svelte
<script lang="ts">
  import Select, { Option } from "@smui/select";
  const options: { value: string, label: string}[] = [];
</script>

<Select
  bind:value={value}
>
  {#each options as option}
    <Option
      value={option.value}
    >
      {option.label}
    </Option>
  {/each}
</Select>
```

**Comment by samausir** [comment]
Seems to be already fixed in beta.2.
