### ISSUE TITLE
Select menus does not work

### ISSUE THREAD

**Issue by iXyles** [hperrin/svelte-material-ui#71]
Select menus does no longer work with the latest versions of Svelte, this started happening from 3.14.0 update.

The Enchanced ones are not showing up at all, whilst the regular ones are showing but without any styling.

Reason: The styling is not completed & finalized, the opacity is stuck at 0 and displayed as "none"

**Comment by MintyMods** [comment]
Linking to #52

**Comment by MintyMods** [comment]
@iXyles The fix is a simple change to the MenuSurface component e.g.

`node_modules\@smui\menu-surface\MenuSurface.svelte`

to use:-

` class:mdc-menu-surface--open={open}`

previously:- 

` class:mdc-menu-surface--open={isStatic}`

Can you confirm this resolves the issue?

**Comment by iXyles** [comment]
Seems to resolve the issue perfectly fine yes :)

**Comment by MintyMods** [comment]
Thank you for the test as your use case is different to mine. 

I have submitted a PR so hopefully it should be fixed within an NPM build soon.

**Comment by hperrin** [comment]
Fixed in https://github.com/hperrin/svelte-material-ui/commit/8a94e95574c36595158603c83b3d79892fe4af4d
