### ISSUE TITLE
Material Icons Not Displaying

### ISSUE THREAD

**Issue by agiveygives** [hperrin/svelte-material-ui#72]
I'm trying to use icon buttons in my app header, pretty much identical to the [Top App Bar demo](https://github.com/hperrin/svelte-material-ui/blob/master/site/src/routes/demo/top-app-bar-iframe.svelte#L4), but the icons are not displaying. Instead it is just showing the text. I haven't been able to find if there is an additional package I need or a webpack config I'm missing, but any help would be appreciated.

![svelte-mui-icons](https://user-images.githubusercontent.com/15256633/69683940-33d7ef00-107c-11ea-9a78-4488224a6d1b.gif)

[Use in my application](https://github.com/agiveygives/api-console/blob/master/src/components/header/header.svelte#L21)

[My Webpack config](https://github.com/agiveygives/api-console/blob/master/webpack.config.js)

**Comment by catchspider2002** [comment]
Can you check if adding the below in the head of template.html displays the icons?

`<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">`

**Comment by agiveygives** [comment]
> Can you check if adding the below in the head of template.html displays the icons?
> 
> `<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">`

Yup, that was it. Thanks!
