### ISSUE TITLE
Upgrade to version 4 of Material Components.

### ISSUE THREAD

**Issue by hperrin** [hperrin/svelte-material-ui#76]
This will be a doozy. Lots of breaking changes.

Changelog:
https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#400-2019-11-02

**Comment by ptone** [comment]
Do you have any sample commits from the June 2->3 breaking changes that demonstrate what kind of changes are needed?

**Comment by hperrin** [comment]
Everything that's breaking should be covered in the changelog. Just updating all the APIs and fixing any new bugs.

**Comment by hperrin** [comment]
There's a whole heap of changes, so it'll probably take a while to upgrade everything.

**Comment by hperrin** [comment]
I started with version 3, so I have no examples of going through a breaking change set.

**Comment by monkeythedev** [comment]
And we arrived at version 7 in the mean time 😂

**Comment by hperrin** [comment]
:P

**Comment by hperrin** [comment]
Ok, so here's my plan. I'm going to release what I have now as version 1.0, then I'll start working on bringing in all the changes from upstream as 2.0.

**Comment by hperrin** [comment]
Closing this since I'm going straight to v10 with the next release.

**Comment by hperrin** [comment]
(And I'm about 3/4 done so far!)
