### ISSUE TITLE
Navigation drawer opening with a swipe from the left

### ISSUE THREAD

**Issue by sanjibukai** [hperrin/svelte-material-ui#78]
Hello,
Is it possible to make the Navigation Drawers opening by swiping from the left border?
This is for example the default behavior on the Navigation Drawers from Vuetify..
[Here (Vuetify doc)](https://vuetifyjs.com/en/components/navigation-drawers) you can test this behavior (works well on mobile) either for the Navigation Drawer of the site itself or for each Drawer demo..

I very like Svelte and I wanted to switch altogether to it, and having a great UI library like this one is a game changer!

Thank you..

**Comment by hperrin** [comment]
This looks like a job for Tinygesture.js.
