### ISSUE TITLE
use with svelte transitions

### ISSUE THREAD

**Issue by ptone** [hperrin/svelte-material-ui#86]
You can't apply thing like transition:fade directly to things like a DataTable Row component

I tried also `<Row tr$transition:fade` but I didn't expect this to work.

wrapping a row in a div throws off the layout

Any thoughts on how to combine with other svelte features like this?

**Comment by ptone** [comment]
looking at https://github.com/hperrin/svelte-material-ui/blob/master/packages/data-table/Row.svelte

I'm guessing it would be something like the way `  use:useActions={use} ` is done?

**Comment by ptone** [comment]
I hacked this by basically forking Row to CustomRow and adding in the in/out attributes there, not perfect, but the result is: https://youtu.be/kRKn9hj1kzc

**Comment by phas0r** [comment]
It would be great to be able to use transitions and animations on all components.

**Comment by hperrin** [comment]
I don't have plans to add this functionality. I'm not sure how I would.
