### ISSUE TITLE
Label wrapping textfields

### ISSUE THREAD

**Issue by caschbre** [hperrin/svelte-material-ui#9]
I noticed that textfields are being [wrapped in the label](https://github.com/hperrin/svelte-material-ui/blob/1.0.0-alpha.9/components/textfield/Textfield.svelte). Is that intended?  I've been trying to debug some styling issues on my end and was looking at the [textfield usage](https://material.io/develop/web/components/input-controls/text-field/) which doesn't have the label wrapping the input.

Here's the outlined variant usage example...

```
<div class="mdc-text-field mdc-text-field--outlined">
  <input type="text" id="tf-outlined" class="mdc-text-field__input">
  <div class="mdc-notched-outline">
    <div class="mdc-notched-outline__leading"></div>
    <div class="mdc-notched-outline__notch">
      <label for="tf-outlined" class="mdc-floating-label">Your Name</label>
    </div>
    <div class="mdc-notched-outline__trailing"></div>
  </div>
</div>
```

**Comment by hperrin** [comment]
It is intentional. You can see an explanation of what it's for on the floating label page:
https://material.io/develop/web/components/input-controls/floating-label/#avoid-dynamic-id-generation

**Comment by caschbre** [comment]
Ah I missed that in the docs.  Thanks!
