### ISSUE TITLE
Unexpected string in @smui/select/index.js

### ISSUE THREAD

**Issue by mercurio** [hperrin/svelte-material-ui#93]
I've added `import Select, {Option} from '@smi/select'` to an existing project and I'm getting 

`../node_modules/@smui/select/index.js:1
import './_index.scss';
       ^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23) ...`

Importing other packages that use identical index.js files, like Button, works just fine. This is a Sapper/webpack app. Any idea what could be going on?

**Comment by mercurio** [comment]
Figured it out: this is the error you get if you `npm install --save @smui/select` instead of `npm install --save-dev @smui/select`. It's tricky, because it will appear to work as long as you're in the same `npm run dev` session. The error doesn't show up until you restart `npm run dev`.

**Comment by melgrove** [comment]
Thank you I couldn't figure this out!
