### ISSUE TITLE
What is the conventional way to style material components

### ISSUE THREAD

**Issue by SwiftWinds** [hperrin/svelte-material-ui#94]
Because Svelte scopes styles, I'm confused on the Clean Way™ to style material components beyond the parameters that you can pass in.

So far, I've only seen adding `style=` to a particular material element and `* :global(.some-class)`, with the particular material elements with class `some-class`.

The global method means that you can accidentally style another element from elsewhere with the same class and the `style=` way is kind of hard to read/maintain.

Is there a cleaner/less hacky way to customize material components’ styles?

**Comment by simonh1000** [comment]
Good question. Based on your question I realised I could use global.css but that's just as hacky! (And I needed to use `!important` - ugh - as well!)

**Comment by tonyketcham** [comment]
Until Svelte adopts a way to tack on or pass classes down to imported components, it seems like any customization of external components will involve some degree of hackiness.

To make it easier for people to customize components, the library could potentially adopt:
- an exported `style` prop for each component to allow inline CSS overrides in the form of JSONified CSS, however I think this could result in some unwarranted bloat
- an exported `class` with this clever trick @GoshaEgorian detailed on [@sveltejs/issues/2870](https://github.com/sveltejs/svelte/issues/2870#issuecomment-631500630) which seems to be the most elegant solution proposed for this kind of thing right now:
```svelte
<script>
  let className = '';
  export {className as class};
</script>

<p class="test {className}">Test</p>
``` 

Besides adding a workaround to the library, you could avoid hacky CSS all together by forking the repo and customizing the components internally for the time being. Although that has the obvious implication of burdening yourself with resolving issues by manually updating your fork against the official repo. 

However, the silver lining of that approach is that it could promote finding and fixing issues on your own which can then be contributed to the project!

**Comment by pspierce** [comment]
Anyone?  I'm trying to figure this out as well.

**Comment by i8ramin** [comment]
Similar question. How does one their custom classes to these components? For example, the following does not seem to work as expected:

```svelte
import Dialog, { Content } from "@smui/dialog";

<style>
.my-content {
  color: red;
}
</style>

<Dialog>
  <Content class="my-content">Hello</Content>
</Dialog>
```

It adds the `my-content` class globally, and not scoped. Is there a right/better way to do this?

```html
<div class="mdc-dialog__content content">Hello</div>
```

**Comment by hperrin** [comment]
There is an answer in the `Common` demos section now. :)
