### ISSUE TITLE
Add link to github component directly from the example page

### ISSUE THREAD

**Issue by Egnus** [hperrin/svelte-material-ui#95]
Hello, this is only a fast suggestion,
it would be a great improvement for everyone to have directly access to the source when we are checking the examples.

For instance in the page:
https://sveltematerialui.com/demo/button

Having a "link to source" button to:
https://github.com/hperrin/svelte-material-ui/blob/master/site/src/routes/demo/button.svelte

It seems not important, but normally the libraries have or the source directly in the page, or a link directly to source so we can understand how the variant we want is built.

Thanks in advance

**Comment by MintyMods** [comment]
@Egnus,

Good suggestion - I find myself always manually 'flicking' between the demos and GitHub sources.

_I can personally take this on and would like to do it, I just can't take it on at the moment._ 

It does sound like a good little challenge so if you or anyone else wants to contribute I am sure the commit would be welcome. 

Gonna chuck a few idea's out for feedback and if no one else contributes I will do so when I get more spare time.

Couple of options exist here:-

- Manually edit each demo page and link to the source via adding a button, icon, hyperlink. 
- Automate it at runtime and inject the button, icon, hyperlink via Javascript (pageload etc)
- Automate it via the build and bake the button, icon, hyperlink (npm)

Each component demo page has a corresponding source page and the naming convention is very consistent so I would try and use that to my advantage:-

```
H:\Development\svelte-material-ui\packages>tree

├───button
├───card
├───checkbox
├───chips
├───common
├───data-table
├───dialog
├───drawer
├───fab
├───floating-label
├───form-field
├───icon-button
├───image-list
├───line-ripple
├───linear-progress
├───list
├───menu
├───menu-surface
├───notched-outline
├───paper
├───radio
├───ripple
├───select
│   ├───helper-text
│   └───icon
├───slider
├───snackbar
│   └───kitchen
├───switch
├───tab
├───tab-bar
├───tab-indicator
├───tab-scroller
├───textfield
│   ├───character-counter
│   ├───helper-text
│   └───icon
└───top-app-bar
```

```
H:\Development\svelte-material-ui\site\src\routes\demo>tree /f

    button.svelte
    card.svelte
    checkbox.svelte
    chips.svelte
    data-table.svelte
    dialog.svelte
    drawer.svelte
    elevation.scss
    elevation.svelte
    fab.svelte
    icon-button.svelte
    image-list.scss
    image-list.svelte
    linear-progress.scss
    linear-progress.svelte
    list.svelte
    menu-surface.scss
    menu-surface.svelte
    menu.svelte
    paper.svelte
    radio.svelte
    ripple.svelte
    select.svelte
    slider.svelte
    snackbars.svelte
    switch.svelte
    tabs.svelte
    textfield.svelte
    theme.scss
    theme.svelte
    top-app-bar-iframe.svelte
    top-app-bar.svelte
    typography.scss
    typography.svelte
```

There is a few mismatches in there but some wouldn't have routes anyway.

**Question**: Could it be done via SCSS in anyway? I bet someone could :o)

**Comment by MintyMods** [comment]
@hperrin can you tag this as a 'good first issue'?

**Comment by Egnus** [comment]
I might find sometime in the following days/weeks for this, let's see if I can add also the code inlined in every page like Svelte API docs are.

**Comment by hperrin** [comment]
Yeah, this is a great suggestion.

**Comment by hperrin** [comment]
In the layout file there’s an array of all the components and their demo pages. That might be a good place to put the source URLs. Then that same layout component could build the link to the source.
