### ISSUE TITLE
Outlined Select component has error

### ISSUE THREAD

**Issue by tomashornak** [hperrin/svelte-material-ui#97]
Hello.
I'm quite new to Svelte so maybe I'm doing something wrong.
When I create `Select` component with variant=`outlined` I get the following error:
```
component.js:72 Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at Object.removeNotchWidthProperty (component.js:72)
    at MDCNotchedOutlineFoundation.closeNotch (foundation.js:86)
    at MDCNotchedOutline.closeNotch (component.js:61)
    at Object.closeOutline (component.js:446)
    at MDCSelectFoundation.notchOutline (foundation.js:226)
    at MDCSelectFoundation.handleChange (foundation.js:148)
    at MDCSelect.initialSyncWithDOM (component.js:152)
    at MDCSelect.MDCComponent (component.js:37)
    at new MDCSelect (component.js:41)
    at Select.svelte:88
```

The component's code:
```html
<script>
    import Select, { Option } from '@smui/select';
    export let options = [];
    export let value = '';
</script>

<Select variant="outlined" bind:value>
    <Option value="" />
    {#each options as optn}
        <Option value={optn} selected={optn === value}>{optn}</Option>
    {/each}
</Select>
```

Thank you for help

**Comment by andy37380** [comment]
you miss the label

`<Select variant="outlined" bind:value label="some label"> `

**Comment by tomashornak** [comment]
I see now. I was hoping to create `<Select />` without a label but I can see examples are all with labels.
Thank you for explaining. Closing issue

**Comment by MintyMods** [comment]
@tomashornak according to the [material design docs](https://material.io/develop/web/components/input-controls/select-menus/) the label is optional:-

> A label is not required if a separate, adjacent label is provided elsewhere. To correctly style MDC Select without a label, add the class mdc-select--no-label and remove the label from the structure.

The SMU code has the following which suggests you should be able to specify a property of `noLabel=true` or by assigning the label prop to null:-

```
  {#if variant === 'outlined'}
    <NotchedOutline noLabel={noLabel || label == null} {...prefixFilter($$props, 'outline$')}>
      {#if !noLabel && label != null}
        <FloatingLabel
          for={inputId}
          class="{value !== '' ? 'mdc-floating-label--float-above' : ''} {label$class}"
          {...exclude(prefixFilter($$props, 'label$'), ['class'])}
        >{label}<slot name="label"></slot></FloatingLabel>
      {/if}
    </NotchedOutline>
  {/if}
```

I haven't used the selects without a label yet but it might be worth you trying the above or maybe leave this issue open if it doesn't work as a Select without a label does seem to be a valid use case.
