### ISSUE TITLE
Cannot find @material/image-list/mixins, when trying the git repo

### ISSUE THREAD

**Issue by koudonojinchuu** [hperrin/svelte-material-ui#99]
Hi, thank you always for your great work, smui is a fantastic idea!
I wanted to try Dialog in my app, but the import failed, so I wanted to try it directly as you are using it in your demo. So I've tried to run "npm run build" in the site/ directory of this repo, but I got this error:

```
$ npm run build

> svelte-material-ui-site@0.0.0 build /home/user1/src/svelte-material-ui/site
> sapper build --legacy

> Building...
> File to import not found or unreadable: @material/image-list/mixins.
Error: File to import not found or unreadable: @material/image-list/mixins.
    at options.error (/home/user1/src/svelte-material-ui/site/node_modules/node-sass/lib/index.js:291:26)

```

Any idea how to solve this?
Thank you!

**Comment by koudonojinchuu** [comment]
Ok I could solve it just by installing @material/image-list with npm!
So it would be good to commit this dependency to the package.json.
Now I have a new problem though:
$ npm run build

> svelte-material-ui-site@0.0.0 build /home/user1/src/svelte-material-ui/site
> sapper build --legacy

> Building...
> Invalid CSS after "...eting-functions": expected expression (e.g. 1px, bold), was ".all()) {"
Error: Invalid CSS after "...eting-functions": expected expression (e.g. 1px, bold), was ".all()) {"
    at options.error (/home/user1/src/svelte-material-ui/site/node_modules/node-sass/lib/index.js:291:26)

**Comment by koudonojinchuu** [comment]
Ok I could make progress by installing sass and removing node-sass, with npm install and npm remove.

**Comment by koudonojinchuu** [comment]
Now I have, after installing several more subpackages from @material, this error:

$ npm run dev

> svelte-material-ui-site@0.0.0 dev /home/user1/src/svelte-material-ui/site
> sapper dev -p 5000

✗ server
Can't find stylesheet to import.
  ╷
5 │ @forward "@material/theme" as mdc-theme-* hide $mdc-theme-red-50, $mdc-theme-red-100, $mdc-theme-red-200, $mdc-theme-red-300, $mdc-theme-red-400, [.....I truncated it.....];
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [.....I truncated it.....]
  ╵
  node_modules/@material/image-list/_mixins.import.scss 5:1  @import
  src/routes/demo/menu-surface.scss 1:9                      root stylesheet
✗ client
Two forwarded modules both define a variable named $mdc-theme-mdc-theme-linear-channel-values.
  ╷
4 │ @forward "@material/theme/constants" as mdc-theme-*;
  │ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ original @forward
5 │ @forward "@material/theme/variables" as mdc-theme-*;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ new @forward
  ╵
  node_modules/@material/top-app-bar/mdc-top-app-bar.import.scss 5:1  @import
  node_modules/@smui/top-app-bar/_style.scss 1:9                      @import
  src/routes/_app.scss 14:9                                           root stylesheet
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '/home/user1/src/svelte-material-ui/site/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
> Server crashed
✔ service worker (4.7s)
^C

**Comment by kmmbvnr** [comment]
material-componets-web project uses dart-sass implementation of sass compiler. The only compiler that has new sass features set.

I've got similar errors, and fix it by switching from node-sass to dart-sass

**Comment by mnemitz** [comment]
I think (at least from what I understand), the Mixins should not need to be installed directly for the project itself (`@smui/image-list` brings them in as a dependency, and they should be in the path in which the node-sass can read them).

I was having a similar issue though in my project, and tried experimenting with adding them directly, but then I managed to get it to work by starting fresh with:

```
npm i -D @smui/image-list
```

And then adding the import in my own SCSS file:
```
@import "@material/image-list/mixins";
                                                                                                                 
.image-list {                                                                                                                                                                  
    @include mdc-image-list-standard-columns(5);                                                                                                                               
    max-width: 680px;                                                                                                                                                          
}  
```
Running a fresh `npm run build` did the trick

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
